### ISSUE TITLE
foutje bij rubbing_damage_perc

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#102]
In de `calculate_regeneration ` - functies wordt `rubbing_damage_perc` berekend obv het exact genoteerde aantal.
Maar soms is er een aantalsklasse genoteerd, en dan zou het percentage berekend moeten worden obv dat aantal (approx_nr_regeneration).

Het percentage zou ook berekend moeten worden bij alle hoogteklasses en niet enkel bij de"A2".

Het is wel OK dat percentage NA is wanneer er geen verjonging is (0) en number_browsed = 0.

Ik heb dat nog niet aangepast, omdat ik denk dat jij dat mooier kan oplossen.

**Comment by leymanan** [comment]
check voor ` regeneration_by_plot_height(_species) ` zeker eens bv plot 755, species 20, heightclass 2000: daar is `rubbing_damage_perc ` Inf wegens geen A2 
(!! maar er staat ook een NA bij number_class (wel exact aantal genoteerd), dus enkel A2 uitbreiden met A1 zou ook de oplossing nog niet zijn.

`rubbing_damage_perc `in `data_regeneration `is wel correct berekend voor dat record (50%)

Ik weet niet hoe je dat gaat corrigeren, maar misschien goed o m in achterhoofd te houden dat 
niet alle A1-records een aantalsklasse hebben (maar dan wel een exact aantal).
Ik weet dat dat niet helemaal correct is, maar probleem is dat we met deels oude data werken, en dat correctie moeilijk is. 
Daarom lijkt het me practischer om - als code aangepast wordt - eventueel te implementeren dat als exact aantal niet becshikbaar is, aantalsklasse gebruikt moet worden.

Voor de rest van package stelt probleem zich niet.

Maar als je dat echt niet ziet zitten, schrijf ik wel code die voorafgaand elk exact aantal omzet naar de desbetreffende aantalsklasse.
Ik heb dat nu ook (in omgekeerde richting) al gedaan voor de A2.

**Comment by leymanan** [comment]
bijkomend zag ik net dat `rubbing_damage_perc` in `reg_by_plot_(height_species)` ook NA is, terwijl er wel een opname was en dat dus '0' moet zijn (`game_impact_reg ` = TRUE bij plotinfo )

Idem dito voor `browse_index `: NA in `herblayer_by_plot`, terwijl het 100 of `no browsing observed` zou moeten zijn (`game_impact_veg ` = TRUE bij plotinfo )

**Comment by leymanan** [comment]
ter aanvulling: zie ook issue #111

**Comment by ElsLommelen** [comment]
> In de `calculate_regeneration ` - functies wordt `rubbing_damage_perc` berekend obv het exact genoteerde aantal.
> Maar soms is er een aantalsklasse genoteerd, en dan zou het percentage berekend moeten worden obv dat aantal (approx_nr_regeneration).

Moet er in dit geval ook een `min_rubbing_damage_perc` en `max_rubbing_damage_perc` gegeven worden?  Bij het eerste voorbeeld dat ik bekeek, lag het rubbing_damage_perc tussen 20 en 50 %, dus bij die aantalsschattingen kan die vork tussen min en max blijkbaar tamelijk breed zijn.
We kunnen het uiteraard ook gelijkaardig doen aan `nr_regeneration`: de variabele `rubbing_damage_perc` behouden as is, dus enkel ingevuld ingeval van exacte aantallen, en daarnaast de variabelen `approx_rubbing_damage_perc`, `min_rubbing_damage_perc` en `max_rubbing_damage_perc` toevoegen die overal ingevuld worden (waarbij `min_rubbing_damage_perc` afgeleid is van `max_number_of_regeneration` en omgekeerd).

(Ter info: deze berekening gebeurt in `load_data_regeneration()`, niet in de calculate-functies.)

**Comment by ElsLommelen** [comment]
> Het percentage zou ook berekend moeten worden bij alle hoogteklasses en niet enkel bij de"A2".

Bedoel je dat er equivalent aan de aantallen een onderscheid gemaakt moet worden tussen 'established' (A2) en 'seedlings' (A1)?

En als je op de vorige vraag aangegeven hebt om het met min en max te doen, zet ik dat hier dan ook om naar een gemiddelde met betrouwbaarheidsintervallen?  En daarnaast uiteraard ook de approx.

**Comment by ElsLommelen** [comment]
> bijkomend zag ik net dat `rubbing_damage_perc` in `reg_by_plot_(height_species)` ook NA is, terwijl er wel een opname was en dat dus '0' moet zijn (`game_impact_reg ` = TRUE bij plotinfo )
> 
> Het viel me op dat in de calc-functies `sum(.data$rubbing_damage_number, na.rm = TRUE)` 0 wordt als `rubbing_damage_number `overal NA is. Met als gevolg dat `not_na_rubbing ` soms 1 is, terwijl er geen enkele opname van rubbing_damage was
> 
> ```
> not_na_rubbing = sum(!is.na(.data$rubbing_damage_perc)),
> ```
> 
> Misschien beter om dit obv plotinfo (`game_impact_reg`) te bepalen?
> 
> Ook oppassen met
> 
> ```
> rubbing_damage_perc =
>         ifelse(
>           .data$not_na_rubbing > 0 & .data$rubbing_damage_perc > 0,
>           .data$rubbing_damage_perc,
>           NA
>         )
> ```
> 
> dit wil zeggen dat als rubbing_damage_perc = 0 , het omgezet wordt naar NA terwijl het 0 moet blijven (enkel wanneer > 0 & een opname, dan wordt de waarde behouden)
> 
> ? beter:
> 
> ```
> rubbing_damage_perc =
>         ifelse(
>           .data$not_na_rubbing == 0 , NA, 
>           .data$rubbing_damage_perc
>         )
> ```
> 
> Of nog beter
> 
> ```
> rubbing_damage_perc =
>         ifelse(
>           .data$game_impact_reg == FALSE,
>           NA, 
>           .data$rubbing_damage_perc
>       )
> ```

Dit heb ik intussen opgelost: toevallig ontdekte ik zelf die fout ook, en via 'blame' en de commit waarin dit aangepast was, ben ik bij issue #33 uitgekomen.  Ik heb dit opgelost in commit 92ddd01, en ik heb [onderaan issue 33](https://github.com/inbo/forrescalc/issues/33#:~:text=2%20hours%20ago-,Info%20over%20bug%3A,-Bovenstaande%20was%20opgelost) wat uitleg geschreven over deze bug.  Pas nadien zag ik dat die hier ook vermeld stond...

**Comment by ElsLommelen** [comment]
Euh, behalve die bug begrijp ik eigenlijk niet heel goed hoe ik dit issue zou moeten oplossen.  Het moet niet enkel voor A2 zijn, maar betekent dit dat ik de aantallen voor A2 en A1 samentel, of dat ik afzonderlijke rubbing_damage_perc bereken voor A2 en A1?  (In dat laatste geval gaan er wel resultaten met `Inf` blijven, vrees ik, want er zijn wel enkele plots zonder regeneratie in A1 of A2, want delen door 0 geeft `Inf`.)
Ah, of vervang ik die `Inf` evt. door `NA` (oftewel NA geven als n_regeneration 0 is)?  Redenering: als er geen boompjes zijn, kunnen we eigenlijk niet inschatten of ze beschadigd zijn.
En als het over klassen gaat, werk ik dan met min en max erbij (zoals voorgesteld in een commentaar hierboven)?

Een hoop 'inhoudelijke' knopen om door te hakken voor u, maar het is een kleintje om het verder in orde te brengen als ik goed begrijp wat er moet gebeuren.

**Comment by leymanan** [comment]
> (In dat laatste geval gaan er wel resultaten met `Inf` blijven, vrees ik, want er zijn wel enkele plots zonder regeneratie in A1 of A2, want delen door 0 geeft `Inf`.)
> Ah, of vervang ik die `Inf` evt. door `NA` (oftewel NA geven als n_regeneration 0 is)? Redenering: als er geen boompjes zijn, kunnen we eigenlijk niet inschatten of ze beschadigd zijn.

Ja, dat lijkt me meest correcte: als `nr_of_regeneration = 0` (met percentage = Inf), dan sowieso `rubbing_damage_perc = NA`

**Comment by leymanan** [comment]
> Het moet niet enkel voor A2 zijn, maar betekent dit dat ik de aantallen voor A2 en A1 samentel, of dat ik afzonderlijke rubbing_damage_perc bereken voor A2 en A1?

op plot-niveau werken we met `seedlings `(obv A1) en `established `(obv A2): daar zou `rubbing_damage_perc `afzonderlijk voor berekend moeten worden:    

- `calculate_regeneration_plot()`
- `calculate_regeneration_core_area_species()`

Zodra `heightclass `vermeld wordt in de resultaten, moet geen onderscheid meer gemakt worden tss A1 en A2, maar wordt `rubbing_damage_perc `berekend per hoogteklasse

- `calculate_regeneration_plot_height()`
- `calculate_regeneration_plot_height_species()`
- `calculate_regeneration_core_area_height_species()`

**Comment by leymanan** [comment]
> **EDIT:** ik heb intussen gemerkt dat deze berekening zowel in `load_data_regeneration()` als de calculate-functies gebeurt, en bovenstaande in deze commentaar gaat over `load_data_regeneration()`. Maar ik neem aan dat de vraag over de calculate-functies gaat, of gaat dit ook over `load_data_regeneration()`?

Inderdaad vooral met calculate-functies in het achterhoofd.
Ik zag dat `rubbing_damage_perc` ook berekend wordt in de load-functie, maar daar wordt in de calculate-functie niet verder mee gewerkt (dat klopt toch?).

Dus voor mij is het ook goed om die berekening volledig weg te halen uit de load-functie, lijkt me properder (?).

**Comment by leymanan** [comment]
> Moet er in dit geval ook een `min_rubbing_damage_perc` en `max_rubbing_damage_perc` gegeven worden? Bij het eerste voorbeeld dat ik bekeek, lag het rubbing_damage_perc tussen 20 en 50 %, dus bij die aantalsschattingen kan die vork tussen min en max blijkbaar tamelijk breed zijn. We kunnen het uiteraard ook gelijkaardig doen aan `nr_regeneration`: de variabele `rubbing_damage_perc` behouden as is, dus enkel ingevuld ingeval van exacte aantallen, en daarnaast de variabelen `approx_rubbing_damage_perc`, `min_rubbing_damage_perc` en `max_rubbing_damage_perc` toevoegen die overal ingevuld worden (waarbij `min_rubbing_damage_perc` afgeleid is van `max_number_of_regeneration` en omgekeerd).
> 
> (Ter info: deze berekening gebeurt in `load_data_regeneration()`, niet in de calculate-functies.)

Meest correcte zou inderdaad zijn om ook hier een `min_rubbing_damage_perc` en `max_rubbing_damage_perc` te geven, maar zeker ook een `approx_rubbing_damage_perc` en een `mean_rubbing_damage_perc` .
Dus helemaal conform `nr_of_regeneration_ha`. 

Dus `rubbing_damage_perc` niet echt behouden "as is", eerder vervangen door een `approx_rubbing_damage_perc` met een waarde voor alle waarnemingen (exacte aantallen en aantalsklasses)
Zo werkt `approx_nr_of_regeneration_ha` toch ook, niet?

Dacht even dat ik mijn opmerking mbt load-functie van hierboven zou moeten herroepen , omdat voor `nr_of_regeneration` de berekeningen van `min` en `max` daar gebeuren.
Maar een percentage is toch iets anders dan totalen, dus dat moet volgens mij toch in elke calculate-functie herberekend warden.

**Comment by ElsLommelen** [comment]
> Inderdaad vooral met calculate-functies in het achterhoofd. Ik zag dat `rubbing_damage_perc` ook berekend wordt in de load-functie, maar daar wordt in de calculate-functie niet verder mee gewerkt (dat klopt toch?).
> 
> Dus voor mij is het ook goed om die berekening volledig weg te halen uit de load-functie, lijkt me properder (?).

Zou het kunnen dat dit destijds toegevoegd is aan die load-functie voor gebruikers die de detailgegevens met de load-functie inladen en deze gegevens rechtstreeks gebruiken?  Sowieso mag het voor mij weg hoor, als dit niet meer relevant is, ik probeer alleen maar even te helpen afvragen waarom het evt. nuttig zou kunnen (geweest) zijn.  Je ziet maar, zoals je hierboven aangeeft: dat percentage is op elk niveau anders, dus op elk niveau kan het relevant zijn om dat te berekenen.  Vraag is vooral: op welk niveau is het voor u nuttig om te gebruiken?

**Comment by leymanan** [comment]
rubbing_perc is relevant op elk niveau:
- plot
- plot-height
- plot-height-species

en dit voor CP en CA

Maar volgens mij niet op het niveau van load_data: dat komt eigenlijk overeen met niveau van plot-height-species
maar zou dus eigenlijk dubbel berekend worden.
Dus voor mij mag het bij de load-functie verwijderd worden.

Maar door dit nu zo te benomen, merk ik dat we geen regeneration_by_plot_species berekenen 
(mbv  calculate_regeneration_plot_species.R)

Zal misschien ook ooit een reden voor geweest zijn, mogelijks dat dat in de oude rapporten niet op die manier gerapporteerd werd.
Maar ljjkt me toch opportuun. 
Voor core area's hebben we het wel.
Sorry!
Ik maak er een nieuw issue van: zie #125

**Comment by ElsLommelen** [comment]
Dit lijkt allemaal iets complexer (en meer typwerk) dan verwacht.  Voor de zekerheid een klein vraagje in dit verband: is de `plotarea_ha` telkens hetzelfde voor alle A2 of alle A1 binnen een plot_id (of subplot_id ingeval van CA)?  Ik vermoed van wel?  (Anders kan ik voor de zekerheid wel een warning toevoegen.)

(In dat geval kan ik mean, lci en uci berekenen voor het aantal seedlings en established, en vanuit die aantal zowel aantal_ha als perc_rubbing berekenen.  Dit vermijdt dat ik dezelfde code die ik nu heb voor aantal_ha, nog eens volledig moet herhalen voor aantal om perc_rubbing te berekenen.  Want inclusief die voorwaarden voor 0 vs NA is dat toch tamelijk wat code.  Hier en daar zou ik het waarschijnlijk wel met `across()` kunnen oplossen, maar niet overal, vrees ik.)

**Comment by ElsLommelen** [comment]
Ik denk dat dit issue bij deze in orde is, @leymanan?  (Behalve die nieuwe functie, dat is een apart issue.)
