### ISSUE TITLE
foutje bij calc_dendro_plot(_species_diam)

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#104]
vraag voor aanpassing berekening logs (zie ook PR AL_deadwood).

Zoals forrescalc nu werkt, wordt vol_logs = 0 gezet, zodra er levende bomen gemeten zijn. Dat is niet steeds correct.
Zou obv plotdetails moeten gebeuren (survey_deadwood_YN).
(bv. Kersselaerspleyn, 1ste decade: wel dendro, maar geen deadwood opgemeten)

**Comment by ElsLommelen** [comment]
opgelost in commit cf72ac9, veronderstel ik?  Dit onderwerp was ook aangebracht in PR #103.
