### ISSUE TITLE
liggend dood hout - intact - extra berekening

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#105]
Els, zie je het zitten om het volgende ook nog mee te nemen in het package?
Indien niet ook geen probleem!
Op dit moment bereken ik dit buiten het package.

Het gaat over het liggend dood hout (deadwood layer).
Standaard worden fragmenten ingemeten (met min en max diameter).
In de kernvlaktes (plottype = CA)  is het ook mogelijk om volledige bomen aan te duiden (dan moeten ze op terrein niet alle zijtakken inmeten, spaart veel tijd uit).
Dit wordt aangeduid in het veld `intact_fragm`: code 10 = intact, 20 = fragment (LU-list qCondLUVdagnVfm)

Indien een record aangeduid staat als `intact `moet het volume berekend worden mbv de tarieven (zoals bij staande bomen): zowel stamvolume als kroonvolume en dan beide optellen (vol_bole + vol_crown).
- dbh = `max_diam_mm `
- hoogte = `calc_length_m`

Indien een record aangeduid staat  als `fragment `mag de waarde uit het veld `calc_volume_m3` behouden blijven (wordt berekend in FieldMap als fragment).

**Comment by ElsLommelen** [comment]
Ik ben er sowieso voorstander van om alle berekeningen samen te zetten, en vermits die berekening van de tarieven intussen ook in het package zit, klinkt het alsof dat niet veel extra werk is.  Dus ja, ik zal dat nog even toevoegen (nadat de rest in orde is).

**Comment by leymanan** [comment]
super! bedankt!

**Comment by leymanan** [comment]
> * Moet dit inclusief die hoogtemodellen zijn (met berekening van `calc_height_r` en `calc_height_m`), of enkel de volumeberekening op basis van de tarifering?

Hier mag je gewoon `calc_length_m` gebruiken uit de tabel `deadwood` als hoogte, dus geen hoogtemodellen nodig.


> * Bij staand hout is er 1 maat `dbh_mm` die op 1,3 m gemeten is, maar bij liggend dood hout is er voor elk uiteinde een diameter (dus 2 in totaal).  Hoe ga ik hiermee om, omrekenen naar de diameter op 1.3 m van het brede uiteinde op basis van de lengte?  Gebruik ik hiervoor `calc_length_m` of `total_length_m`?

Tot nu toe gebruikte ik de diameter aan de basis, maar dat is inderdaad een kleine overschatting.
Alternatief zou zijn om via driehoeksmeting de `dbh_mm` op 1.3m te schatten, obv de diameter aan de basis = `max_diam_mm` en de totale lengte van de boom = `total_length_m`.
Maar dat is dan weer eerder een onderschatting, want een boom is geen kegel, maar eerder een soort kogelvorm: onderaan redelijk recht en pas hogerop een sterkere afbuiging.
En nog een ander alternatief  is om met de tarieven van Dagnelie de verhouding tss C0 (helemaal onderaan) en C130 te berekenen, maar dat leidt ons vrij ver en creëert ook maar een vals gevoel van nauwkeurigheid. Want als een boom omvalt, w
Maar als we dan toch moeten kiezen is de laatste optie toch 

**Dus doe maar obv `max_diam_mm` en `calc_length_m`**

**Comment by ElsLommelen** [comment]
Eventjes voor de zekerheid: ik zie in de tabel Deadwood geen variabelen `CrownVolumeReduction` en BranchLengthReduction, dus ik neem aan dat dit hier niet van toepassing is?  M.a.w. als `intact_fragm == 10`, dan mag ik er voor de berekening sowieso van uitgaan dat de boom nog compleet is?

**Comment by ElsLommelen** [comment]
Ook kom ik in het script van `calc_variables_stem_level()` `ind_sht_cop == 12` en `intact_snag == 10` tegen en die variabelen staan ook niet in tabel Deadwood.  Ik neem aan dat ik voor liggend dood hout `ind_sht_cop` gelijk mag stellen aan 10 en er dus van uit mag gaan dat het bij deze berekeningen nooit over omgevallen hakhoutstoven gaat?  Of is enkel tarief 2 relevant voor liggend dood hout, en zorg ik er dus best voor dat de berekening van tarief 1 en en de berekening van de niet intacte bomen volledig bij staand hout blijft?  (En dat ik dus enkel de berekening volgens tarief 2 in een aparte helperfunctie steek om voor zowel staand als liggend dood hout te kunnen gebruiken?)

**Comment by leymanan** [comment]
> Eventjes voor de zekerheid: ik zie in de tabel Deadwood geen variabelen `CrownVolumeReduction` en BranchLengthReduction, dus ik neem aan dat dit hier niet van toepassing is? M.a.w. als `intact_fragm == 10`, dan mag ik er voor de berekening sowieso van uitgaan dat de boom nog compleet is?

Inderdaad, liggend dood hout steeds compleet, anders wordt alles als fragment ingemeten

**Comment by leymanan** [comment]
> Ook kom ik in het script van `calc_variables_stem_level()` `ind_sht_cop == 12` en `intact_snag == 10` tegen en die variabelen staan ook niet in tabel Deadwood. Ik neem aan dat ik voor liggend dood hout `ind_sht_cop` gelijk mag stellen aan 10 en er dus van uit mag gaan dat het bij deze berekeningen nooit over omgevallen hakhoutstoven gaat? Of is enkel tarief 2 relevant voor liggend dood hout, en zorg ik er dus best voor dat de berekening van tarief 1 en en de berekening van de niet intacte bomen volledig bij staand hout blijft? (En dat ik dus enkel de berekening volgens tarief 2 in een aparte helperfunctie steek om voor zowel staand als liggend dood hout te kunnen gebruiken?)

inderdaad: liggend dood hout enkel gewone (geen hakhout, steeds intacte) bomen

**Comment by ElsLommelen** [comment]
Ik merk net dat `intact_fragm` nog niet binnengehaald werd bij `load_data_deadwood()`, dus ik doe dit nu. Behoud ik het gewoon met de waarden 10 en 20 zoals in de databank, of maak ik er een TRUE/FALSE van?  Ik neem aan dat die waarde bij aggregatie tot op plotniveau e.d. wegvalt, of misschien al direct na de berekening van de volumes?

**Comment by ElsLommelen** [comment]
Dit zou opgelost moeten zijn, test liefst nog wel even grondig of de resultaten correct zijn (en check documentatie, laat gerust weten als je niet akkoord bent met de naamgeving,...).
Ik heb hiervoor de berekening van 'bole' en 'crown' volume uit `calc_variables_stem_level()` in een aparte hulpfunctie `calc_stem_volume()` gestoken, die ik ook aanroep bij de nieuwe functie `calc_intact_deadwood()`.  Voorlopig is die hulpfunctie `calc_stem_volume()` ook extern beschikbaar, ik weet niet of dat nuttig/nodig is?  Sowieso moeten zowel voor staand als liggend dood hout vooraf enkele voorafgaande stappen gebeuren (bv. hoogtemodel berekenen of wat variabelen hernoemen of toevoegen), dus die functie rechtstreeks gebruiken is niet evident (tenzij ze beter gedocumenteerd wordt?).

(Ik heb deze stap voor liggend dood hout ook toegevoegd in `calculate_dendrometry()`, dus je moet niks aanpassen in je main script.  Ik ontdekte wel nog wat fouten in zowel `calculate_dentrometry()` als het main script, deze heb ik aangepast in aparte commits naar bug_fixes waarin ik niet verwijs naar een issue.)

**Comment by ElsLommelen** [comment]
Euh, sluit je dit issue als je dit getest hebt en het correcte resultaten geeft?  (Of je mag ook een datasetje bezorgen en het resultaat dat dit zou moeten geven, als dat eenvoudiger is.  Dan maak ik er de eerste unittest van.  ;-) )  Dat heeft uiteraard geen haast, 't is maar dat je weet dat het open blijft tot je het getest hebt en sluit.
