### ISSUE TITLE
regeneration: number_class vs exact number

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#106]
Els,
dit in een afzonderlijk issue, het sluit wel aan bij ander issues, maar ik wou het hier eens afzonderlijk onder de aandacht brengen.
Het zou me veel tijd besparen, mocht er een beetje meer inwisselbaarheid zijn in het package tss het gebruik van de aantalsklasse en het exact aantal.

Bij de standaard methodiek is het inderdaad zo dat bij A1-verjonging gewerkt wordt met aantalsklasses en bij A2-verjonging (de iets grotere) met exacte aantallen.
Het is goed om het package in die zin op te bouwen.
MAAR er zijn ook bosreservaten waar de standaard methodiek niet gevolgd werd (bv. Everzwijnbad) 
Dat zijn geen fouten, maar gewoon iets ander afspraken toendertijd.

Daarom lijkt het me het meest practische om bij A1-verjonging steeds te vertrekken van de aantalsklasse (`NumberClass`), maar als die niet ingevuld staat de info uit het exacte aantal (`Number`) te halen.
En vice versa bij de A2-verjonging.

Want nu is dat ook iets dat ik buiten het package om aanpas ...

Idem dito wanneer er een percentage berekend wordt van rubbing damage: erop letten om ook dan het goede "aantal" te nemen.

**Comment by leymanan** [comment]
Het gaat inderdaad enkel over regeneration niet dendro.

> bij `load_data_regeneration()` zie ik dat er voor het invullen van `min_number_of_regeneration` voorrang wordt gegeven aan de aantalsklasse (`min_number_of_regeneration` die afkomstig is van `NumberClass`), en als dit NA is, wordt het exacte aantal (`nr_of_regeneration`) gebruikt.

Dat klopt, maar dan wordt dus voorrang gegeven aan aantalsklasse, terwijl er soms een exact aantal ingevuld staat, wat voor de A2-verjonging correcter is.

> Voor rubbing damage wordt `GameDamage_number` uit `RegSpecies` gebruikt (en als dat niet ingevuld is en `GameImpactRegObserved` uit `PlotDetails` 10 is en er bij `RegSpecies` geen `Species` ingevuld is, krijgt het waarde 0). Klopt dit?

Dat klopt ook, maar wanneer je een percentage wil berekenen, heb je het aantal verjonging nodig, en daar moet je dan ofwel naar aantalsklasse, ofwel naar exact aantal gaan kijken.

Mijn vraag was vooral om er in 't algemeen op te letten als je aanpassingen doet, ik denk wel dat ik daar waar het fout was dat ofwel in de code aangepast heb, of het wel gevraagd heb in een of ander issue.
Maar hier nog eens uitgelicht ...

**Comment by ElsLommelen** [comment]
> > bij `load_data_regeneration()` zie ik dat er voor het invullen van `min_number_of_regeneration` voorrang wordt gegeven aan de aantalsklasse (`min_number_of_regeneration` die afkomstig is van `NumberClass`), en als dit NA is, wordt het exacte aantal (`nr_of_regeneration`) gebruikt.
> 
> Dat klopt, maar dan wordt dus voorrang gegeven aan aantalsklasse, terwijl er soms een exact aantal ingevuld staat, wat voor de A2-verjonging correcter is.

Ah, oeps, die vice versa voor A2 over het hoofd gezien.  Ok, ik pas dit bij oplossen van dit issue aan en check dan alle `load`-functies nog eens.

Voor rubbing damage zie ik inderdaad dat dit ook aangepast moet (die wordt berekend op basis van het exacte aantal).

**Comment by ElsLommelen** [comment]
(de hierboven weergegeven commit was een fout die ik intussen verwijderd heb in de git-geschiedenis, maar blijkbaar blijft die referentie hier wel staan... gewoon negeren dus!)

**Comment by ElsLommelen** [comment]
Ik heb dit opgelost door in `load_data_regeneration()` min, max en approx gelijk te stellen aan nr_regeneration ingeval van A2.  In het andere geval (A1) wordt voorrang gegeven aan de klassen om min, max en approx in te vullen, wat voor de aanpassing de algemene regel was voor min, max en approx.
(En door ook telkens te controleren op NA, vermijd ik dat de waarden NA geraken, m.a.w. als de voorkeur (klasse of aantal) niet ingevuld is, zal de andere optie behouden blijven of toegevoegd worden.)

Ik weet niet of hier nog iets anders moet gebeuren?  Hetgeen hier verder vermeld is, hangt samen met issue #102, heb ik de indruk.

**Comment by ElsLommelen** [comment]
Ik heb dit nog eens nagelezen na het afwerken van issue #102, en ik denk dat dit opgelost is?
