### ISSUE TITLE
make_table_wide()

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#110]
Het voorbeeld van deze functie werkt niet meer omdat de opgevraagde tabel niet meer bestaat in forresdat.

@leymanan Komen er in forresdat nog tabellen die toelaten om gegevens tussen verschillende periodes te vergelijken (gebruik makend van de functie `compare_periods_per_plot()`), of maak ik hier best een voorbeeld aan dat illustreert hoe gegevens uit forresdat een boomnummer kunnen meekrijgen met `compare_periods_per_plot()`, om daarna `make_table_wide()` te gebruiken om de tabel breed te maken?

**Comment by leymanan** [comment]
`compare_periods_per_plot `vergelijkt bv. stamtal of grondvlak voor een plot doorheen de tijd.
Daar zit geen link meer in naar individuele bomen (met boomnummer).
Was verschil vergeten tss beide functies en blijkbaar berekent `compare_periods_per_plot `al direct een verschil,
daar waar `make_table_wide ` gewoon `pivot_wider` is.

Misschien moeten we die functie gewoon uit het package halen?
Wie met R werkt, zou moeten weten hoe hij van long naar wide moet gaan.

Alternatief is als vb gewoon `dendro_by_plot ` wide maken (dus zonder verschil in stamtal tsss 2 periodes).
Maar misschien weinig meerwaarde?

**Comment by ElsLommelen** [comment]
Ter herinnering: die `make_table_wide()` is destijds gemaakt omdat we met het probleem zaten dat tabellen in forresdat beter in lang formaat opgeslagen werden (meest bruikbaar voor statistiek), en dat je dacht dat het voor Kris te moeilijk zou zijn om die zelf naar breed formaat om te zetten.  Op zich is het gewoon een wrapper rond `pivot_wider()` met wat minder argumenten en meer duidelijkheid in naamgeving en documentatie (of dat was toch de intentie).  Idee is uiteraard ook dat het voorbeeld iets is wat Kris kan gebruiken, dus liefst iets wat hij nodig heeft.  Of als hij intussen met `pivot_wider()` zijn plan kan trekken en deze functie overbodig geworden is, mag ze uiteraard weg.

**Comment by leymanan** [comment]
ik vrees dat Kris teveel ander werk heeft, om ooit met R aan de slag te gaan ....
Spijtig wel ...
Maar je hebt gelijk, is nu niet veel werk meer om daar toch een voorbeeld aan toe te voegen, en de functie toch te behouden.
Ik zou als voorbeeld dan "dendro_by_plot_species" nemen, met variabele `vol_alive_m3_ha`.
Bedankt!

**Comment by ElsLommelen** [comment]
Ter info: behalve `vol_alive_m3_ha` ook `number_of_trees_ha` toegevoegd, omdat ik 2 voorbeeldkolommen nodig had om te illustreren wat mis kan gaan als je niet alles als 'grouping_variable' toevoegt.
