### ISSUE TITLE
browsing/rubbing: NA = 0 - aanvulling bij issue #102

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#111]
Ter aanvulling bij issue #102 : met Peter VdK besproken, en blijkbaar brengt het veel workload met zich mee, om ook 0-waardes in te voeren bij browsing en rubbing.
Tot nu toe werd er steeds achteraf bij de datacontrole een update-query uitgevoerd die alle NA's omzette naar 0 (gamedamage) of 100 (no browsing). Maar dat is weer een extra bewerking.
Daarom zou het goed zijn om in forrescalc de code zodanig aan te passen dat - als game_impact_reg/game_impact_veg == TRUE én GameDamage_number/BrowseIndex = NA - dit als een '0' beschouwd wordt.

**Comment by ElsLommelen** [comment]
Ik neem aan dat ik dit oplos door een extra argument 'plotinfo' toe te voegen aan deze functies, zoals ik ook bij de functies `calculate_dendro_xxx()` gedaan heb?  (Zie discussie in PR #103)

**Comment by leymanan** [comment]
inderdaad, en dan obv `GameImpactVegObserved` en `GameImpactVegObserved` bepalen of het een 0 of een NA is.
Bedankt!

**Comment by ElsLommelen** [comment]
Ik zie dat er voor de verjonging in bv. `calculate_regeneration_plot()` momenteel al berekeningen staan als
```
mean_number_established_ha =
             ifelse(is.na(.data$mean_number_established_ha)
                    & .data$mean_number_seedlings_ha > 0
                    , 0
                    , .data$mean_number_established_ha)
```
Laat ik die staan, of vervang ik die ook meteen door:
```
mean_number_established_ha =
             ifelse(is.na(.data$mean_number_established_ha)
                    & .data$survey_reg
                    , 0
                    , .data$mean_number_established_ha)
```

Of moet ik de `.data$mean_number_seedlings_ha > 0` ook behouden, dus:
```
mean_number_established_ha =
             ifelse(is.na(.data$mean_number_established_ha)
                    & .data$mean_number_seedlings_ha > 0
                    & .data$survey_reg
                    , 0
                    , .data$mean_number_established_ha)
```
Als ik de plotinfo toch inlees, is het een kleintje om dat even te doen als dit correcter is.

**Comment by leymanan** [comment]
de berekening (0 vs NA) obv survey_reg is correcter, onderstaande is dus voldoende

```
mean_number_established_ha =
             ifelse(is.na(.data$mean_number_established_ha)
                    & .data$survey_reg
                    , 0
                    , .data$mean_number_established_ha)
```

**Comment by ElsLommelen** [comment]
N.a.v. je finale opmerking in issue #33 heb ik die plotinfo terug verwijderd en lijkt het me gemakkelijker om die 0 vs NA voor regeneratie ook op te vangen in de load-functie, net zoals we het voor `rubbing_damage_number` doen.  Anders dan bij `load_data_dendrometry()` (waar op bomen en niet op plots gefocust wordt), worden bij `load_data_regeneration()` sowieso toch al alle plots meegenomen, dus is het gemakkelijker om hier meteen die 0 vs NA in orde te brengen.

**Comment by ElsLommelen** [comment]
Na het iets grondiger bekijken van `calculate_regeneration_plot()` ben ik toch niet heel zeker of we dit allemaal juist berekenen, het wringt ergens een beetje.

Mijn eerste gedacht was: als we die plotinfo terug verwijderen en we moeten ons baseren op de ingevoerde dataset om na te gaan of het 0 of NA moet zijn, dan klopt dit wel:

```
mean_number_established_ha =
             ifelse(is.na(.data$mean_number_established_ha)
                    & .data$mean_number_seedlings_ha > 0
                    , 0
                    , .data$mean_number_established_ha)
```
Want als we een resultaat hebben voor de seedlings, dan moet er ook naar de established gekeken hebben, en omgekeerd.  Dus het is compleet logisch om op die manier een 0 toe te kennen.

Maar toen vroeg ik me af: als we hier een 0 geven, hadden we dan eigenlijk niet beter bovenaan de berekening (voor de aggregatie) ook al een 0 gegeven?  Ingeval er voor geen enkele grootteklasse boompjes geteld zijn, dan is die 0 wel correct, maar als er bij bepaalde grootteklassen wel bomen geteld zijn en bij andere grootteklassen niet, dan zouden er eigenlijk ook nullen toegevoegd moeten worden om min en mean te berekenen.  Of toch niet?

Dus anders uitgelegd gaat het over de volgende kwestie: moet er voor de aggregatie voor elke grootteklasse een aantal meegeteld worden (dus een 0 als die grootteklasse niet aanwezig is), of wordt de aggregatie genomen van alle grootteklassen die niet 0 zijn?  In het eerste geval zal het minimum en de lci 0 zijn omdat je rekening houdt met het feit dat niet alle grootteklassen aanwezig zijn.

Nog iets anders wat lichtjes wringt, is: het aantal soorten is eigenlijk het aantal soorten van de seedlings en de established samen.  Dus soms heb je 0 seedlings, maar toch 3 soorten.  En als je wel seedlings en established hebt, weet je eigenlijk niet voor beide afzonderlijk hoeveel soorten er zijn.  Of maakt dat niet uit?

**Comment by leymanan** [comment]
> Nog iets anders wat lichtjes wringt, is: het aantal soorten is eigenlijk het aantal soorten van de seedlings en de established samen. Dus soms heb je 0 seedlings, maar toch 3 soorten. En als je wel seedlings en established hebt, weet je eigenlijk niet voor beide afzonderlijk hoeveel soorten er zijn. Of maakt dat niet uit?

al snel hierop een antwoord: 
1) sowieso moeten we op plotniveau weten hoeveel soorten er zijn (ongeacht of het seedling of established is)
2) daarnaast zou het misschien (?) interessant zijn om te weten hoeveel soorten er zijn die doorgroeien (= enkel established).
Dus naast `number_of_tree_species`, ook nog `nr_of_tree_speciesestablished` en dan logischerwijze ook maar `nr_of_tree_species_seedlings` toevoegen
Maar leidt ons dat niet wat te ver?

**Comment by ElsLommelen** [comment]
> 2\. Maar leidt ons dat niet wat te ver?

Dat laat ik volledig aan u om te oordelen.  Dat toevoegen op zich is niet zo heel veel werk, maar er moet dan ook nog documentatie (metadata) voor toegevoegd worden, en het is voor gebruikers weer een extra variabele (wat een voordeel kan zijn als ze die variabele net nodig hebben, maar een nadeel om door de bomen het bos nog te zien).

In elk geval wel al goed om te horen dat het totaal aantal soorten voor seedlings + established wel nuttig is.  Voor de eventuele andere variabelen laat ik je de overweging zelf maken.

**Comment by leymanan** [comment]
Kan je anders toch nog `nr_of_tree_species_established` meenemen?
Het aantal soorten enkel in de kruidlaag (seedlings) lijkt me niet relevant

**Comment by leymanan** [comment]
> Mijn eerste gedacht was: als we die plotinfo terug verwijderen en we moeten ons baseren op de ingevoerde dataset om na te gaan of het 0 of NA moet zijn, dan klopt dit wel:
> 
> ```
> mean_number_established_ha =
>              ifelse(is.na(.data$mean_number_established_ha)
>                     & .data$mean_number_seedlings_ha > 0
>                     , 0
>                     , .data$mean_number_established_ha)
> ```
> 
> Want als we een resultaat hebben voor de seedlings, dan moet er ook naar de established gekeken zijn, en omgekeerd. Dus het is compleet logisch om op die manier een 0 toe te kennen.

inderdaad dat klopt en is logisch

> Maar toen vroeg ik me af: als we hier een 0 geven, hadden we dan eigenlijk niet beter bovenaan de berekening (voor de aggregatie) ook al een 0 gegeven? Ingeval er voor geen enkele grootteklasse boompjes geteld zijn, dan is die 0 wel correct, maar als er bij bepaalde grootteklassen wel bomen geteld zijn en bij andere grootteklassen niet, dan zouden er eigenlijk ook nullen toegevoegd moeten worden om min en mean te berekenen. Of toch niet?
> 
> Dus anders uitgelegd gaat het over de volgende kwestie: moet er voor de aggregatie voor elke grootteklasse een aantal meegeteld worden (dus een 0 als die grootteklasse niet aanwezig is), of wordt de aggregatie genomen van alle grootteklassen die niet 0 zijn? In het eerste geval zal het minimum en de lci 0 zijn omdat je rekening houdt met het feit dat niet alle grootteklassen aanwezig zijn.

Dit snap ik niet helemaal: het is toch niet omdat er een hoogteklasse ontbreekt dat het min van alle waarnemingen '0' wordt? 

Want meest correcte is inderdaad dat er al voor de aggregatie nullen toegekend worden aan alle hoogteklasses waar geen waarneming gebeurd is (veiligste obv `survey_reg`, want ook nodig wanneer er nergens iets geteld werd)

**Comment by ElsLommelen** [comment]
> Dit snap ik niet helemaal: het is toch niet omdat er een hoogteklasse ontbreekt dat het min van alle waarnemingen '0' wordt?

Als er een hoogteklasse ontbreekt (= geen bomen van die hoogteklasse gezien zijn), dan heeft die hoogteklasse 0 waarnemingen.  En als je dan het minimum aantal waarnemingen op plotniveau gaat berekenen, dan zou dat 0 zijn omdat er een hoogteklasse bij is waarvoor er 0 waarnemingen zijn.

Maar terwijl ik dit antwoord schrijf, weet ik weer niet meer goed of dit de meest logische benadering is.  Want als er vaak een hoogteklasse ontbreekt, zal je zeer vaak voor je interval de minimumwaarde 0 hebben.  En ik heb nog even de functie getest waarmee het betrouwbaarheidsinterval met lci en uci bepaald wordt (`sum_intervals()`), en die gaat bij de (vaak voor aantallen gebruikte) logaritmische schaal ingeval van het toevoegen van records met min 0, mean 0 en max 0 de mist in: lci wordt 0, en uci wordt oneindig, wat we eerder gecorrigeerd hebben door het dezelfde waarde te geven als het gemiddelde (om bij enkel nullen geen problemen te krijgen).

Dus misschien is dit toch niet zo'n goed idee, en behouden we beter de huidige situatie, waarbij we achteraf een 0 toekennen in de gevallen waar er geen seedlings of established verjonging gezien is?

> Want meest correcte is inderdaad dat er al voor de aggregatie nullen toegekend worden aan alle hoogteklasses waar geen waarneming gebeurd is (veiligste obv `survey_reg`, want ook nodig wanneer er nergens iets geteld werd)

Die gegevens krijgen bij het opladen via de load-functie een 0 vs. NA op basis van `survey_reg`, dus die info is al in de dataset `data_regeneration` aanwezig.   Het is vrij simpel: als er records zijn op plotniveau (inclusief de waarnemingen met subcircle NA en number_of_regeneration 0 waar geen verjonging was maar wat wel geteld is), dan zijn er waarnemingen gebeurd, en anders niet.

**Comment by leymanan** [comment]
> Als er een hoogteklasse ontbreekt (= geen bomen van die hoogteklasse gezien zijn), dan heeft die hoogteklasse 0 waarnemingen. En als je dan het minimum aantal waarnemingen op plotniveau gaat berekenen, dan zou dat 0 zijn omdat er een hoogteklasse bij is waarvoor er 0 waarnemingen zijn.

Dat is toch niet correct? 
Stel heel veel waarnemingen in klasses 0-30, 30-50, 50-100, en bij één klasse niks.
Dan is globaal over alle hoogteklasses het minimum toch niet 0 waarnemingen? 
Of begrijp ik iets niet goed?

**Comment by ElsLommelen** [comment]
> Dat is toch niet correct?
> Stel heel veel waarnemingen in klasses 0-30, 30-50, 50-100, en bij één klasse niks.
> Dan is globaal over alle hoogteklasses het minimum toch niet 0 waarnemingen?
> Of begrijp ik iets niet goed?

Ja, inderdaad, ik ga dat idee laten vallen en het laten zoals het is.  (Behalve die `nr_of_tree_species_established` toevoegen.)

**Comment by ElsLommelen** [comment]
Blijkbaar was het toch nog niet helemaal in orde in de zin dat ik bij wijze van test eens een record met verjonging NA i.p.v. 0 toegevoegd heb (dus waar geen observaties gedaan zijn, dat zat niet in de db), en dit gaf voor verjonging als resultaat 0 en niet NA.  Wat me niet de bedoeling leek.  Na een beetje gepruts heb ik dit in orde gekregen voor `calculate_regeneration()`: input met nr_regeneration NA geeft eindresultaat NA, en input met nr_regeneration 0 geeft eindresultaat 0.  Ik krijg wel nog telkens als aantal soorten 0, ik weet niet of ik daar ook NA van moet maken ingeval de verjonging NA is?  (Dit kan ik dan enkel aanpassen op basis van het resultaat van het aantal verjonging, want de input voor veld `species` is hetzelfde voor een record waar 0 soorten gezien zijn en waar niet gekeken is (telkens NA).  Maar een kleintje om dat even te doen als het juister is.)

**Comment by leymanan** [comment]
> Blijkbaar was het toch nog niet helemaal in orde in de zin dat ik bij wijze van test eens een record met verjonging NA i.p.v. 0 toegevoegd heb (dus waar geen observaties gedaan zijn, dat zat niet in de db)

je bedoelt dan toch met survey_reg = FALSE?

> Ik krijg wel nog telkens als aantal soorten 0, ik weet niet of ik daar ook NA van moet maken ingeval de verjonging NA is?

aantal soorten mag/moet 0 zijn als survey_reg = TRUE én geen verjonging waargenomen

**Comment by ElsLommelen** [comment]
> > Blijkbaar was het toch nog niet helemaal in orde in de zin dat ik bij wijze van test eens een record met verjonging NA i.p.v. 0 toegevoegd heb (dus waar geen observaties gedaan zijn, dat zat niet in de db)
> 
> je bedoelt dan toch met survey_reg = FALSE?
> 
Ja, als `survey_reg = FALSE`, dan zou `load_data_regeneration()` een record moeten geven waarin nr_of_regeneration NA is (en hoogteklasse en ...), en dat heb ik 'nagebootst' bij mijn test (omdat er zo geen record in zat als ik het uit de databank haalde).

> > Ik krijg wel nog telkens als aantal soorten 0, ik weet niet of ik daar ook NA van moet maken ingeval de verjonging NA is?
> 
> aantal soorten mag/moet 0 zijn als survey_reg = TRUE én geen verjonging waargenomen enkel NA als survey_reg = FALSE

Ok, dan zal ik dit nog aanpassen (dat dit ook NA moet worden ingeval de verjonging niet opgenomen is).  En ook eens kijken bij de andere calculate-functies van verjonging in hoeverre dezelfde zaken nog moeten aangepast worden.

**Comment by leymanan** [comment]
Bedankt!

**Comment by leymanan** [comment]
Ja, dat zou fijn zijn!
Bedankt!

**Comment by ElsLommelen** [comment]
Dit issue is dus opgelost, vermoed ik, m.u.v. hetgeen ook beschreven is in issues #102 en #125.  (Nog wel uitgebreid te testen nadat issue #102 ook opgelost is.)

**Comment by ElsLommelen** [comment]
Euh, wacht nog maar even met dit goed te keuren, ik ga eerst kijken of ik het voor vegetatie ook niet gemakkelijker kan oplossen in de load-functie, zoals ik uiteindelijk ook met regeneratie gedaan heb.

**Comment by ElsLommelen** [comment]
Voila, browsing is nu in orde gemaakt in de load-functie en de andere (bij nader inzien foute) aanpassingen zijn terug verwijderd.

Maar ik zie dat bij `load_data_vegetation()` de bedekkingen van de verschillende lagen NA zijn omdat 0 niet bij de opties van de scores staat.  Ik neem aan dat ik dat best ook aanpas zodat `load_data_vegetation()` ingeval van geen mossen coverage 0 % geeft i.p.v. NA?  (Vermits ik het alvast uitgewerkt heb, push het meteen even, ik revert wel als het niet nodig was.)

**Comment by ElsLommelen** [comment]
Sorry, mijn fout.  Terug verwijderd.  Zal ik dat voor die datacontrole bij issue #1 toevoegen?  Of heb je al ergens een duidelijke lijst van wat gecheckt zou moeten worden?  Of moet dit niet via R gebeuren?
Evt. kan je voor die datacontrole een nieuw issue aanmaken: relevante tekst hierboven selecteren, dan op de puntjes rechtsboven van de commentaarbox klikken en kiezen voor 'reference in new issue', moest je dat knopje nog niet eerder ontdekt hebben.

**Comment by ElsLommelen** [comment]
Verder is dit issue opgelost, neem ik aan?
