### ISSUE TITLE
read_forresdat: argument "plottype" werkt niet

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#112]
onderstaande code behoudt ook de core area's?
argument `plottype = "CP"` doet niet wat het moet doen ...
?enig idee

```
dendro_by_plot <- read_forresdat("dendro_by_plot"
                                 , repo_path = path_to_git_forresdat
                                 , join_plotinfo = TRUE, plottype = "CP")
```

**Comment by ElsLommelen** [comment]
Euh, ik heb je code geprobeerd, en ik krijg:
```
> unique(dendro_by_plot$plottype)
[1] "CP"
```
Dus hier lijkt het wel in orde.
(Ik heb de laatste versie van forresdat, met een laatste commit op 14-02-2023.)

Kan je voor de zekerheid even RStudio herstarten, en evt. ook even opnieuw forrescalc installeren als je niet zeker weet of je de nieuwste versie hebt?  Dit laatste uiteraard terwijl alle andere sessies van RStudio gesloten zijn.

Wat je eens zou kunnen checken om te weten of je de nieuwste versie hebt, is de functienaam zonder haakjes intypen, en checken of dit hetzelfde geeft als hieronder.  Indien niet, dan heb je niet de recentste versie van het package.
```
> read_forresdat
function(tablename, repo_path, join_plotinfo = TRUE, plottype = c("CP", "CA")) {
  assert_that(is.logical(join_plotinfo))
  var_plottype <- match.arg(plottype)
  repo <- repository(repo_path)
  pull(repo, credentials = get_cred(repo))
  dataset <- read_vc(file = paste0("data/", tablename), root = repo)
  if (join_plotinfo) {
    assert_that(
      has_name(dataset, "plot_id"),
      msg = "No column 'plot_id' in the requested table, please add 'join_plotinfo = FALSE'" #nolint
    )
    if (has_name(dataset, "period")) {
      dataset <- dataset %>%
        left_join(
          read_vc(file = "data/plotinfo", root = repo),
          by = c("plot_id", "period")
        ) %>%
        filter(.data$plottype == var_plottype)
    } else {
      dataset <- dataset %>%
        left_join(
          read_vc(file = "data/plotinfo", root = repo),
          by = "plot_id"
        ) %>%
        filter(.data$plottype == var_plottype)
    }
  } else {
    warning(
      paste(
        "Data include all plottypes, use 'join_plotinfo = TRUE' if you only want data of a specific plottype (defaults to 'CP' so add 'plottype = CA' if needed).", #nolint
        plottype
      )
    )
  }
  warning("The dataset only contains presence data and lacks zero observations (except for 1 observation per plot_id and period to indicate that observations are done).  Please use function add_zeros() to add zero observations when needed.") #nolint
  return(dataset)
}
<bytecode: 0x000002be3afba490>
<environment: namespace:forrescalc>
```

Als het probleem zich blijft voordoen, kan je dan even de output van volgende code doorgeven?
```
sessioninfo::session_info()
```
Alle andere info die relevant zou kunnen zijn, is ook welkom, want ik heb eerlijk gezegd absoluut geen idee waar dit zou kunnen mislopen (tenzij je niet de recentste versie van het package hebt).

**Comment by leymanan** [comment]
vrees dat het aan versie ligt, bytecode is alvast anders ;-)

**Comment by leymanan** [comment]
maar nu krijg ik foutmelding "year" not found ...

In welke branch ben jij bezig? Dat is toch reg_al?

**Comment by ElsLommelen** [comment]
Intussen in mijn nota's teruggevonden dat ik inderdaad een branch bug-fixes aangemaakt had om enkele issues op te lossen en daarna een PR naar reg_al te maken.  En anderzijds zou ik nog wat vragen van u moeten oplossen in branch deadwood.  Idee is om daarna alles samen te brengen in branch statistics-and-other-issues en dan de boel verder af te werken.

Ik zal proberen om die eerste stappen op een relatief korte termijn te zetten, zodat we terug 1 branch hebt waarin de recentste versie staat (nu is dat zowel bug-fixes als deadwood, en statistics-and-other-issues met wat extra machinerie).

**Comment by ElsLommelen** [comment]
@leymanan Kan je bij gelegenheid eens testen of je hier nog problemen mee hebt?  Ik werk dus intussen in de branch bug-fixes, waarin aanpassingen uit ongeveer alle branches zitten (zoals reg_AL), en hiermee heb ik geen problemen met het argument `plottype`.

**Comment by leymanan** [comment]
de functie werkt, als ik CP of CA aangeef.
Specifieer ik echter geen plottype, maar gebruik ik wel plotinfo = TRUE,
dan krijg ik enkel data van de CP's

```
dendro_by_plot<- read_forresdat("dendro_by_plot", path_to_git_forresdat, join_plotinfo=TRUE, plottype = c("CP", "CA"))
unique(dendro_by_plot$plottype)
# CP 
```

Heeft wel zekere logica, want  `join_plotinfo=TRUE` was initieel bedoeld om CP of CA te kunnen selecteren. En dan moet je dat ook doen.
Maar anderzijds als iemand gewoon graag weet wat de plottypes zijn ...

**Comment by ElsLommelen** [comment]
Euh, in de [documentatie](https://github.com/inbo/forrescalc/blob/2728432e4000ce1dabb71b1b50de59d9b891d99e/R/read_forresdat.R#L21) staat dat de default CP is...
Ik denk dat we dat ooit zo afgesproken hebben, vooral om te vermijden dat gebruikers zonder het te beseffen analyses zouden doen op 2 plottypen door elkaar (wat tot fouten zou kunnen leiden is vanwege verschillende plotgroottes,...).  Dit kan uiteraard herzien worden, maar misschien dan best eerst eens terug nagaan waarom we het toen aangepast hebben?  Sowieso staan de twee plottypes (uit forresdat) in de documentatie vermeld, dus een gebruiker kan het ook daar te weten komen.  ;-)

Ik ga u zelf eens laten uitzoeken waarom we dat destijds aangepast hebben, dan leer je Github ook eens op die manier gebruiken: ga naar die functie read_forresdat() in github (= link van hierboven), klik net linksboven de tekst langs Code op 'Blame', en dan krijg je voor elke regel van het document te zien in welke commit deze regel toegevoegd of aangepast is.  Klik op de commit vlak voor de aanpassing die je wil onderzoeken (documentatie van argument voor plottype), en in die commit vind je weer de verwijzing naar het issue waarin we ongetwijfeld deze aanpassing bediscussieerd hebben vooraleer ik ze uitvoerde.

Dus laat gerust weten als er nog aanpassingen moeten zijn.  Misschien wil je in de beschrijvende tekst van de documentatie ook al iets weergeven over plottype, omdat niet iedereen de volledige documentatie met beschrijving van de argumenten leest?  Of misschien wil je een extra voorbeeld met plottype CA toevoegen om de gebruiker op allerlei manieren op dit argument te wijzen?  (Zelf heb ik de gewoonte om een beetje diagonaal door een help-file te scrollen en vooral de voorbeelden te bekijken, ik weet niet hoe jij dat bekijkt?  In elk geval houd je dit best een beetje in het achterhoofd om te bepalen hoe en waar je dit soort zaken wil documenteren.)

**Comment by leymanan** [comment]
Ah nee, goed dat jij dat nog weet.
Is inderdaad een logische redenering.

En "blame": zo cool!! Kende ik nog niet!

Eens in historiek gaan kijken, en inderdaad: default (door iemand die niks kent) zouden de CP's moeten binnengehaald worden.
Maar misschien toch nog everbeterinng mogelijk?

Bv. als je `join_plotinfo = FALSE` selecteert, worden wél alle plots binnengehaald, maar zonder info over plottype.
Dat is eigenlijk nog gevaarlijker. Vooral daar zouden de CP's default moeten zijn. 

```
dendro_by_plot2<- read_forresdat("dendro_by_plot", path_to_git_forresdat, join_plotinfo=FALSE)
range(dendro_by_plot2$plot_id)
# [1]    101 171200
# alles, maar geen info over CP of CA 
```

Is het een optie om wat aanpassingen te doen zodat: 
- sowieso altijd `plottype` (en `forest_reserve`) ingelezen wordt? (zonder de andere info over surveys en zo)
- default enkel CP's ingelezen worden, zowel bij `join_plotinfo = TRUE` als bij `join_plotinfo = FALSE`
- de mogelijkheid bestaat om `plottype` te selecteren, zelfs als `join_plotinfo = FALSE` (nu geeft dat foutmelding omdat er geen veld `plottype` is)
- de mogelijkheid bestaat om beide plottypes te selecteren (dat hoeft niet persé voor mij, je kan ook beide apart inlezen en dan samenvoegen, maar kan misschien wel handig zijn)

**Comment by leymanan** [comment]
> Dus laat gerust weten als er nog aanpassingen moeten zijn. Misschien wil je in de beschrijvende tekst van de documentatie ook al iets weergeven over plottype, omdat niet iedereen de volledige documentatie met beschrijving van de argumenten leest? Of misschien wil je een extra voorbeeld met plottype CA toevoegen om de gebruiker op allerlei manieren op dit argument te wijzen? (Zelf heb ik de gewoonte om een beetje diagonaal door een help-file te scrollen en vooral de voorbeelden te bekijken, ik weet niet hoe jij dat bekijkt? In elk geval houd je dit best een beetje in het achterhoofd om te bepalen hoe en waar je dit soort zaken wil documenteren.)

Hangt een beetje af van of en hoe je mijn suggesties zou verwerken.
Ik miste alvast iets over hoe je wél alle plottypes kan meenemen.
En inderdaad toch reeds vermelding van CA en CP in de beschrijvende tekst ;-)

**Comment by leymanan** [comment]
> Moest dit een probleem zijn (= te traag), dan zouden we best overwegen wat het meest optimaal zou zijn: in forresdat aan elke tabel `plottype` (en `forest_reserve`) toevoegen (= join niet nodig, maar data-opslag iets groter), of de join telkens uitvoeren (= minder data-opslag in forresdat, maar vertraging door join). Weet jij toevallig al uit ervaring in hoeverre die join vertraagt?

Is me niet opgevallen dat het trager  gaat als ik  `load_plotinfo = TRUE` selecteer.
Omdat het toch wel over heel veel tabellen gaat, is 't misschien toch beter om plottype niet standaard in elke tabel op forresdat op te nemen (nochtans misschien handig mochten mensen de tabellen inladen zonder via `read_forresdat` te gaan)
Maar dus wel vanaf je `read_forresdat` gebruikt, ongeacht of  `load_plotinfo = TRUE` of `FALSE` is.
Maar `forest_reserve `kan dan misschien wel enkel via `load_plotinfo = TRUE.`?

**Comment by leymanan** [comment]
> Uiteraard is dat ook een optie, dan voegen we voor plottype naast "CP" en "CA" een extra optie toe, en kwestie is dan vooral: hoe wil je dat noemen? (Heel vroeger was dit de default en dan was dat NA, nl. niks opgegeven, maar als je het niet als default wil, kan je het best een andere naam geven, lijkt mij. Een beetje raar als een gebruiker plottype NA moet opgeven.)

is `all` een mogelijkheid?

**Comment by ElsLommelen** [comment]
> > Moest dit een probleem zijn (= te traag), dan zouden we best overwegen wat het meest optimaal zou zijn: in forresdat aan elke tabel `plottype` (en `forest_reserve`) toevoegen (= join niet nodig, maar data-opslag iets groter), of de join telkens uitvoeren (= minder data-opslag in forresdat, maar vertraging door join). Weet jij toevallig al uit ervaring in hoeverre die join vertraagt?
> 
> Is me niet opgevallen dat het trager gaat als ik `load_plotinfo = TRUE` selecteer. Omdat het toch wel over heel veel tabellen gaat, is 't misschien toch beter om plottype niet standaard in elke tabel op forresdat op te nemen (nochtans misschien handig mochten mensen de tabellen inladen zonder via `read_forresdat` te gaan) Maar dus wel vanaf je `read_forresdat` gebruikt, ongeacht of `load_plotinfo = TRUE` of `FALSE` is. Maar `forest_reserve `kan dan misschien wel enkel via `load_plotinfo = TRUE.`?

Ok, dan kunnen we voor de join gaan.
Als ik toch moet joinen, is het een kleintje om `forest_reserve` mee te nemen, dus dat is vooral een 'inhoudelijke' keuze: wil je stimuleren om `load_plotinfo = TRUE` te gebruiken als er extra gegevens nodig zijn, dan voegen we het niet toe; wil je dat iedereen altijd de reservaatnaam in z'n dataset heeft, dan voegen we het wel doe.

Anderzijds haal je hier wel nog een goed punt aan: wat als mensen de tabellen uit forresdat halen zonder gebruik te maken van `read_forresdat()`?  Moest je om die reden (of performantie) graag plottype opslaan in elke tabel, dan lijkt me dat niet echt een probleem. Als we het bv. als factor met 2 mogelijke waarden opslaan (of zelfs als 2 karakters), dan vraagt dat niet veel extra ruimte in tabellen die toch al tientallen variabelen bevatten, lijkt mij.  Een vrij tekstveld met een ruimte tot 255 karakters is uiteraard een ander verhaal.  Dus `forest_reserve` overal als tekst toevoegen zou al wel een stuk minder ideaal zijn.  (En het toevoegen van een extra veld in alle records van een bestaande Git-repo gaat er uiteraard ook voor zorgen dat 'alles' aangepast wordt, maar vermits we toch met het idee lopen om naar csv over te schakelen e.d., lijkt het me sowieso beter om vanaf nul te vertrekken en forresdat volledig leeg te maken en opnieuw te vullen nadat alles op punt staat.)

Een andere optie zou kunnen zijn: gegevens voor CP en CA in forresdat in aparte tabellen opslaan.  Maar ik heb er eerlijk gezegd geen idee van hoeveel gemak of rompslomp dat voor u oplevert.  Het vermijdt wel dat onwetende gebruikers alles samen gaan gebruiken, maar anderzijds: langere tabelnamen, gebruikers moeten weten wat CP en CA zijn (terwijl ze nu via `read_forresdat()` het juiste of meest gebruikte krijgen), beetje meer gedoe als je alles wil samenvoegen,...  Enfin, aan u om de overweging te maken, en dit moet zeker nu niet raprap.  ;-)

**Comment by ElsLommelen** [comment]
> > Uiteraard is dat ook een optie, dan voegen we voor plottype naast "CP" en "CA" een extra optie toe, en kwestie is dan vooral: hoe wil je dat noemen? (Heel vroeger was dit de default en dan was dat NA, nl. niks opgegeven, maar als je het niet als default wil, kan je het best een andere naam geven, lijkt mij. Een beetje raar als een gebruiker plottype NA moet opgeven.)
> 
> is `all` een mogelijkheid?

Jazeker.  Ok, dan neem ik `all`.

**Comment by leymanan** [comment]
Bedankt!

**Comment by ElsLommelen** [comment]
Ok, opgelost door:

- kolom plottype op te nemen in de output van alle functies die tabellen voor forresdat genereren
- in `read_forresdat()` de optie `plottype = "all"` toe te voegen en de functie wat te herschrijven, uitgaande van het idee dat alle tabellen kolom plottype hebben (maar de functie zou niet vreemd mogen reageren als dit niet het geval is, enkel een warning geven dat de selectie niet uitgevoerd is als dit van toepassing is)

Ik heb niks aangepast in forresdat, dus in de praktijk ga je nog niet kunnen testen wat `read_forresdat()` zal geven als in forresdat overal een kolom plottype toegevoegd is.  (Voor mij ok om dit issue open te laten tot je dit hebt kunnen testen, dan vergeten we het in elk geval niet te testen.)

**Comment by ElsLommelen** [comment]
Nog een klein vraagje in verband hiermee dat ik nog niet gevraagd heb: voeg ik ingeval van een functie/tabel voor enkel de core area `plottype` ook toe, of niet?  Ik denk dan bv. aan de functies `calculate_regeneration_core_area_species()` en `calculate_regeneration_core_area_height_species()`.

**Comment by leymanan** [comment]
> Nog een klein vraagje in verband hiermee dat ik nog niet gevraagd heb: voeg ik ingeval van een functie/tabel voor enkel de core area `plottype` ook toe, of niet? Ik denk dan bv. aan de functies `calculate_regeneration_core_area_species()` en `calculate_regeneration_core_area_height_species()`.

nee, dat hoeft niet, staat in naam van de gegenereerde tabel

**Comment by ElsLommelen** [comment]
voila, bij deze in orde, behalve dat die aanpassingen nog niet in forresdat zitten.
