### ISSUE TITLE
create_statistics: n_obs niet steeds correct

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#115]
als ik `create_statistics `run, is `n_obs `in het resultaat voor de eerste variabele steeds 2 keer zo groot als  `n_obs `van de andere variabelen.
Hierna een voorbeeldje met maar drie variabelen.
Is onafhankelijk van welke variabele.

```
resultaat_test <- create_statistics(
  dataset = dataset2_0,
  level = c("period", "forest_reserve", "speciesTxt"),
  variables = c("basal_area_alive_m2_ha", "number_of_trees_ha", "vol_alive_m3_ha"),
  include_year_range = FALSE,
  na_rm = FALSE,
    interval_information = suppressMessages(read_csv2(system.file("extdata/class_data.csv",
    package = "forrescalc")))
  )
 %>% 
  filter(forest_reserve == "Wijnendalebos")
```

```
> table(resultaat_test$variable, resultaat_test$n_obs)
                        
                         120 240
  basal_area_alive_m2_ha   0 107
  number_of_trees_ha     107   0
  vol_alive_m3_ha        107   0
```
Ter info
```
> names(dataset2_0)
 [1] "plot_id"                 "period"                  "species"                
 [4] "number_of_trees_ha"      "stem_number_ha"          "basal_area_alive_m2_ha" 
 [7] "basal_area_dead_m2_ha"   "vol_alive_m3_ha"         "vol_dead_standing_m3_ha"
[10] "vol_bole_alive_m3_ha"    "vol_bole_dead_m3_ha"     "vol_log_m3_ha"          
[13] "vol_deadw_m3_ha"         "vol_log_m3_ha_min40cm"   "speciesTxt"             
[16] "forest_reserve"  
```

**Comment by ElsLommelen** [comment]
Vreemd.  Vermits ik je dataset niet heb, heb ik dit geprobeerd met een voorbeeld uit de help van het package, en dit aangepast om 'gelijkaardige' variabelen te gebruiken, maar ik kan dit probleem niet reproduceren: ik krijg wel voor elke variabele een gelijk aantal observaties.

Zou je wat meer info kunnen meegeven?  Bv. welke versie (branch + evt. hash van commit) van het package heb je geïnstalleerd?  En wat meer info over de dataset in kwestie zou ook handig zijn, zoals de output van `head(dataset2_0)` en `summary(dataset2_0)`, of liever nog: zorgen dat ik het hier gemakkelijk kan reproduceren (bv. je code toepassen op een dataset uit forresdat zodat ik de code kan overnemen, of illusteren met een publieke testdataset uit R zoals `iris`).

**Comment by leymanan** [comment]
Is inderdaad heel raar, wanneer ik vertrek van bv. `dendro_by_plot_species` kan ik het ook niet reproduceren.
Ik vertrek echter van een dataset waar ik mbv `add_zeros` de nulwaardes heb toegevoegd voor elke , en daar blijft probleem zich stellen.

SORRY, OPGELOST! Had bij koppelen van naam bosreservaat een foutje gemaakt (periode vergeten meenemen), waardoor er een verdubbeling van data was.

Maar blijft toch raar dat er enkel bij de eerste van de 3 variabelen een verdubbeling van n_obs is, terwijl in de dataset alle variabelen 2x zoveel voorkomen.
