### ISSUE TITLE
0 vs NA bij dendro_by_plot(_species_diam)

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#117]
momenteel ontstaan er NA's wanneer er bv. wel dood hout is van een bepaalde soort, maar geen levend (en vice versa)
Dat zouden nullen moeten worden (toch als er een `survey_trees ` geweest is van de staande bomen en `survey_deadwood ` van het liggend dood hout).

Met uitz. van de variabele `stems_per_tree`: deze variabele moet NA blijven wanneer er geen levende, staande bomen opgemeten werden.

**Comment by ElsLommelen** [comment]
Opgelost in commit cf72ac9dd5a81d4a36969ca83eb3184f533026f6, neem ik aan?
Voor die `stems_per_tree`: zie nog even mijn voorstel [hier](https://github.com/inbo/forrescalc/pull/103#:~:text=Nu%20ik%20andere,argumenten%20te%20gebruiken.) in PR #103.
