### ISSUE TITLE
create_unique_id() loopt vast bij sommige kernvlaktes

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#119]
ik dacht dat het misschien te maken had met grote waardes voor `old_id `en `tree_measure_id`, maar ik heb die eens weggefilterd maar dat blijkt toch niet zo te zijn

Bij CP's loopt dat heel vlot, en ook bij de meeste kernvlaktes (heb ik getest door subsets te nemen)
Enkel bij `plot_id `43000 (KV) loopt het vast.

Blijkbaar komt dat doordat er één boom is met een `old_id`, die in de voorgaande periode niet terug te vinden is (geen `tree_measure_id`): plot_id = 43000, tree_meaure_id = 9, old_id = 1000
Zou met datacontrole moeten opgevangen worden, ik weet het.

Maar wat ik niet snap is dat ik plot 11000 wel al afzonderlijk heb kunnen runnen, zonder problemen, maar als ik  er een andere KV (bv. 21000) aan toevoegde, lukte het niet meer.
En nu lukt het helemaal niet meer als ik een subset neem met enkel plot_id 11000.
Ik heb daar ook eens de trees weggehaald die wél een old_id hebben, maar geen link naar vorige periode, maar dat lukte ook niet.
Ofwel is de code gewoon heel traag ...

Enig idee?
In bijlage een RData-file.

Ik gebruik volgende code:
`tree_id <- create_unique_tree_id(data_dendro = data_dendro_calc_id)`

[data_dendro_calc.zip](https://github.com/inbo/forrescalc/files/11576591/data_dendro_calc.zip)

**Comment by leymanan** [comment]
ter aanvulling: ik heb die functie al succesvol gebruikt (oa voor KV Kersselaerspleyn, 4 decades), maar dateert wel van 8/4/2022 ...

**Comment by ElsLommelen** [comment]
Het loopt vast omdat voor 1323 bomen uit 11000 (en die ene uit 43000) `old_id` niet in de voorgaande periode terug te vinden is.  Bijvoorbeeld: boom uit periode 2 met tree_measure_id 184 en old_id 1048: in periode 1 bestaat er geen boom met tree_measure_id 1048 (wel in periode 3, maar dat gaat hij niet koppelen omdat ik dacht dat altijd met de vorige periode gekoppeld moest worden).

Probleem is dat het script blijft zoeken tot alle NA's voor tree_id weggewerkt zijn, en met die 'onoplosbare gevallen' loopt het dus na een hele tijd vast door geheugenproblemen (= oneindige lus).  Hoe los ik dit op?  Sowieso zal ik zorgen dat hij stopt met zoeken nadat hij alle periodes doorlopen heeft.  Moet ik daarnaast ook een warning geven als er nog NA's aanwezig zijn voor tree_id, of is dat niet nodig?

**Comment by leymanan** [comment]
Bedankt, dus inderdaad wat ik dacht dat de oorzaak was.

Maar is raar, want bij Kersselaerspleyn heb ik dat vroeger wel nog kunnen runnen, met dezelfde dataset?

Zou inderdaad handig zijn dat hij stopt met zoeken, en ja, een warning zou handig zijn.
Ev. met vermelding van `forest_reserve `en `period`? (indien mogelijk; als moeilijk is dat natuurlijk ook snel opgezocht met een join)

**Comment by ElsLommelen** [comment]
Gemakkelijkst om te weten welke hij niet heeft kunnen invullen, is om gewoon het resultaat te filteren op `is.na(tree_id)`.  ;-) 

Hoe wil je dat ik de warning formuleer?  `Some records from forest_reserve xxx and period y did not get a tree_id (NA) because the old_id was unknown in the previous period.`  En wat doe ik als er meerdere bosreservaten en/of periodes zijn?  Of heb je een betere suggestie voor de formulering?

**Comment by leymanan** [comment]
geode formulering, bedankt!
En als er meerder reservaten zijn, dan 
`Some records from multiple forest_reserves did not get a tree_id (NA) because the old_id was unknown in the previous period`

**Comment by ElsLommelen** [comment]
Euh, ik zie net dat forest_reserve niet in de dataset staat, dit vervangen door plot_id, neem ik aan?

**Comment by leymanan** [comment]
> Euh, ik zie net dat forest_reserve niet in de dataset staat, dit vervangen door plot_id, neem ik aan?

ik heb je een veel beperktere dataset doorgestuurd, normaal staat forest_reserve wel in de datasat.
Maar misschien toch niet slecht om plot_id te nemen, voor 't zekerste, dat zit altijd in de datasets

**Comment by leymanan** [comment]
voor mij is een eenvoudige warning dat er NA's zijn voldoende, gebruiker kan inderdaad achteraf snel zien over welke bomen het gaat

Bedankt!

**Comment by ElsLommelen** [comment]
Ok, dat vereenvoudigt de code enorm (bijna 10 lijnen) :-)

**Comment by ElsLommelen** [comment]
Dit lijkt me opgelost, @leymanan ?  Ik heb bovenstaande code en dataset opnieuw getest, en dit gaf:
```
Warning message:
In create_unique_tree_id(data_dendro = data_dendro_calc_id) :
  Some records did not get a tree_id (NA) because the old_id was unknown in the previous period
```
En er waren inderdaad een aantal records met `tree_id` NA.
