### ISSUE TITLE
calculate_vegetation_plot

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#120]
Mbt functie `calculate_vegetation_plot()`

in de code staat een left_join, waardoor de plots zonder enige soort niet meegenomen worden
Dat zou best een full_join (of right_join) worden

```
by_plot <- data_herblayer %>%
    ......
    ) %>%
    ungroup() %>%
    **left_join(**
      data_vegetation %>%
```

Bv. plot 1176 periode 1

**Comment by ElsLommelen** [comment]
Ik neem aan dat dit probleem opgelost is door commit cf9068492e7ef9755addc9686ee1e3b8c35b540e, nl. door bij `load_data_herblayer()` alle gegevens in te laden?

**Comment by leymanan** [comment]
> Ik neem aan dat dit probleem opgelost is door commit [cf90684](https://github.com/inbo/forrescalc/commit/cf9068492e7ef9755addc9686ee1e3b8c35b540e), nl. door bij `load_data_herblayer()` alle gegevens in te laden?

ik denk het wel ;-)
