### ISSUE TITLE
compare_periods_per_plot()

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#121]
Het voorbeeld in de documentatie van `compare_periods_per_plot()` geeft wat vreemde resultaten (een extra kolom `p3` en tamelijk wat NA-waarden) omdat deze functie gemaakt is toen er nog maar 2 periodes beschikbaar waren, en er intussen ook al metingen van de 3de periode zijn (maar niet voor alle records).

Vraagje, @leymanan : hoe pas ik die functie best aan, oftewel: wat moet de uitkomst zijn?  Geef ik alle mogelijke verschillen tussen de 3 periodes (dus diff_1_2, diff_1_3 en diff_2_3), of enkel tussen de opeenvolgende periodes (dus diff_1_2 en diff_2_3)?  Geef ik het in lang formaat, zodat je per `plot_id` 2 of 3 rijen hebt met telkens `year_diff`, `n_year` en een diff voor alle opgegeven variabelen?  (Dus een beetje zoals het nu is, maar dan kolom `p3` wegdoen en de 2 rijen samenvoegen en NA's weglaten.

**Comment by leymanan** [comment]
- enkel tussen de opeenvolgende periodes (dus diff_1_2 en diff_2_3)
- lang formaat, zodat je per plot_id 2 of 3 rijen hebt met telkens year_diff, n_year en een diff voor alle opgegeven variabelen
Bedankt!

! er is ook één reservaat met 4 periodes ... (Kersselaerspleyn), kan die optie ook toegevoegd worden?

**Comment by ElsLommelen** [comment]
> Ik dacht even aan KV Kersselaerspleyn: daar zijn 4 periodes opgemeten, maar dat is eigenlijk maar één plot (plot_id 11000), dus daar hoeft geen rekening mee gehouden te worden. Drie periodes zijn OK.

Ik denk dat het sowieso beter is dat ik de code meteen aanpas voor n periodes.  Er gaan soms nog gegevens doorgegeven worden met maar 2 periodes (want niet alle plots hebben al een 3de periode), en over een aantal jaren gaat er ook voor andere plots een 4de periode bijkomen...  En eigenlijk is het een generieke functie die mits de nodige voorwaarden in de dataset (kolommen plot_id, year,... toevoegen) ook voor andere data gebruikt zou kunnen worden, dus de limiet op exact 3 periodes zetten zou de bruikbaarheid heelwat verlagen.
