### ISSUE TITLE
plotinfo laden met `read_forresdat()`

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#122]
Wat ik nu ook merkte is dat `read_forresdat() ` niet werkt om plotinfo in te laden ... 
Ik weet dat dat niet doel was, omdat je die kan koppelen, maar soms toch handig om overzocht te krijgen van alle plots met info over waar wat opgemeten.
Bevat wél het veld `plottype`
`> plotinfo <- read_forresdat("plotinfo", repo_path = path_to_git_forresdat)
Error in `filter()`:
ℹ In argument: `.data$plottype == plottype`.
Caused by error in `.data$plottype`:
! Column `plottype` not found in `.data`.
Run `rlang::last_trace()` to see where the error occurred`

_Originally posted by @leymanan in https://github.com/inbo/forrescalc/pull/103#discussion_r1374129646_

**Comment by ElsLommelen** [comment]
Ik heb dit eventjes getest, en blijkbaar kan het wel als je argument `join_plotinfo = FALSE` toevoegt.  Zelf had ik eigenlijk direct de reflex om het zo te testen, want het leek me onlogisch om die tabel binnen te halen en met zichzelf te koppelen...  Ik heb dit toegevoegd in de documentatie, ik neem aan dat dit voldoende is als oplossing?

**Comment by leymanan** [comment]
nog kleine toevoeging aan documentatie gedaan, hopelijk geen probleem?

**Comment by ElsLommelen** [comment]
Nee hoor, uiteraard niet.
(Tip voor de toekomst: als je documentatie aanpast, best even het package opnieuw bouwen en ook de aanpassing in de `Rd`-file aan de commit toevoegen, kwestie dat alles samen staat in 1 commit.  Uiteraard lukt dat niet als je dit online op Github zou aangepast hebben.  In dit geval heb ik het al even in orde gemaakt in een aparte commit, nadat ik bij het proberen pushen van een andere commit ontdekte dat er iets aangepast was in m'n branch.  ;-)  )

**Comment by leymanan** [comment]
sorry mocht ik iets fouts gedaan hebben!

**Comment by ElsLommelen** [comment]
Nee hoor, zeker niet, ik gaf enkel een tip.  Nu ik zelf ondervonden heb hoe handig het is om een hele commit weg te halen, zie ik nog beter in hoe belangrijk het is om alle aanpassingen in 1 commit te hebben.  En bij aanpassingen in de documentatie hoort ook een update van de `.Rd`-file.  Maar uit ondervinding weet ik ook dat het opnieuw builden om die `.Rd` aan te passen, niet kan als je de tekst online op Github aanpast (wat ik zelf ook handig vind om een typo of andere kleine aanpassing te suggereren in andermans code).  En zelf heb ik er eerlijk gezegd ook wel wat tijd over gedaan tot ik er consequent aan dacht om die documentatie te bouwen en de update in de Rd mee te nemen.  Dus alle begrip dat je dat soort details vergeet.  ;-)
