### ISSUE TITLE
opkuis branches

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#123]
De [branches](https://github.com/inbo/forrescalc/branches) en de geschiedenis zijn intussen een zootje geworden waar ik nog moeilijk aan uit kan, en ik zou hier graag eens opruim in houden.  Kijk je even mee, @leymanan ?

- [vignettes_AL](https://github.com/inbo/forrescalc/tree/vignettes_AL): dit is een heel oude branch waarin jij [2 commits](https://github.com/inbo/forrescalc/commits/vignettes_AL) gemaakt hebt: een aanzet tot een vignet over missing plots en je orcid aangevuld.  Die orcid zit intussen ook in de master en andere branches, maar wil je dat vignet nog behouden of iets mee doen?
- [test_proxy](https://github.com/inbo/forrescalc/commits/test_proxy) is een testje van u met 2 commits, ik neem aan dat die weg mag?
- workflow_AL: ook oud en gemerged in de master, dus ik neem aan dat die weg mag?
- update_query_database heb ik ooit aangemaakt, is gemerged in de master en mag wat mij betreft weg

Volgende branches zijn recenter dan de master, en die ga ik misschien nog even laten staan als referenties (omdat ik niet zeker ben dat we altijd wel de beste versies gehouden hebben bij de merges), maar idee is om niet meer van hieruit te werken
- issue90 is gemerged in bug-fixes, dus issue90 mag wat mij betreft weg
- revert-82-reg_AL: geen idee wat hier de bedoeling was, maar ik neem aan dat het weg mag?
- reg_AL is gemerged in bug-fixes op 30/11/22, dus ik neem aan dat die weg mag?
- update-Main-script: een suggestie die ik gegeven heb in reg_AL, dus die mag ook weg
- statistics-and-other-issues: een branch waar ik ooit aan bezig was, maar om een of andere reden is die als merged aangeduid nadat je deze in reg_AL gemerged hebt om reg_AL up-to-date te maken met de aanpassingen die ik hierin gemaakt heb.  Ook de bijhorende pull request is toen verdwenen.  (Ligt zeker niet aan u, ik heb al enkele keren gelijkaardige situaties meegemaakt, waarbij GitHub na wat mergen van branches naar elkaar ineens beslist dat een bepaalde PR niet meer nodig is.)  Omdat ik die actie van github niet helemaal vertrouw, houd ik dit label zeker nog even bij (moest er iets mis zijn, dan kan ik terug zien hoe de code daar was), maar idee is dus ook om die branch te negeren en weg te gooien zodra de issues opgelost zijn.

Dan blijven over:
- bug-fixes: hierin zitten de meeste aanpassingen, dus ik stel voor dat ik hiermee verder ga
- deadwood_AL: hierin heb je enkele aanpassingen gemaakt in deadwood, en ook een aantal to do's als opmerking toegevoegd in het script.  Ik heb hier nog een kleine opmerking, ik stel voor dat je die even bekijkt en dat we daarna die branch mergen in bug-fixes, gewoon met de commentaar in de code, en dan los ik het daar allemaal op.  (Vooral om het risico op conflicten te beperken, want daar is al een en ander opgelost i.v.m. `add_zeros()`.)
- testdatabase: een zijbranch van de toenmalige statistics-and-other-issues waarin ik bezig was om een testdatabank te maken, die recupereer ik ook nog wel in bug-fixes als ik aan het desbetreffende issue verder werk
- gh-pages: dit is om de website te maken, dus die moet blijven
- master: die blijft uiteraard ook, die ga ik trouwens uiteindelijk hernoemen naar main

Kan jij even voor je branches aangeven wat ermee moet gebeuren, en reageren als je niet akkoord bent voor de andere voorstellen?  (En best eerst even de PR van deadwood_AL bekijken, dan kan ik verder. ;-) )

**Comment by leymanan** [comment]
> * [vignettes_AL](https://github.com/inbo/forrescalc/tree/vignettes_AL): dit is een heel oude branch waarin jij [2 commits](https://github.com/inbo/forrescalc/commits/vignettes_AL) gemaakt hebt: een aanzet tot een vignet over missing plots en je orcid aangevuld.  Die orcid zit intussen ook in de master en andere branches, maar wil je dat vignet nog behouden of iets mee doen?

doe maar weg, heb een eigen copietje gepakt mocht ik er ooit mee verder willen

> * [test_proxy](https://github.com/inbo/forrescalc/commits/test_proxy) is een testje van u met 2 commits, ik neem aan dat die weg mag?
jawel

> * workflow_AL: ook oud en gemerged in de master, dus ik neem aan dat die weg mag?
inderdaad

> * update_query_database heb ik ooit aangemaakt, is gemerged in de master en mag wat mij betreft weg
OK

> Volgende branches zijn recenter dan de master, en die ga ik misschien nog even laten staan als referenties (omdat ik niet zeker ben dat we altijd wel de beste versies gehouden hebben bij de merges), maar idee is om niet meer van hieruit te werken
> 
> * issue90 is gemerged in bug-fixes, dus issue90 mag wat mij betreft weg
ok

> * revert-82-reg_AL: geen idee wat hier de bedoeling was, maar ik neem aan dat het weg mag?
mag weg, denk dat dat ontstaan is omdat ik ooit eens een branch te vroeg gemerged had met iets van u

> * reg_AL is gemerged in bug-fixes op 30/11/22, dus ik neem aan dat die weg mag?
die zou ik nog even laten staan,  omdat daar toch nog aanpassingen op voorgesteld zijn nadat bug-fixes ervan afgetakt is, niet?

> * update-Main-script: een suggestie die ik gegeven heb in reg_AL, dus die mag ook weg
ok

> * statistics-and-other-issues: een branch waar ik ooit aan bezig was, maar om een of andere reden is die als merged aangeduid nadat je deze in reg_AL gemerged hebt om reg_AL up-to-date te maken met de aanpassingen die ik hierin gemaakt heb.  Ook de bijhorende pull request is toen verdwenen.  (Ligt zeker niet aan u, ik heb al enkele keren gelijkaardige situaties meegemaakt, waarbij GitHub na wat mergen van branches naar elkaar ineens beslist dat een bepaalde PR niet meer nodig is.)  Omdat ik die actie van github niet helemaal vertrouw, houd ik dit label zeker nog even bij (moest er iets mis zijn, dan kan ik terug zien hoe de code daar was), maar idee is dus ook om die branch te negeren en weg te gooien zodra de issues opgelost zijn.
Inderdaad beste, want kan zijn dat ik die merge toen weer ongedaan gemaakt heb of zo, ben echt niet meer zeker.
Ik weet alleen dat ik ooi eens te overhaast was (of iets fout begrepen had)
Kan toen geweest zijn ....
> 
> Dan blijven over:
> 
> * bug-fixes: hierin zitten de meeste aanpassingen, dus ik stel voor dat ik hiermee verder ga
Lijkt me inderdaad goed plan

> * deadwood_AL: hierin heb je enkele aanpassingen gemaakt in deadwood, en ook een aantal to do's als opmerking toegevoegd in het script.  Ik heb hier nog een kleine opmerking, ik stel voor dat je die even bekijkt en dat we daarna die branch mergen in bug-fixes, gewoon met de commentaar in de code, en dan los ik het daar allemaal op.  (Vooral om het risico op conflicten te beperken, want daar is al een en ander opgelost i.v.m. `add_zeros()`.)
ok

> * testdatabase: een zijbranch van de toenmalige statistics-and-other-issues waarin ik bezig was om een testdatabank te maken, die recupereer ik ook nog wel in bug-fixes als ik aan het desbetreffende issue verder werk
ok
> * gh-pages: dit is om de website te maken, dus die moet blijven
> * master: die blijft uiteraard ook, die ga ik trouwens uiteindelijk hernoemen naar main

**Comment by ElsLommelen** [comment]
> > * reg_AL is gemerged in bug-fixes op 30/11/22, dus ik neem aan dat die weg mag?
> 
> die zou ik nog even laten staan, omdat daar toch nog aanpassingen op voorgesteld zijn nadat bug-fixes ervan afgetakt is, niet?

Ik heb gecheckt, en bug-fixes is blijkbaar pas gestart na de voorgestelde aanpassingen in reg_AL.  De laatste commit in reg_AL is [4fab058](https://github.com/inbo/forrescalc/pull/100/commits/4fab0589dd9742e26a49bcbbdd0b6efe21ae973a) (remove mid_cover from load_data_vegetation()) en die staat ook in [bug_fixes](https://github.com/inbo/forrescalc/commits/bug-fixes).  Maar zoals aangegeven: ik houd reg_AL voor de zekerheid nog even bij.  Ik ben trouwens ook even aan 't nagaan of alle commentaren uit die PR wel ingewerkt zijn.

> > * [vignettes_AL](https://github.com/inbo/forrescalc/tree/vignettes_AL): dit is een heel oude branch waarin jij [2 commits](https://github.com/inbo/forrescalc/commits/vignettes_AL) gemaakt hebt: een aanzet tot een vignet over missing plots en je orcid aangevuld.  Die orcid zit intussen ook in de master en andere branches, maar wil je dat vignet nog behouden of iets mee doen?
> 
> doe maar weg, heb een eigen copietje gepakt mocht ik er ooit mee verder willen

Je zegt het maar, hoor.  Als je er evt. later nog mee verder wil, dan kan ik die wel laten staan en na afwerken van het package rebase toepassen om die ene commit met je vignet als zijbranch aan de finale versie vast te zetten.  Doordat het een los document is waar in de tussenliggende geschiedenis niks aan gedaan is, kan dat proper opgevist worden.  Het is net het idee van git dat dit allemaal kan, zonder met externe kopieën te moeten werken (en die kwijt te geraken of te vergeten dat je die nog hebt).  Het waren vooral die andere branches die in mekaar gemerged waren die het ingewikkeld maakten, en het feit dat het intussen veel branches waren; een branch met duidelijke naam die afgesplitst is voor een specifiek item dat nog niet afgewerkt is, vind ik minder problematisch wat overzichtelijkheid betreft.

**Comment by leymanan** [comment]
> > > * [vignettes_AL](https://github.com/inbo/forrescalc/tree/vignettes_AL): dit is een heel oude branch waarin jij [2 commits](https://github.com/inbo/forrescalc/commits/vignettes_AL) gemaakt hebt: een aanzet tot een vignet over missing plots en je orcid aangevuld.  Die orcid zit intussen ook in de master en andere branches, maar wil je dat vignet nog behouden of iets mee doen?
> > 
> > 
> > doe maar weg, heb een eigen copietje gepakt mocht ik er ooit mee verder willen
> 
> Je zegt het maar, hoor. Als je er evt. later nog mee verder wil, dan kan ik die wel laten staan en na afwerken van het package rebase toepassen om die ene commit met je vignet als zijbranch aan de finale versie vast te zetten. Doordat het een los document is waar in de tussenliggende geschiedenis niks aan gedaan is, kan dat proper opgevist worden. Het is net het idee van git dat dit allemaal kan, zonder met externe kopieën te moeten werken (en die kwijt te geraken of te vergeten dat je die nog hebt). Het waren vooral die andere branches die in mekaar gemerged waren die het ingewikkeld maakten, en het feit dat het intussen veel branches waren; een branch met duidelijke naam die afgesplitst is voor een specifiek item dat nog niet afgewerkt is, vind ik minder problematisch wat overzichtelijkheid betreft.

ja, hou die dan maar bij.
Wou het niet complexer maken dan 't al is, maar als dat simpel opgevist kan worden ... ;-)

**Comment by ElsLommelen** [comment]
Ok, de oudste branches zijn intussen verwijderd, de andere behoud ik voor de zekerheid nog even.

Takenlijstje:

- [x] `deadwood` mergen in `bug-fixes`
- [x] `checklist-test` afwerken en mergen in `testdatabase`
- [x] `testdatabase` mergen in `master`
- [x] alle hierboven vernoemde branches verwijderen (alles behalve `vignettes_AL`)
- [x] na mergen PR `master` hernoemen naar `main` (en testen of machinerie in orde is)
- [x] forresdat leegmaken en terug vullen

(**Edit**: rebasen van `vignettes_al` verwijderd uit takenlijstje, omdat branch per ongeluk verwijderd is.)
