### ISSUE TITLE
correctie volumeberekening mbv tarief Quataert (eik en beuk)

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#124]
Els, er is een foutje geslopen in het gebruik van het tarief van Quataert et al. voor eik en beuk.
De formules zijn berekend op een omtrek op 1.5 m (C150) en niet op 1.3 m (C130).
Momenteel wordt als input overal `perimeter `gebruikt, zijnde de omtrek op 1.3m (C130).

Dat heeft geen grote impact, maar toch ... 

Daarom heb ik nu in de tabel `tblTarieven_2ing `uit `BR_ExterneData.accdb` het veld `Formule_type ` (`formula`) gewijzigd in "3" (ipv "1").
Zie aangepaste databank op [gdrive ](https://drive.google.com/file/d/100aX-inMIovb2y7Z0XTxA8zc6ZCiQFc5/view?usp=drive_link)(G:\Gedeelde drives\Team_Boseco\00_projecten\PRJ_BR_VisualisatieResultaten\Werkruimte).

In script `tarifering.R` wordt obv de tabellen uit deze databank `tariffs2entries.csv` aangemaakt, dat dan in script `calc_variables_stem_level.R` aangeroepen wordt om volumes te berekenen.

In dat laatste script zou er dus een extra code voorzien moeten worden voor boomsoorten volgens `formula == 3` :
- berekening van omtrek op 1.5m (? `perimeter_150`) 
- gebruik van `perimeter_150 ` ipv `perimeter `als `formula == 3`

Voor de berekening van de omtrek op 1.5m hoogte, moet gebruik gemaakt worden van de tabel `tblCoefOmzetOmtrek` (ook opgenomen in `BR_ExtereData.accdb`).
Deze is door Dagnelie aangemaakt om omtrek op 1.5m hoogte (C150) om te zetten naar C130: C130 = A + B. C150
Maar omgekeerd kan dus ook: C150 = (C130 - A)/B

Op termijn moet ik eens overleggen met BMK (? Pieter Verschelde) of er enige mogelijkheid is om die tarieven rechtstreeks aan te maken obv C150. Volgens Beatrijs (VanderAa) zijn de gegevens daarvoor beschikbaar).

Sorry dat ik daar nu mee afkom, maar veel mensen hebben daar blijkbaar over gekeken ...

**Comment by ElsLommelen** [comment]
Nog enkele vraagjes hierover:
- ik vind `tblCoefOmzetOmtrek` niet in die databank (versie van 8 nov 2023, dus van de dag van je post), ik neem aan dat daar A en B in staan voor de verschillende boomsoorten om `perimeter_150` te berekenen?
- ik neem aan dat ik dezelfde berekening gebruik als `formula == 1`, maar dan met `perimeter_150` (oftewel in de eerste stap de perimeter anders berekenen en dan verderop dezelfde berekening als `formula == 1` gebruiken)?

**Comment by leymanan** [comment]
> * ik vind `tblCoefOmzetOmtrek` niet in die databank (versie van 8 nov 2023, dus van de dag van je post), ik neem aan dat daar A en B in staan voor de verschillende boomsoorten om `perimeter_150` te berekenen?

Oeps, ja blijkbaar stond daar nog steeds de oude, sorry!
Nu de correcte, onder : G:\Gedeelde drives\Team_Boseco\00_projecten\PRJ_BR_VisualisatieResultaten\Werkruimte

**Comment by leymanan** [comment]
> * ik neem aan dat daar A en B in staan voor de verschillende boomsoorten om `perimeter_150` te berekenen?

inderdaad

**Comment by leymanan** [comment]
> * ik neem aan dat ik dezelfde berekening gebruik als `formula == 1`, maar dan met `perimeter_150` (oftewel in de eerste stap de perimeter anders berekenen en dan verderop dezelfde berekening als `formula == 1` gebruiken)?

Inderdaad.

**Comment by ElsLommelen** [comment]
Ok, zal ik die omzettingstabel ook in het package steken?  (Dat vermijdt dat we die voor elke berekening apart moeten oproepen, en dat anderen die tabel ook moeten hebben als ze die berekeningen willen doen.)

**Comment by ElsLommelen** [comment]
Voila, aangepast, en dat geeft inderdaad iets hogere resultaten voor de boomsoorten in kwestie, dus ik veronderstel dat het in orde is?

**Comment by leymanan** [comment]
> Voila, aangepast, en dat geeft inderdaad iets hogere resultaten voor de boomsoorten in kwestie, dus ik veronderstel dat het in orde is?

code bekeken en lijkt me in orde
Maar eigenlijk zou volume dan net lager moeten worden, want we gebruiken een C150 die ietsje lager is dan C130.

**Comment by ElsLommelen** [comment]
> > Voila, aangepast, en dat geeft inderdaad iets hogere resultaten voor de boomsoorten in kwestie, dus ik veronderstel dat het in orde is?
> 
> code bekeken en lijkt me in orde Maar eigenlijk zou volume dan net lager moeten worden, want we gebruiken een C150 die ietsje lager is dan C130.

Oeps, sorry, blijkbaar me vergist, het is inderdaad iets lager.  Voor de allereerste boom van de dataset krijg ik voor vol_bole_m3 9.192888 i.p.v. 9.364741

**Comment by ElsLommelen** [comment]
mag dicht, neem ik aan?
