### ISSUE TITLE
extra functie "calculate_regeneration_plot_species()"

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#125]
zie ook bedenking issue #102

Ik merkte op dat we geen `regeneration_by_plot_species `berekenen.
Zou via een functie ` calculate_regeneration_plot_species()` kunnen

Zal misschien ook ooit een reden voor geweest zijn, mogelijks dat dat in de oude rapporten niet op die manier gerapporteerd werd.
Maar ljjkt me toch opportuun. 
Voor core area's hebben we het wel.
Sorry!

**Comment by ElsLommelen** [comment]
Voila, toegevoegd.  Deze functie is gelijkaardig aan `calculate_regeneration_plot()` (maar output per soort en zonder aantal soorten) en `calculate_regeneration_core_area_species()` (maar gegevens per subplot, niet voor de volledige kernvlakte)
