### ISSUE TITLE
output calculate_vegetation()

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#129]
In `calculate_vegetation()` wordt [hier](https://github.com/inbo/forrescalc/blob/a518ee686d6ddbbe762ae5afb3a31a3fb162cc9a/R/calculate_vegetation.R#L34) `data_herblayer` van CA berekend, maar dit wordt niet teruggegeven door de functie.  Is het de bedoeling dat dit wel gebeurt?  (Anders is het overbodig om de berekening te maken.)  Moet het resultaat `herblayer_by_plot` genoemd worden, zoals er momenteel al een tabel is in forresdat, of moet er een expliciete verwijzing naar CA in de naam?  (Hier ben ik toevallig bij uitgekomen tijdens het toevoegen van plottype aan alle output die als tabel aan forresdat toegevoegd wordt.)

**Comment by leymanan** [comment]
> In `calculate_vegetation()` wordt [hier](https://github.com/inbo/forrescalc/blob/a518ee686d6ddbbe762ae5afb3a31a3fb162cc9a/R/calculate_vegetation.R#L34) `data_herblayer` van CA berekend, maar dit wordt niet teruggegeven door de functie. Is het de bedoeling dat dit wel gebeurt? (Anders is het overbodig om de berekening te maken.)

Dat moet inderdaad niet teruggegeven worden (makkelijk te filteren uit `herblayer_by_plot`), maar is wel nodig om `by_core_area_species` te berekenen (`vegetation_by_core_area_species = by_core_area_species`):

` by_core_area_species <- calculate_vegetation_core_area_species(data_herblayer_CA)`

**Comment by ElsLommelen** [comment]
Ah ja, oeps, toen ik dit issue postte, had ik blijkbaar niet gezien dat dit wel gebruikt werd.
