### ISSUE TITLE
calculate_regeneration_plot_species()

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#130]
Ik stel vast dat er een functie `calculate_regeneration_plot_species()` is die niet toegevoegd is aan `calculate_regeneration()` en die ook geen overeenkomstige tabel heeft in forresdat.  Is dit de bedoeling?  (Als we die functie ooit gemaakt hebben en ze bruikbaar en in orde is, mag ze uiteraard blijven bestaan, ook als ze niet in `calculate_regeneration()` staat.  Vraag is vooral: is het nodig om die aan `calculate_regeneration()` en forresdat toe te voegen, of was het een bewuste keuze om dat niet te doen of ze hier terug uit te halen?)

**Comment by leymanan** [comment]
> Ik stel vast dat er een functie `calculate_regeneration_plot_species()` is die niet toegevoegd is aan `calculate_regeneration()` en die ook geen overeenkomstige tabel heeft in forresdat. Is dit de bedoeling?

Eigenlijk niet nee, die functie mag toegevoegd worden aan `calculate_regeneration()` met als output naar forresdat `regeneration_by_plot_species = by_plot_species`
