### ISSUE TITLE
functie access_to_sqlite()

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#131]
Ik ben in de beginperiode van het package ooit eens begonnen aan een functie [`access_to_sqlite()`](https://github.com/inbo/forrescalc/blob/testdatabase/R/access_to_sqlite.R) die ik nooit afgewerkt heb en die ook nooit gebruikt is, veronderstel ik.  Ik vermoed dat het idee was om de gegevens uit fieldmap over te brengen naar een geïndexeerde SQLite-databank om de performantie van de berekeningen te verbeteren, maar dat ik dan toch maar begonnen ben met eerst de functies zelf uit te werken en dit is blijven liggen.  Mogelijk heb ik die functie dan behouden om het testdatabankje (issue #81) aan te maken, maar uiteindelijk heb ik hiervoor in branch testdatabase [een apart script](https://github.com/inbo/forrescalc/blob/testdatabase/data-raw/example_dataset.R) gemaakt.  Dus ik neem aan dat die functie `access_to_sqlite()` niet meer nodig is en dus verwijderd mag worden?

(Laat gerust weten als je hiervoor toch een nuttige toepassing ziet.)

**Comment by leymanan** [comment]
ik zie geen toepassing, heb eigenlijk geen echt idee wat die sqlite is ;-)

**Comment by ElsLommelen** [comment]
SQLite is een formaat van databank, net zoals Access, SQL Server, postgreSQL,...
SQLite heeft iets minder mogelijkheden dan de andere databanken (wat minder dataformaten mogelijk, bv. niet voor GIS-gegevens; niet alle complexe queries zijn mogelijk,...), maar het heeft wel als voordeel dat het 'licht' is: relatief weinig ballast, gemakkelijk aan te maken, gemakkelijk lokaal op te slaan of door te geven,...  En daarom is het het ideale formaat om bv. een voorbeelddatabankje te maken om in een R-package te steken.  (Ik denk dat we het er elders in deze gitrepo al wel eens over gehad hebben in een issue of PR.)

Maar ok, als je geen toepassing ziet, gaat de functie weg.  Vermits het niet zo visueel is als Access om queries samen te stellen, vermoed ik dat uw teamgenoten geen vragende partij zullen zijn voor zo'n functie.
