### ISSUE TITLE
probleem met `create_unique_tree_id()` bij gebruik in `check_trees_evolution()`

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#134]
De logica van functie `create_unique_tree_id()` is als volgt:

1. alle records zonder `old_id` (NA) krijgen een `tree_id`, opgebouwd uit `periode`, `plot_id` en `tree_measure_id` (met het idee dat dit alle bomen zijn in de eerste periode dat ze waargenomen zijn)
2. op basis van deze records mét ingevuld `tree_id` wordt in de lijst gekeken welke records hetzelfde `tree_id` moeten krijgen: dit zijn de records van de volgende `periode` met dezelfde `plot_id` en die een `old_id` hebben die naar het `tree_measure_id` van een ingevuld record verwijzen
3. deze tweede stap wordt herhaald zolang er bij elke herhaling nieuwe `tree_id`'s aangevuld worden

Maar als er bomen zijn waarbij een fout of onbekend `old_id` ingevuld is, dan zullen deze geen `tree_id` krijgen, en als dezelfde boom in een volgende periode ook gezien is (met wel een correct verwijzende `old_id`), krijgt deze ook geen `tree_id` omdat het record waarnaar deze verwijst, geen `tree_id` heeft.  Als dit gebeurt, krijg je wel de warning dat sommige records geen `tree_id` kregen.

Deze functie `create_unique_tree_id()` wordt ook gebruikt in de functie `check_trees_evolution()` om de databank te testen (zie issue #66), en bovenstaande heeft hier als gevolg dat:
- de records zonder tree_id gerapporteerd worden met `aberrant_field` "old_id" en `anomaly` "unknown id", en
- records van dezelfde boom van opeenvolgende periodes daarnaast nog eens extra gerapporteerd worden met `aberrant_field` "old_id" en `anomaly` "on same place but not coupled"

@leymanan is dit zo ok?  Of zou er nagedacht moeten worden over een manier om te zorgen dat opeenvolgende periodes toch nog een `tree_id` krijgen ondanks het feit dat er fouten in zitten?  (In de huidige situatie lijkt het me relatief makkelijk om de problematische records op te sporen, en na aanpassen en opnieuw runnen van de functies, krijg je uiteraard wel het juiste resultaat.  Ook test ik met een gedeeltelijke dataset waar ik een beperkt aantal soorten uitgehaald heb, ik weet niet in hoeverre dergelijke fouten voorkomen in de volledige dataset.)

**Comment by leymanan** [comment]
oldid zou nooit fout mogen zijn, omdat dit automatisch in fieldmap gegenereerd wordt
Maar bugs zijn steeds mogelijk, of per ongeluk/expres boom uit vorige periode verwijderd of ...

Dus voor mij is de controle ok zo: er moet gekeken worden waarom er een old-id is, die geen link heeft naar de voorafgaande periode, dat moet dan gecorrigeerd worden

**Comment by ElsLommelen** [comment]
Ok, da's gemakkelijk.  :-)  (Ik ga dan vooral die voorbeelddatabanken verbeteren zodat ze dit soort fouten niet hebben.)
