### ISSUE TITLE
functies load_data_xxxx geven foutmelding

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#135]
ik krijg onderstaande foutmeldingen

```
> plotinfo <- load_plotinfo(database = path_to_fieldmap_db)
An error occurred while the 'inbodb' package was updating the RStudio Connections pane:
Error in on_connection_closed(conn): object 'type' not found
If necessary, these warnings can be squelched by setting `options(rstudio.connectionObserver.errorsSuppressed = TRUE)`.
An error occurred while the 'inbodb' package was updating the RStudio Connections pane:
Error in on_connection_closed(conn): object 'type' not found
If necessary, these warnings can be squelched by setting `options(rstudio.connectionObserver.errorsSuppressed = TRUE)`.
Joining with `by = join_by(plot_id, plottype, forest_reserve, survey_trees)`
```

```
> data_dendro <- load_data_dendrometry(path_to_db) %>% filter(period == 3)
An error occurred while the 'inbodb' package was updating the RStudio Connections pane:
Error in on_connection_closed(conn): object 'type' not found
If necessary, these warnings can be squelched by setting `options(rstudio.connectionObserver.errorsSuppressed = TRUE)`.
An error occurred while the 'inbodb' package was updating the RStudio Connections pane:
Error in on_connection_closed(conn): object 'type' not found
If necessary, these warnings can be squelched by setting `options(rstudio.connectionObserver.errorsSuppressed = TRUE)`.
```

**Comment by leymanan** [comment]
ter aanvulling: de data worden wel "geload" maar ik krijg toch error ...

**Comment by ElsLommelen** [comment]
Vreemd, ik kan dat hier niet reproduceren, bij mij werkt het wel zoals het moet.  En ook zeer vreemd dat die foutmelding over inbodb gaat en niet over forrescalc.  Kan het zijn dat je nog een dataconnectie open had via inbodb?  Normaal zou dit geen probleem mogen geven als je 2 connecties gelijktijdig open hebt, maar ik heb de indruk dat het venster dat de connecties van de databank weergeeft, in dit geval gecrasht is of zoiets?  Heb je er momenteel nog last van, of is dit probleem intussen verdwenen na het herstarten van je computer?
In elk geval lijkt het me eerder een probleem van RStudio dan van forrescalc.  En moest het blijven opduiken bij gebruik van inbodb voorafgaand aan forrescalc, dan post je misschien best je voorgaande code (of de hele code) bij het package inbodb.

**Comment by leymanan** [comment]
error blijft, maar data worden gelukkig geladen.
Ik zal dat inderdaad eens posten bij inbodb-package, bedankt!

**Comment by ElsLommelen** [comment]
`dbConnect` is bij mijn weten geen package, dus dat lijkt me normaal.
Test misschien eens of je de packages odbc en DBI kan installeren (al zouden die er normaal op moeten staan als je forrescalc kan runnen)?  Als het niet aan odbc ligt, ligt het waarschijnlijk aan RStudio (hetgeen ervoor zorgt dat die connecties in die tab getoond worden).

Misschien kan je ook eens testen of het in R (niet RStudio) wel werkt zonder error?  Dan heb je uitsluitsel of het aan RStudio ligt of aan odbc.

**Comment by leymanan** [comment]
odbc en dbi staan er idd al op

ik vond het ook raar omdat ik - naar mijn weten - inbodb nergens voor gebruikte. Maar blijkbaar laadt ik bij mijn setup toch wel die library(inbodb) in. Als ik die niet inlaadt, is melding weg!
