### ISSUE TITLE
vraag i.v.m. `from_git_to_access()`

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#136]
Ik heb `read_forresdat()` aangepast zodanig dat deze functie de tabel rechtstreeks van de website van github leest, dus zonder dat het nodig is om de repo binnen te halen of zonder te authenticeren (vermits het een publieke repo is, is dat niet nodig).  Dat gaat het voor de gebruikers een heel pak gemakkelijker maken, lijkt mij.

Voorlopig haal ik wel enkel de tsv binnen om te testen (met mogelijk onvolledige info omdat git2rdata een deel relevante info in de yaml steekt), idee is om dit met de csv te doen zodra we frictionless gebruiken.  En ook: voorlopig test ik niet of de gebruiker een correcte tabelnaam ingeeft, dus het zou weleens een vreemde foutmelding kunnen worden als hij dat niet doet.  Idee is om dit laatste wel te testen zodra we frictionless gebuiken, gebruik makend van de info uit de json.

Nu lijkt het me best om dat systeem ook toe te passen bij `from_git_to_access()`, maar ik weet niet meer wat hier de bedoeling is: een generieke functie om een tabel uit eender welke repo in te laden (zoals de naamgeving en documentatie aangeven), of dit specifiek maken voor gegevens uit forresdat.
- ingeval van enkel forresdat lijkt het me het beste om in de functie gewoon `read_forresdat()` aan te roepen, dan kunnen we binnenkort ook profiteren van het voordeel dat de tabelnamen gecheckt worden, en dan wordt enkel CP of CA binnengehaald (en dan moeten we misschien wel ook de argumenten van `read_forresdat()` overnemen om de gebruiker de nodige keuzevrijheid te geven).  En dan willen we de functie misschien hernoemen naar `from_forresdat_to_access()`?
- ingeval van een generieke functie zal het zeer moeilijk zijn om fouten in de invoer van tabelnaam of reponaam te gaan controleren, ik kan dan wel bij een probleem hiermee de foutmelding aanpassen naar een tekst die aangeeft dat de tabelnaam of reponaam fout is.  En dan hebben we ook het nadeel dat een gebruiker niet kan kiezen tussen CP en CA of standaard enkel CP krijgt.  (En dat we er bij aanpassingen in `read_forresdat()` aan moeten denken om na te gaan of ze ook hier relevant zijn.)

Wat denk je, welke optie zouden we hier kiezen?

**Comment by leymanan** [comment]
> Ik heb `read_forresdat()` aangepast zodanig dat deze functie de tabel rechtstreeks van de website van github leest, dus zonder dat het nodig is om de repo binnen te halen of zonder te authenticeren (vermits het een publieke repo is, is dat niet nodig). Dat gaat het voor de gebruikers een heel pak gemakkelijker maken, lijkt mij.

dat is inderdaad veel makkelijker!

**Comment by leymanan** [comment]
> Nu lijkt het me best om dat systeem ook toe te passen bij `from_git_to_access()`, maar ik weet niet meer wat hier de bedoeling is: een generieke functie om een tabel uit eender welke repo in te laden (zoals de naamgeving en documentatie aangeven), of dit specifiek maken voor gegevens uit forresdat.
> 
> * ingeval van enkel forresdat lijkt het me het beste om in de functie gewoon `read_forresdat()` aan te roepen, dan kunnen we binnenkort ook profiteren van het voordeel dat de tabelnamen gecheckt worden, en dan wordt enkel CP of CA binnengehaald (en dan moeten we misschien wel ook de argumenten van `read_forresdat()` overnemen om de gebruiker de nodige keuzevrijheid te geven).  En dan willen we de functie misschien hernoemen naar `from_forresdat_to_access()`?
> * ingeval van een generieke functie zal het zeer moeilijk zijn om fouten in de invoer van tabelnaam of reponaam te gaan controleren, ik kan dan wel bij een probleem hiermee de foutmelding aanpassen naar een tekst die aangeeft dat de tabelnaam of reponaam fout is.  En dan hebben we ook het nadeel dat een gebruiker niet kan kiezen tussen CP en CA of standaard enkel CP krijgt.  (En dat we er bij aanpassingen in `read_forresdat()` aan moeten denken om na te gaan of ze ook hier relevant zijn.)
> 
> Wat denk je, welke optie zouden we hier kiezen?

doe maar optie 1, was inderdaad enkel de bedoeling om de tabellen uit forresdat makkelijk in een access-tabel te krijgen

**Comment by ElsLommelen** [comment]
Moeten de argumenten van `read_forresdat()` overgenomen worden (dus in functie `from_git_to_access()` ook gebruikt kunnen worden als argument)?  Zo ja, welke default moeten ze krijgen?  Zo nee, welke waardes gebruik ik hiervoor?  (Een argument wel overnemen en het andere niet, kan uiteraard ook.)

Het gaat over de volgende argumenten:
- join_plotinfo: of de tabel plotinfo aan de opgevraagde tabel gekoppeld moet kunnen worden, default in `read_forresdat()` is TRUE
- plottype: van welk plottype de gegevens opgehaald moeten worden, default in `read_forresdat()` is 'CP'

**Comment by leymanan** [comment]
> Moeten de argumenten van `read_forresdat()` overgenomen worden (dus in functie `from_git_to_access()` ook gebruikt kunnen worden als argument)? Zo ja, welke default moeten ze krijgen? Zo nee, welke waardes gebruik ik hiervoor? (Een argument wel overnemen en het andere niet, kan uiteraard ook.)
> 
> Het gaat over de volgende argumenten:
> 
> * join_plotinfo: of de tabel plotinfo aan de opgevraagde tabel gekoppeld moet kunnen worden, default in `read_forresdat()` is TRUE
> * plottype: van welk plottype de gegevens opgehaald moeten worden, default in `read_forresdat()` is 'CP'

Enkel de keuze om voor CP of CA te kiezen lijkt me relevant, met als default echter wel allebei (CP én CA naar access).
Sowieso zou ik altijd plotinfo willen toevoegen (join_plotinfo = TRUE).

**Comment by ElsLommelen** [comment]
> Enkel de keuze om voor CP of CA te kiezen lijkt me relevant, met als default echter wel allebei (CP én CA naar access).

ok

> Sowieso zou ik altijd plotinfo willen toevoegen (join_plotinfo = TRUE).

Euh, ik had het zo geïmplementeerd, maar als ik dan het voorbeeld van de functie run (met qAliveDead en qdecaystage als over te zetten tabellen), dan krijg ik de error dat er geen kolom 'plot_id' in de gevraagde tabel zit, en dat join_plotinfo op FALSE moet, terwijl de gebruiker dit zelf niet kan aanpassen.  Dus misschien toch maar gewoon de default op TRUE zetten, en ervoor zorgen dat de gebruiker het wel kan aanpassen als het nodig is?
