### ISSUE TITLE
extra argument "processed" bij calculate-functies

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#137]
bij de `load_data_xxx()` - functies is er een extra argument `processed `dat toelaat om al dan niet geproceste data in te laden.

Bij de calculate-functies is die mogelijkheid er niet, maar wordt er obv `survey_trees `en/of `survey_deadwood ` mogelijks een '0' toegekend aan plots die niet in de dataset zitten (o.a. omdat ze "non-processed" zijn, en dus bij de load-functie weggefilterd zijn), maar waar wel een survey gebeurd is.

Dus om volledig te zijn, zou er ook bij de calculate-functies  een extra argument `processed ` moeten toegevoegd worden.
Eventueel met een warning dat als `processed = FALSE/TRUE`, dat ook de input-data `processed  = FALSE/TRUE` moet zijn.
(als input data deels "niet processed" zijn, maar bij calculate-functies stel je dat `processed = TRUE` moet zijn , zal je toch resultaten krijgen voor non-processed plots)

Als `processed = TRUE`, dan moet 

- OF de variabele `processed_data` in combinatie met `survey_trees ` / `survey_deadwood` gebruikt worden om een NA door een 0 te vervangen
- OF op einde van elke functie de non-processed data met een anti-join verwijderd worden
Bv. 
`anti_join(plotinfo %>% filter(data_processed == FALSE), by = c("plot_id", "period"))`

**Comment by leymanan** [comment]
Of we gooien die "processed" helemaal weg uit het package als 't te complex wordt, en 't is aan de gebruiker om enkel met data te werken waar een datacontrole op gebeurd is, en waar hoogtemodellen voor gemaakt zijn.

Die kan dan zelf op einde van de analyse een filter doen en enkel de "processed" data behouden.

**Comment by ElsLommelen** [comment]
Klinkt inderdaad vrij complex, waarom niet gewoon bij `load_plotinfo()` als extra argument ook `processed` toevoegen dat default op TRUE staat, net als bij de `load_data_xxx()`-functies?
Als de default overal hetzelfde staat (TRUE), gaat een gebruiker die van dat argument afblijft, niet in de problemen komen (want enkel de verwerkte gegevens worden geladen).  En iemand die het wel wil gebruiken, moet maar zorgen dat hij/zij het argument overal dezelfde waarde geeft en dus consequent voor alle delen van de berekening dezelfde dataset binnenhaalt (ofwel enkel processed, ofwel alles).  Of zie ik iets over het hoofd waardoor dit de situatie toch niet zou oplossen?

**Comment by leymanan** [comment]
> Klinkt inderdaad vrij complex, waarom niet gewoon bij `load_plotinfo()` als extra argument ook `processed` toevoegen dat default op TRUE staat, net als bij de `load_data_xxx()`-functies?

goed idee, niet aan gedacht

**Comment by ElsLommelen** [comment]
> > Klinkt inderdaad vrij complex, waarom niet gewoon bij `load_plotinfo()` als extra argument ook `processed` toevoegen dat default op TRUE staat, net als bij de `load_data_xxx()`-functies?
> 
> goed idee, niet aan gedacht

Ik zie dat bij de `load_data_xxx()`-functies behalve `processed = TRUE` ook argumenten `plottype` en `forest_reserve` (met default NA) als selectiecriteria zijn opgegeven.  Is het zinvol om die ook meteen toe te voegen bij `load_plotinfo()`, of niet?  (Is amper extra inspanning omdat die selectie in een aparte functie zit.)
