### ISSUE TITLE
datacontrole aanvulling game impact survey? 

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#139]
kan er ook gecheckt worden of - indien GameImpactRegObserved = 10 - 
rubbing_damage_number <= nr_of_regeneration
en 
rubbing_damage_number <= max_number_of_regeneration

ik zag zo een (typ)foutje passeren, daarmee ...  (50 ipv 5)

**Comment by ElsLommelen** [comment]
Ok.
Welk veld geef ik op als aberrant veld (en voor de aberrante waarde), en wat geef ik als foutmelding?
In de databank heet rubbing_damage_number 'game_damage_number' (maar dan deels in CamelCase en deels snake_case): behoud ik de naam van de databank (maar omgezet naar snake_case), of gebruik ik rubbing_damage_number hier?  (Voorlopig heb ik bij de check-functies de naamgeving zo dicht mogelijk bij die van de databank gehouden, maar wel de omzetting naar snake_case gedaan om de naamgeving in het package wat uniform te houden.  En met ook in het achterhoofd: als ik een website met de documentatie wil toevoegen en unittests automatisch uitvoeren enz., dan is checklist gebruiken de gemakkelijke optie, maar dan is het wel het volledige pakket zoals Thierry het ontworpen heeft, dus inclusief stijl voor naamgeving en layout.  Op zich zou ik de naamgeving in de finale stap terug kunnen omzetten naar de originele databanknamen zonder in de problemen te geraken, dus laat gerust weten als je dat zou willen.)
