### ISSUE TITLE
foutmelding load_plotinfo() - recent

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#144]
ELs,

kan het zijn dat er een foutje geslopen is bij één van de laatste wijzigingen aan `load_plotinfo()`?

Ik krijg volgende foutmelding

```
Error: nanodbc/nanodbc.cpp:1710: 42000
[Microsoft][ODBC Microsoft Access-stuurprogramma] Syntaxisfout (operator ontbreekt) in query-expressie --add column name for right order (to be overwritten)
        99.
```

En ik zag dat in commit b973c6610f887e2838a3508a2d088b346b5f6e55 "--add column name for right order (to be overwritten)" toegevoegd werd (https://github.com/inbo/forrescalc/commit/b973c6610f887e2838a3508a2d088b346b5f6e55)

**Comment by ElsLommelen** [comment]
Euh, `--` is in SQL gewoon het toevoegen van commentaar in SQL, net zoals `#` in R.  Alternatief is dat hetgeen ik ervoor geschreven heb, niet door Access aanvaard wordt.  (Nu ik dat SQLite-databankje heb, vergeet ik al eens om het ook in Access te testen, dus goed dat je het opmerkt!)

**Comment by ElsLommelen** [comment]
Ok, blijkbaar kan commentaar toevoegen aan de SQL niet in Access, ik zal deze verwijderen zodra ik terug in branch testdatabase aan 't werken ben.  En dan evt. voor de query dit even kort uitleggen, want ik vermoed dat we ons anders toch wel ooit gaan afvragen waarom we het zo opgelost hebben.  Trouwens, zoals je wellicht gezien hebt, komt dat ook in andere load-functies voor.

**Comment by leymanan** [comment]
`load_plotinfo.R` bevat op regel 66 ook nog "--" comment.
Pas ik dat aan of jij?

**Comment by ElsLommelen** [comment]
Ah, maakt mij niet uit.  Als je nog andere aanpassingen in die query wil doen, doe je het beter zelf, anders wil ik het gerust doen.

**Comment by leymanan** [comment]
nee, geen andere aanpassingen te doen ;-)

**Comment by ElsLommelen** [comment]
Dan doe ik het wel even, het staat nu toch open.  ;-)

**Comment by ElsLommelen** [comment]
Ik heb ook even het hele package gecheckt, en nu staan er echt geen commentaren meer in queries...
