### ISSUE TITLE
opkuis van calc_stem_volume()

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#145]
Voor `calc_stem_volume()` geeft `lintr::lint_package()` de opmerkingen dat er code in commentaar staat, en dat enkele lijnen meer dan 80 karakters lang zijn.  En eerlijk gezegd, door de vele opmerkingen ziet het er wel wat rommelig uit, maar omdat jij de code geschreven hebt, durf ik het ook niet goed opkuisen om geen relevante info te verwijderen.  Zou jij dit even kunnen bekijken en in orde brengen (opkuisen en/of verduidelijken)?  Voor alle duidelijkheid: je mag gerust een beetje uitleg behouden zodat je achteraf nog begrijpt waarom je die keuze gemaakt hebt, al zou je ook kunnen overwegen om dit hier bovenaan in de documentatie toe te voegen, of ergens in een vignet dat de berekeningen beschrijft (en de keuzes die hierin gemaakt zijn).

Hmm, en in verband met die documentatie ook nog een vraag/opmerking: hier staat dat dit een interne helperfunctie is (en meestal zijn dat functies die niet de bedoeling hebben om buiten het package gebruikt te kunnen worden), maar ze wordt wel geëxporteerd.  Mogelijk is dit tijdelijk gedaan om gemakkelijker te kunnen werken, dus in dat geval zou ik ze nu terug intern kunnen maken.  Zal ik dit doen?  (Zoals je weet, je kan die dan nog wel gebruiken, maar die is niet zomaar vindbaar en ik zorg dan uiteraard ook dat de documentatie niet op de website komt, maar uiteraard wel aan te raden om voor onszelf dat de documentatie behouden blijft.)

**Comment by leymanan** [comment]
ik heb @NoRd toegevoegd en @eport verwijderd: is dat voldoende om daar een interne functie van te maken?
Indien niet, mag jij het nodige doen ;-)

**Comment by ElsLommelen** [comment]
Zie PR #146  ;-)
