### ISSUE TITLE
datacontrole tussen twee periodes: 1_2 ipv 2_1

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#147]
als het niet veel werk is, zou het iets handiger zijn mocht diff van de periodes steeds vertrekken van de eerste periode
dus 1_2 en 2_3 ipv 2_1 en 3_2.

**Comment by ElsLommelen** [comment]
Euh, enerzijds begrijp ik dat je die periodes graag in chronologische volgorde wil vermelden, maar anderzijds vraag ik me af of het niet verwarrend zou kunnen zijn als je 1_2 schrijft maar in de achtergrond voor de berekeningen 2-1 doet en niet 1-2 om bv. de boomvolumes tussen de periodes te vergelijken.  En dan is ook de vraag: trekken we de lijn door naar `compare_periods_per_plot()`, of doen we dit enkel in de check-functies?

Misschien het als volgt oplossen voor zowel `check_trees_evolution()` als `compare_periods_per_plot()`?
- bij alles waar de waarden gegeven worden als tekst met scheidingsteken `-` of `_` tussen, geven we de oudste periode eerst (bv. vermelding van de jaartallen, status van boom zoals alive_dead, decaystage,...)
- bij alles waar we berekeningen maken (waarden tussen periodes vergelijken), doen we de oudste periode min de jongste periode, zodat we een positief getal krijgen als er een toename is van de oudste naar de jongste periode

Klinkt dat logisch?  Zie ik functies over het hoofd met een gelijkaardige situatie?
