### ISSUE TITLE
datacontrole op NA's bij game impact reg/veg - NIET

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#148]
In twee van mijn commits (2cc12b671cbe07de41e0a148d15c1d408a200054 en 3e78eed45930b55f802b0dcbdc24849cd8a27da2)
suggereer ik om niet de NA's te detecteren ("missing"; wordt opgevangen bij de dataverwerking en overload om dat telkens bij te werken), maar om te signaleren dat er - als GameImpactReg/VegObserved = TRUE/10 -in het gehele bosreservaat nergens één waarneming van game damage was.
Want dan zou het kunnen dat GameImpactReg/VegObserved = FALSE is.

Maar dat lijkt me overbodig.

**Comment by ElsLommelen** [comment]
Euh, kan je even situeren waar je die commits toegevoegd hebt (welke branch, evt. welke PR)?  (In dit geval was het waarschijnlijk handiger geweest, moest je een PR aangemaakt hebben en daarin deze vraag stellen.)

Ik begrijp je uitleg niet heel goed (misschien omdat ik de context van je aanpassingen wat mis), maar sowieso wordt die missing nu al enkel gegeven als er minstens een waarneming van game damage of browse index was in die plot en periode (voor moest je dit over het hoofd gezien hebben).  Ik heb de indruk dat je het nu toch anders zou willen, uiteraard geen probleem, maar ik begrijp eerlijk gezegd niet heel goed wat je precies bedoelt.  Zou je het wat concreter kunnen maken, of evt. een voorbeeld geven van iets wat niet of wel gedetecteerd moet worden?  Of je mag uiteraard ook zelf een aanzet doen als het gemakkelijker in code uit te leggen is dan in tekst.  ;-)  (Of even online uitleggen als dat vlotter gaat...)

Ik geef ook alvast enkele opmerkingen over de aanpassingen die je gedaan hebt, zodat we dit zeker niet vergeten aan te passen:
- zorg dat je meteen alles verwijdert wat met de berekening te maken heeft, dus in dit geval ook berekening van variabelen `not_na_browse_index` en `not_na_game_damage_number` die (als ik het goed voorheb) enkel voor deze berekening gebruikt worden
- in verband met commit 3e78eed: deze zal sowieso een foutmelding geven omdat `field_game_damage_number` na de aanpassing in lijn 120 nog niet gekend is, dus het is altijd een goed idee om na aanpassingen het package te bouwen en te testen om niks over het hoofd te zien

**Comment by leymanan** [comment]
> Dus als ik het goed begrijp: in plaats van de huidige missing als er minstens een keer geen NA is, zou je willen dat gerapporteerd wordt als er overal NA is terwijl dit in plotdetails anders aangegeven wordt, dus `game_impact_reg == 10 & !not_na_game_damage_number`? Wat hierbij wel wringt, is dat bij deze checks de gegevens per soort en hoogteklasse weergegeven gaan worden, dus dan ga je bv. alle records met NA moeten toevoegen. Alternatief is dat we deze test(s) zouden toevoegen aan `check_data_plotdetails()`, waar dit wel op plotniveau weergegeven wordt en waar de commentaar kan zijn dat GameImpactRegObserved niet juist is. Dit laatste lijkt me iets logischer vanuit het standpunt van de gebruiker?

ja, dat is inderdaad veel logischer, nog niet zo bekeken! Bedankt!

**Comment by leymanan** [comment]
> Euh, kan je even situeren waar je die commits toegevoegd hebt (welke branch, evt. welke PR)? (In dit geval was het waarschijnlijk handiger geweest, moest je een PR aangemaakt hebben en daarin deze vraag stellen.)

ja, sorry, is paar dagen geleden en ik weet het zelf al niet goed meer, dus daar moet ik inderdaad op letten!
Ik dacht dat ik al veel info gegeven had door commits te vermelden.
Het betrof twee commits in branch [testdb_checks_AL](https://github.com/inbo/forrescalc/compare/testdb_checks_AL)
Ik zal er volgende keer een aparte PR voor maken, maar zat zo in die branch van datacontrole, dat ik dacht dat dat er wel bij kon.
En zat nog niet in stadium om van die branch een PR te maken ...

**Comment by ElsLommelen** [comment]
Geen probleem, hoor.  Ik wou vooral de tip geven dat een vraag over code die je aan 't schrijven bent in een nieuwe branch, ook aanleiding mag zijn om alvast een PR aan te maken en die evt. op 'draft' te zetten om aan te geven dat je er nog niet mee klaar bent.
Laat ook maar weten hoe je hiermee verder wil.  Idealiter worden de besproken suggesties in dezelfde branch toegevoegd om nog een klein beetje te weten waar we mee bezig zijn.  ;-)  (Als je wil dat ik je hiermee help nadat je je branch afgewerkt hebt, dan kan je in je PR even verwijzen daar dit issue als je de PR aanmaakt en afgewerkt hebt.  Je ziet maar wat het handigst is.)

**Comment by ElsLommelen** [comment]
Ik denk dat dit intussen opgelost is en gesloten kan worden?
