### ISSUE TITLE
extra check op niveau van plotdetails (?)

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#150]
Het zou handig zijn mocht er ook nog een check komen op niveau van plotdetails, voor `date_dendro`.
Om te checken of er binnen één bosreservaat en plottype bepaalde plots zijn die op een afwijkend moment opgemeten werden, wat kan wijzen op een typfout.
Bv. alle opnames gebeurden in 2022, maar één plot in 2023 of in 2021...

Ik weet niet goed hoe ik dat best kan inwerken in de functie `check_data_plotdetails()`, daar zit nu nog geen check in op bosreservaatsniveau.

- Aberrant field = `date_dendro`
- Aberrant value = datum van opname (`date_dendro`)
- Anomaly = deviating

Als te complex, mag je dat ook laten vallen ...

Een vergelijkbare check is deze op niveau van de vegetatie-opname (layer `Vegetation`) , veld `Date` en de verjongingsopname (layer `Regeneration`), ook veld `Date`. Maar ook hier dus nog geen controle die op reservaatsniveau (en plottype) groepeert.

Maar misschien leidt dit ons allemaal wat te ver??

**Comment by ElsLommelen** [comment]
Euh, zou je 'op een afwijkend moment' concreet kunnen maken?  Gaat dit over een afwijkend jaartal, zoals in dit voorbeeld, of moet er ook naar de maanden of dagen gekeken worden?  Enfin, vanaf wanneer spreek je over een afwijkend moment?

**Comment by leymanan** [comment]
> Euh, zou je 'op een afwijkend moment' concreet kunnen maken? Gaat dit over een afwijkend jaartal, zoals in dit voorbeeld, of moet er ook naar de maanden of dagen gekeken worden? Enfin, vanaf wanneer spreek je over een afwijkend moment?

afwijkend jaartal is OK

**Comment by ElsLommelen** [comment]
Moet het jaartal van de vegetatie-opname of verjongingsopname ook overeenkomen met dat van de dendrometrie, of moeten enkel de datums binnen een opnametype van hetzelfde jaar zijn?

**Comment by leymanan** [comment]
> Moet het jaartal van de vegetatie-opname of verjongingsopname ook overeenkomen met dat van de dendrometrie, of moeten enkel de datums binnen een opnametype van hetzelfde jaar zijn?

enkel de datums binnen een opnametype

**Comment by ElsLommelen** [comment]
Dus ik ga ervan uit dat je bedoelt dat deze unittests zouden moeten slagen: als er een datum is waarin het jaartal afwijkt van de andere, wordt voor het record met de afwijkende datum een record toegevoegd aan de tabel met afwijkende waarden.
(Bij deze dus een voorbeeld waarbij ik eerst de unittest schrijf en pas daarna de code, nu ik toch net met unittests bezig was.  ;-) In dit geval is er niet echt een voordeel, behalve dat ik je kan duidelijk maken hoe ik het zie, maar als je bestaande code wil aanpassen omdat ze in een welbepaalde situatie niet het juiste resultaat geeft maar in de meeste andere situaties wel, is dit eigenlijk een gemakkelijke manier van werken, en ook veilig als je al een aantal unittests zou hebben voor de situaties waarin de code wel correct werkt.)

Om op het niveau van een bosreservaat uit te maken welk jaartal het 'juiste' is, neem ik best de mediaan van het jaartal of de datum, neem ik aan?  In de veronderstelling dat de meerderheid van de records een juiste datum heeft, lijkt me dit de meest betrouwbare methode.

**Comment by ElsLommelen** [comment]
Voila, bij deze is dat in orde, laat zeker weten als het toch niet is wat je in gedachten had.

En in tegenstelling tot wat ik hierboven aangaf, heb ik ook nog eens mogen ondervinden dat die unittests vooraf maken, altijd wel grote voordelen heeft: het schrijven kost niet meer tijd als eenmalig testen of de functie werkt en het helpt ook bij het vooraf nadenken over wat je precies wil/verwacht als resultaat.  En als je code niet direct bij de eerste test het juiste resultaat geeft, kan je nadien met een druk op de knop telkens opnieuw testen tot alle test in orde zijn.  (Terwijl ik anders soms wel zit te sukkelen om die voorbeelden te runnen en voor elke situatie een praktijkvoorbeeld te zoeken, en dat bij elke poging opnieuw, omdat het vooraf niet echt de moeite lijkt om een script neer te schrijven om te testen.)  En achteraf is er uiteraard ook nog het extra voordeel dat die test je in de toekomst helpt om erover te waken dat de geteste functionaliteit behouden blijft als je iets wil aanpassen.

(Zoals je kan zien, heb ik tijdens het schrijven van de functie nog 2 kleine aanpassingen gemaakt in die unittests, maar dat gebeurt enkel als het niet anders kan:
1. Eerder kon aberrant_value numeriek zijn omdat de datum enkel output NA had, maar nu is er soms ook een datum als output, waardoor ik van aberrant_value een character heb moeten maken (wat bij bv. `check_tree_evolution()` nu al het geval is).
2. Ik had initieel verkeerd gegokt bij de exacte output van de datum: die CEST bleek er niet bij te staan.

Voor die unittests is het zeer belangrijk dat die niet zomaar aangepast worden, enkel als het echt niet anders kan of bij een duidelijke vergissing.  Nu zijn we nog in een beginfase, en de unittests zijn er pas, maar zodra het package iets langer in gebruik is, betekent elke aanpassing in de unittest dat een gebruiker ineens geconfronteerd gaat worden met iets dat ineens anders werkt dan voorheen.  Dus dat wil je enkel doen als het nodig is, en dan dat liefst ook duidelijk communiceren...)
