### ISSUE TITLE
date format problem in load_data_herblayer

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#22]
As the first records of date_vegetation only contain a date and deviation_date contains date and time, these cannot be combined without giving an error while extracting year (they are both in the POSIXct format but have a different origin).  At present year is extracted on both sets separately, it should be nice to combine the dates first into one column.

**Comment by ElsLommelen** [comment]
@leymanan Ik heb een manier gevonden om dit op te lossen en om dus `deviating_date` en `date_vegetation` (al in de query) samen te voegen in 1 kolom (dus `deviating_date` gebruiken als opgegeven, anders `date_vegetation`).  Noem ik het resultaat `date_vegetation`, of heb je een ander voorstel?

**Comment by leymanan** [comment]
ik vind dat heel raar dat er een verschil zit op date bij `date_veg `en `dev_date`: ik heb dat nog eens bekeken, en zowel in fieldmap-projectmanager, als in de access-db zie ik geen verschil in format tussen beide.

Maar jouw voorste van naam is ok:  `date_vegetation`

**Comment by ElsLommelen** [comment]
Waarschijnlijk was er ook geen echt verschil, maar maakte R er om een of andere reden andere formaten van (R baseert zich altijd op de eerste 100 records om een formaat te kiezen, en mss zorgt het grote aantal NA's bij `dev_date` ervoor dat er te weinig (of geen) records zijn om tot hetzelfde formaat te komen?).  In elk geval, om me niet te moeten verdiepen in datumformaten in R, heb ik de tabellen simpelweg in de query samengevoegd.  :-D  (Daardoor weet ik dus ook niet wat het 'probleem' precies was.)
