### ISSUE TITLE
compare_periods() for multiple periods

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#23]
append compare_periods() to comparison of more than 2 periods

**Comment by ElsLommelen** [comment]
Voor de zekerheid: hoe doe ik dit best?  Nu neemt deze het verschil tussen periode 2 en 1, maar voeg ik in dat geval enkel het verschil tussen periode 3 en 2 toe, of ook tussen 3 en 1?  En ingeval van de laatste keuze: wat als we naar 4 periodes gaan?  Vervangen we dan het verschil tussen 3 en 1 door het verschil tussen 4 en 1, of moeten alle combinaties erin zitten?  (Dat laatste kan op termijn wel heel overzichtelijk worden.)

**Comment by ElsLommelen** [comment]
@leymanan Kan je hier even aangeven hoe ik dit best oplos?

**Comment by leymanan** [comment]
oeps, ik heb toch indruk dat ik nooit mails ontvangen heb van die toewijzingen.
Ik heb nu eens gefilterd op toegewezen aan mij, en ben ze eens aan 't aflopen.
OK als ik dan terug aan u toewijs?

**Comment by leymanan** [comment]
en hier mijn antwoord:
het zou inderdaad leuk zijn om extra verschillen te kunnen berekenen, maar misschien is dit allemaal wat overload voor het package?

Maar als je dat toch wil toevoegen, dan is het voldoende om enkel de opeenvolgende periodes te vergelijken:

- 1 en 2
- 2 en 3
- 3 en 4 (omdat we nu voor één reservaat al 4 opnames hebben (Kersselaerspleyn 1986))

Maar opnieuw: als dat veel werk is, laat dat dan maar zo! Want ben echt niet zeker of dat veel gebruikt gaat worden.
We kunnen toch met de functie zoals ze nu is, achtereenvolgens periodes gaan vergelijken (eerst filteren op periode 1 & 2 en die vergelijken, en dan eens filteren op periode 2 & 3, en dan die vergelijken, ...)

**Comment by ElsLommelen** [comment]
> oeps, ik heb toch indruk dat ik nooit mails ontvangen heb van die toewijzingen.
> Ik heb nu eens gefilterd op toegewezen aan mij, en ben ze eens aan 't aflopen.
> OK als ik dan terug aan u toewijs?

Je was toen in verlof, als ik me niet vergis.  Om voor mezelf wat duidelijk te maken wat ik al bekeken had en waar ik niet verder kon, heb ik die toen aan u toegewezen (en je ook via email verwittigd, maar die is mss tussen alle andere emails van de vakantie verdwenen?).  Maar inderdaad, als je een antwoord geeft, mag je ze terug aan mij toewijzen, dan pik ik dat binnenkort allemaal op.

**Comment by ElsLommelen** [comment]
Opgelost in commit [4809a8c](https://github.com/inbo/forrescalc/commit/4809a8c5c47b9bb1e669dbe9c4f1220bd430dd70) (zie ook issue #121)?
