### ISSUE TITLE
rubbing dammage per species - core area

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#33]
Ik had graag rubbing_damage_perc mee opgenomen gezien in de functie "calculate_regeneration_core_area_species".
Probleem hier bij is:

1. rubbing_damage werd niet voor alle periodes en bosreservaten genoteerd, dus toevoegen van na.rm geeft soms ongewild als resultaat '0" (bv. Pruikemakers KV, periode 1)
2. rubbing_damage wordt sowieso enkel genoteerd bij de hogere hoogteklasses, daar zou na.rm dan weer wel nuttig kunnen zijn.

Ik was gestart dit aan te passen in een afzonderlijke branch, maar ik ga die weer verwijderen. Misschien beter dat jij dit doet, eens je wat tijd hebt. Is niet superdringend.

**Comment by ElsLommelen** [comment]
Opgelost door:
- `rubbing_damage_perc` berekend als som van `rubbing_damage_number` t.o.v. som van `nr_of_regeneration` in A2 (dus hogere hoogteklasses) met voor beide sommen `na.rm = TRUE`
- als `rubbing_damage_number` nergens genoteerd is (dus enkel NA's), dan wordt NA als resultaat gegeven 

Ik merk dat deze variabele ook in andere `calculate_regeneration`-functies berekend is, ik zal hier dezelfde berekeningswijze toepassen (dat gaat het voor de gebruikers en het schrijven van de documentatie een stuk gemakkelijker maken).

**Comment by ElsLommelen** [comment]
**Info over bug:**

Bovenstaande was opgelost met de volgende code:
```
rubbing_damage_perc =
        sum(.data$rubbing_damage_number, na.rm = TRUE) * 100 /
        sum(.data$nr_of_regeneration * (.data$subcircle == "A2"), na.rm = TRUE),
not_na_rubbing = sum(!is.na(.data$rubbing_damage_perc)),
```
Door de `na.rm = TRUE` in `sum(.data$rubbing_damage_number, na.rm = TRUE)` krijg je voor rubbing_damage_perc telkens waarde 0  als er geen metingen zijn, want `sum(NA, na.rm = TRUE)` geeft als resultaat `0` en niet `NA`.  Maar hierboven staat dat het idee was om dit als volgt op te lossen:

> * als `rubbing_damage_number` nergens genoteerd is (dus enkel NA's), dan wordt NA als resultaat gegeven

Dus eigenlijk had de `rubbing_damage_perc` van de laatste regel `rubbing_damage_number` moeten zijn om de waarde 0 omwille van `na.rm = TRUE` weg te werken.  De (niet eerder gerapporteerde maar toevallig ontdekte) bug is gefixt door dit aan te passen.

**Comment by leymanan** [comment]
OK!
Klopt toch dat `rubbing_damage_number` al op '0' gezet is, wanneer er niks genoteerd werd maar `GameImpactRegObserved = 10`:
```
IIf(Subquery.rdn IS NULL AND pd.GameImpactRegObserved = 10 AND
              Subquery.species IS NULL,
              0, Subquery.rdn) AS rubbing_damage_number
```

**Comment by ElsLommelen** [comment]
> OK! Klopt toch dat `rubbing_damage_number` al op '0' gezet is, wanneer er niks genoteerd werd maar `GameImpactRegObserved = 10`:
> 
> ```
> IIf(Subquery.rdn IS NULL AND pd.GameImpactRegObserved = 10 AND
>               Subquery.species IS NULL,
>               0, Subquery.rdn) AS rubbing_damage_number
> ```

Ah ja, oeps, goed dat je het zegt.  Dan hoef ik dat niet meer op te vangen met die plotinfo in de calculate-functies.  Ik zal de overbodige code even terug verwijderen.

**Comment by ElsLommelen** [comment]
ok, uitgevoerd in commit 52be1554
