### ISSUE TITLE
create_statistics van de variabele rubbing damage_perc - niet correct

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#34]
AANDACHTSPUNT: statistics van een percentage geven niet het correcte resultaat

Beter is om naar de basisdata terug te grijpen: aantal individuen met en zonder veegschade, en dit per bosreservaat.

Voor wat betreft de kernvlaktesis dit al gebeurd in functie calculate_regeneration_core_area_height_species.
Zie vorige issue om dit ook toe te voegen aan calculate_regeneration_core_area_species

Hoe pakken we dat best aan voor de cirkelplots?
Er is - buiten create_statistics - geen functie die groepeert op bosreservaat.
Dit kan uiteraard berekend worden via afzonderlijke code - vertrekkende van data_herblayer -  die de berekening doet op moment dat ernaar gevraagd wordt 
Of is het zinvol om er een functie van te maken? 
Lijkt me nogal specifiek, dus misschien overkill?

**Comment by ElsLommelen** [comment]
Het hangt ervan af wat je bedoelt: als je 'statistieken' wil van je percentages, dus een gemiddelde percentage veegschade per plot, dan klopt het resultaat wel (of zou het moeten kloppen).
Wat jij wil, is de totale veegschade berekenen over het totaal aantal bomen voor het hele bosreservaat.  Hier tellen plots met meer bomen dus zwaarder mee dan plots met weinig bomen, terwijl bij het voorgaande het resultaat van elke plot even zwaar meetelt.

Wat je als gebruiker zou kunnen doen om dit recht te trekken (zonder aanpassingen in het package), is voor elk record de variabele `rubbing_damage_perc` vermenigvuldigen met de verjonging ('regeneration van A2' of 'established') per ha (en te delen door 100), om het aantal bomen veegschade per ha te bekomen, dan van dit laatste getal en de verjonging de statistieken opvragen met `create_statistics()`, en dan zelf terug omzetten naar percentage door de deling opnieuw te maken.

Een alternatief is om in `create_statistics()` de mogelijkheid in te bouwen om met gewichten te werken voor de statistieken (en dan zou je in dit geval de verjonging per ha als gewicht kunnen opgeven), maar dat gaat dan stilaan voorbij aan jullie wens om enkel eenvoudige statistieken in het package te steken.

En nog een ander alternatief is om in de `calculate_regeneration`-functies niet `rubbing_damage_perc` te berekenen, maar `rubbing_damage_nr_ha` (geef gerust andere suggestie voor naam).  Van hieruit is een percentage gemakkelijk te berekenen, en je hebt je getallen om je statistiek te doen.  Maar ook de andere beweging (aantal berekenen vanuit percentage) is vrij eenvoudig, dus mss hier best de overweging maken wat het vaakst nodig is.

Bekijk je dit even en laat je weten als er nog iets aangepast moet t.o.v. de huidige situatie?  (Indien niet, dan mag je het issue afsluiten.)

**Comment by leymanan** [comment]
is oK zo
