### ISSUE TITLE
regeneration: number_of_trees_ha - één getal?

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#35]
Momenteel wordt er enkel min_number_of_trees_ha en max_number_of_trees_ha berekend.
Daar hebben  we het al over gehad, en dat  leek het meest correcte.
Maar bij hoogteklasses > 50 cm worden wél exacte aantallen geteld, en dan komt dit heel verwarrend over. Daarenboven krijg je bij create_statistics deze info (per variabele) onder elkaar.

Zouden we toch niet overstappen naar een gemiddelde waarde? Of deze ev. als extra variabele toevoegen? Eventueel als "mean_number_of_trees_ha"?  Of "estim_number_of_trees_ha"? Of gewoonweg "number_of_trees_ha"?

**Comment by ElsLommelen** [comment]
dit is identiek aan issue #21, dus beter het hier terug sluiten voor de overzichtelijkheid
