### ISSUE TITLE
volume per decaystage snags and deadwood

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#45]
blijkbaar worden momenteel enkel de volumes per decaystage berekend voor logs (liggend dod hout) => uitbreiden naar snags en deadwood

conform calculate_logs_decay_plot en calculate_logs_decay_plot_species, maar dan voor snags (staand dood hout) en voor total deadwood (som van snags en logs)

**Comment by leymanan** [comment]
snags: best dead_standing gebruiken als nieuwe naam, zie ook #69

**Comment by leymanan** [comment]
per ongeluk gesloten, sorry!

**Comment by ElsLommelen** [comment]
> conform calculate_logs_decay_plot en calculate_logs_decay_plot_species, maar dan voor snags (staand dood hout) en voor total deadwood (som van snags en logs)

Bedoel je hiermee dat je er een aparte functie voor wil maken?  Ik zie 2 opties:
- deze berekening aan de functies `calculate_logs_decay_plot()` en `calculate_logs_decay_plot_species()` toevoegen (evt. 'log' in naam verwijderen om de lading te blijven dekken), dus hier een extra argument `data_dendro_calc` toevoegen met de gegevens van staand dood hout, zoals in de functies `calculate_dendro_plot()` en `calculate_dendro_plot_species()`.  Voordeel is dat dan alles samen staat in het resultaat (en 2 functies minder), nadeel is dat je `data_dendro_calc` ook nodig hebt om de functie te kunnen gebruiken, zelfs als je enkel resultaten van liggend dood hout nodig hebt.  Tenzij ik opvang dat het niet opgeven van een dataset als resultaat heeft dat bepaalde kolommen niet uitgevoerd worden (of NA geven).  Tenminste... voor zover dit relevant is en niet iedereen gewoon de gegevens uit forresdat haalt.  (In dat geval zou ik gewoon voor deze optie kiezen omdat we er zo het minst een rommeltje van maken voor onszelf.)
- aparte functies voor liggend en staand dood hout.  In dit geval mag je een voorstel geven voor de namen.  En ook: wat doen we voor `calculate_dendrometry()` en de opslag in forresdat?  Voegen we het samen met liggend dood hout in 1 tabel, of behouden we afzonderlijke tabellen?

**Comment by leymanan** [comment]
lijkt me inderdaad beste om de berekening toe te voegen aan de functies `calculate_logs_decay_plot()` en `calculate_logs_decay_plot_species()`, die ik dan zou hernoemen naar `calculate_deadw_decay_plot()` en `calculate_deadw_decay_plot_species()`.

Maar liefst wel met de optie van lege velden als ik bv. dataset logs of standing deadwood niet kan toevoegen.

> * En ook: wat doen we voor `calculate_dendrometry()` en de opslag in forresdat?  Voegen we het samen met liggend dood hout in 1 tabel, of behouden we afzonderlijke tabellen?

Dataframe `logs_by_decay(_species)` hernoemen naar `deadw_by_decay(_species)`, en er een extra kolom `vol_dead_standing_m3_ha` aan toevoegen.

Wat reeds berekend werd ivm `standing_deadw` in `dendro_by_plot` zou ik wel behouden

**Comment by ElsLommelen** [comment]
Voeg ik hier ook records met nulwaarden toe als de plot onderzocht is maar er geen dood hout aanwezig is, of is dat hier niet nodig?

**Comment by leymanan** [comment]
> Voeg ik hier ook records met nulwaarden toe als de plot onderzocht is maar er geen dood hout aanwezig is, of is dat hier niet nodig?

dat mag dezelfde logica volgen als bv. `dendro_by_diam_plot`: één nulwaarde per plot, met NA voor decaystage

**Comment by ElsLommelen** [comment]
Dit zou in orde moeten zijn, check je bij gelegenheid even of het ok is?  (dit issue sluit vanzelf als ik uiteindelijk naar de master merge)
