### ISSUE TITLE
gemiddelde bedekkingen

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#46]
ik blijf de vraag krijgen vanuit het team (net workshop gedaan) om toch **gemiddelde bedekkingen** ook toe  te voegen, en niet enkel min en max van de range. Volgens Kris wordt dat bij de meeste onderzoeken/artikels toch als benaderende variabele gebruikt.

Bij de bedekkingen per soort in de herblayer (vegetatie), is dit reeds beschikbaar.

Het is echter nog niet beschikbaar voor de **vegetatiebedekkingen over de soorten heen** (oa. moss_cover, shrub_cover, trees_cover, ... ).
Zie functies
- "load_data_vegetation": daar naast min/max_cover, ook een mean_cover toevoegen.
- "calculate_vegetation_plot": idem

Ook bij de **regeneration data** wordt enkel gewerkt met een min/max_number_of_trees. Ook daar zou een variabele mean_number_of_trees moeten toegevoegd worden: 
- load_data_regeneration
- calculate_regeneration_plot, calculate_regeneration_plot_height, calculate_regeneration_plot_height_species
- calculate_regeneration_core_area_height, calculate_regeneration_core_area_height_species

**Comment by ElsLommelen** [comment]
grotendeels opgelost,
- voor vegetatie hiervoor issue #91 nog oplossen
- voor regeneration [deze voorgestelde naamaanpassingen](https://github.com/inbo/forrescalc/pull/82#discussion_r678172388) nog uitvoeren

**Comment by ElsLommelen** [comment]
in orde op issue #91 na
