### ISSUE TITLE
biomassa-berekeningen - minder dringend

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#48]
aanvulling bij issue #47

Luc vroeg of biomassa-berekeningen mee konden opgenomen worden in forrescalc.
Ik heb hem gezegd dat dat me niet zo simpel leek.
Ik heb de berekeningen gedaan voor de VBI-data, en er wordt gewerkt met 5 of 6 externe tabellen (in acces-db), die NIET in de fieldmap-db zitten.
Dat is dan een extra "externe" databank waar er vanuit forrescalc naartoe moet genavigeerd worden.
Of extra csv-files in extdata ...

Ik zag immers net dat je dat bij DAS-indicator opving door data in inst/extdata te plaatsen
read_delim(
        system.file("extdata/DAS_tree_groups.csv", package = "forrescalc"),
        delim = ";", col_types = "cd"
      ),

Dus wellicht is dat niet zo moeilijk, maar vraagt toch wat programmeerwerk.
Ik kan je alvast de scripts aanleveren, die ik gebruikt heb bij de VBI-berekening.

**Comment by ElsLommelen** [comment]
Wat moet ik me voorstellen bij die externe tabellen?
- Zijn dat algemeen geldende waarden zoals de Ellenbergwaarden, of zijn ze specifiek voor bepaalde reservaten of bomen en dus rechtstreeks gekoppeld aan de opgemeten fieldmap-gegevens?
- Zijn die ook ergens anders beschikbaar zoals de Ellenbergwaarden?
- Zijn ze vast of kunnen ze veranderen in functie van de tijd?
- Over hoeveel data gaat het ongeveer (rijen en kolommen)?
- ...

Enfin, de exacte situatie bepaalt toch een beetje wat voor die gegevens de beste aanpak zou zijn, dus graag bij gelegenheid wat meer uitleg hierover.  Het script is uiteraard welkom, maar mss het gemakkelijkst om eerst uit te klaren wat we met die brondata aanvangen?  (Dan kan dit meteen juist toegevoegd worden in het script.)

**Comment by leymanan** [comment]
- Dat zijn eerder algemeen geldende "waarden", oa wood densities en tarieven en ..., wel specifiek per boomsoort
- Die zijn nergens anders beschikbaar (ik heb ze doorgekregen van Wallonie en heb de vertaling gedaan naar bms-enlijst van de VBI; moet nog gebeuren voor de bms-enlijst van de bosreservaten)
- Die zouden kunnen veranderen in de tijd, in die zin dat we misschien op termijn kiezen voor andere densiteiten, of andere ...., maar eigenlijk is het eerder dat er dan een andere tabel bij zal komen
- op dit moment zijn dat 7 tabellen in een access-db van 1.8 Mb

**Comment by leymanan** [comment]
ik heb een script geschreven waarin ik die biomassa-berekeningen gedaan heb, volgens mij is dat voldoende.
Moet niet mee opgenomen worden in forrescalc, is te specifiek.
