### ISSUE TITLE
extra FM-berekeningen overnemen in R

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#59]
Doel is om zoveel mogelijk van dataverwerking in R te doen, en een minimum in FieldMap.
In FieldMap dan enkel nog:
- aanmaak hoogtemodellen (DH-curves)
- berekening deadwood volume: CalcVolume_m3 en CalcLength_m (afgesneden binnen de cirkel)

**Zie ev. als voorbeeld "tmp_load_data_123eSET_NGV_BerekendInR.Rmd", daarin heb ik alle berekeningen eens gedaan.**

In de load_data-functies dan volgende berekeningen opnemen:
**Algemeen dendro**
- tree_number
- individual
- CalcHeight obv hoogtemodellen (per species, forest_reserve, periode, plottype en ev. per plotid):  "Hoogtemodellen.zip" geplaatst in gdrive-folder ...\PRJ_BOSECO_ALGEMEEN\PRJ_BR_VisualisatieResultaten\Werkruimte 
- basal_area_m2
- volumes obv tarieven gebaseerd op CalcHeight (tarieven zie "tblTariefgroepBoomsoort" in comb met "tblTarieven_2ing" & "tblTarieven_1ingKroon" in "BR_ExterneData.accdb", ook in gdrive geplaatst):
--  vol_tot_m3 
-- vol_stem_m3 (!! snag)
-- vol_crown_m3 (+ correctie voor uitgebroken kronen/afgebroken takken)
-- Hakhout ev. op spilniveau én tarief met twee ingangen als hoogtemodel beschikbaar, indien niet, dan tarief met één ingang

**Specifiek voor hakhout**
- dbh_mm (berekend voor hakhout als "gemidelde" van de spillen - gemiddelde zodat grondvlak cte is)
- decaystage (berekend voor dood hakhout: gewogen gemiddelde obv grondvlak van de spillen)

**Deadwood**
- CalcLength_m as calc_length_m (cfr CalcVolume_m3): dat is de afgesneden lengte binnen in de plot
- max_diam_mm obv onderliggende tabel "Deadwood_2eSET_Diameters" en "Deadwood_Diameters"
- min_diam_mm extra toevoegen: ook obv onderliggende tabel
- total_length_m extra toevoegen: ook obv onderliggende tabel
- TreeNumber van deadwood: NEE ,niet meer nodig, gaan we verwijderen

**Comment by leymanan** [comment]
volgende variabelen moeten bijgevolg standaard mee ingeladen worden bij load_data_dendrometry:
        Trees.Calcheight_m AS calc_height_m, 
        Trees.IntactSnag AS intact_snag,
        Trees.CrownVolumeReduction AS crown_volume_reduction,
        Trees.BrancheLengthReduction AS branche_length_reduction

En dus niet meer als "extra_variables"

**Comment by leymanan** [comment]
ik heb zelf al in een tijdelijke file deze zaken berekend: zie in leymanan/forestreserves, script "Validatie/temp_load_data_123eSET_NGV_BerekendInR.Rmd" en "ExtraFunctions_Volume.R"

Want er zijn wel wat extra's:
- Individual = 1, behalve bij opgroeiende spillen (ind_sht_cop = 11)
- volume crown (en bijgevolg ook vol_tot): bijwerken obv velden CrownVolRedu en BranchLenghtReduction
- volume snag als kegel of cilinder?

**Comment by ElsLommelen** [comment]
Je geeft aan om die berekeningen toe te voegen aan de `load`-functies, maar al bij het eerste item (`tree_number`) merk ik dat dat een probleem is: om die te berekenen, heb je eigenlijk de combinatie van 'shoot' data en 'dendro' data nodig, dus het resultaat van `compose_stem_data()`.  En strikt genomen zijn het ook berekeningen (die net iets verder gaan dan het louter interpreteren van de variabelen wat in de `load`-functies gebeurt: jaartal afleiden uit datum,...).  Ik zou daarom voorstellen om die berekeningen in een aparte functie te steken, of aparte functies, die gemakkelijkheidshalve ook toegevoegd wordt in de paraplu-functie `calculate_dendrometry()`.  Het apart beschikbaar stellen van die functies biedt ook het voordeel om ze (als nodig) te gebruiken om de berekeningen op andere gegevens uit te voeren.

Heb je een voorstel voor een naam voor deze functie(s)?  Iets als `calculate_treedata_dendro()` of `precalculate_dendro()`?  Ik zou het ook kunnen opsplitsen in meerdere functies, maar voor elke waarde een functie lijkt me zeer onhandig (veel te veel verschillende functies maakt het package onoverzichtelijk, en ook onhandig als je ze allemaal moet aanroepen om je data klaar te maken voor verwerking).

**Comment by leymanan** [comment]
ja, is goed idee om dat in andere functie te stoppen!
? naam:`calculate_treedata_dendro()` vind ik verwarrend, want wat wordt dan juist berekend? 
`precalculate_dendro()` vind ik dan beter
Of eventueel iets in genre van `calc_variables_tree_level()`?
En dan ook `calc_variables_deadwood_level()`?

Is nog maar een idee ...

**Comment by ElsLommelen** [comment]
Klinkt goed.  Zou je 'calc' afgekort gebruiken, of voluit schrijven zoals bij de andere functies?  (Of zou je ze op termijn liever allemaal afgekort hebben?)

(Ik zal ze voorlopig zo noemen, bij een beter idee pas ik het wel aan.)

**Comment by leymanan** [comment]
ik weet het niet goed: als je calculate pakt, wordt het direct weer zo lang ...
Maar anderzijds zou ik de andere functienamen ook niet direct veranderen ...
Alhoewel misschien wel sneller getypt ... (ik weet dat je dat niet voluit moet typen, maar als je meerdere keuzes hebt moet je toch al tot calculate_xxx komen, om met een eerste letter het vervolg te kiezen ;-) )

Eigenlijk heb ik geen uitgesproken voorkeur, voor allebei is iets te zeggen ;-)

**Comment by ElsLommelen** [comment]
Ok, ik zal voorlopig de afkorting gebruiken voor de nieuwe functies, en de rest laten zoals het is.  Dan kan je ze tenminste al gebruiken, en dan zien we achteraf wel.  Evt. kan je het terugkoppelen met je team.

**Comment by ElsLommelen** [comment]
In verband met `individual`: kan `ind_sht_cop` andere waarden aannemen dan 10, 11 of 12, en welke waarden zouden dit dan zijn?  (In je  berekening zou `individual` in dat geval NA moeten zijn, maar je berekening gaat bv. het feit dat `ind_sht_cop` NA zou zijn, niet opvangen, vermoed ik.)

En ook: staat 0/1 voor FALSE/TRUE?  Dan zou je kunnen overwegen om het ook zo te benoemen (duidelijker en gemakkelijker in berekeningen).

**Comment by leymanan** [comment]
individual: 0/1 = F/T => idd beter zo benoemen! Goed idee!

ind_sht_cop: enkel die drie waardes mogelijk (is een lookuplijst); zou altijd ingevuld moeten zijn (toch zeker na datacontrole ... ;-) )

**Comment by ElsLommelen** [comment]
Enkele vragen i.v.m. `basal_area_m2` en volumes:
- is er een reden dat je `varNameDiameter` en `varNameHeight` gebruikt?  Neem ik het best zo over, of kan ik verder gaan op de namen die in data_dendro gebruikt zijn?
- die tarieven die uit een externe databank opgehaald worden, moet dit zo blijven, of stellen we de opgehaalde tabel beter beschikbaar in het package zelf?  (Een optie is dat we het script om deze op te halen, ook stockeren in het package, en dat dit indien nodig gerund kan worden om de in het package beschikbare tabel te updaten.)  Voordelen voor het beschikbaar stellen, is dat de gebruiker geen gedoe heeft om zelf die gegevens te gaan zoeken, en bij een update gaat het ook transparant zijn wat aangepast wordt.  Als de gegevens vaak veranderen, is dit onderhoud weer een nadeel.
- als de tabel in het package zelf toegevoegd wordt: in hoeverre is het nodig/wenselijk dat een gebruiker toch nog een eigen tabel kan gebruiken hiervoor?  (M.a.w. moet hij dit ook als parameter kunnen ingeven bij de functie, of gebeurt het ophalen intern in de functie?)
- behoud je graag een aparte functie voor deze berekening, of mag de code toegevoegd worden aan `calc_variables_tree_level()`?

**Comment by leymanan** [comment]
- is er een reden dat je `varNameDiameter` en `varNameHeight` gebruikt? NEE
- tabellen mogen beschikbaar gesteld worden in het package zelf, als dat kan is dat inderdaad wel handig! Deze veranderen bijna nooit ...
- gebruiker moet geen eigen tabel kunnen inladen, zijn vrij strikte tarieven. Maar er moet wel mogelijkheid zijn dat ik bij ev. aangepaste tarieven die makkelijk kan inladen (ev. met optie die je voorstelt : _optie is dat we het script om deze op te halen, ook stockeren in het package, en dat dit indien nodig gerund kan worden om de in het package beschikbare tabel te updaten_
- mag toegevoegd worden aan ´calc_variables_tree_level`

**Comment by leymanan** [comment]
zou hééél handig zijn dat dat in package zelf komt!! Bedankt om dit voor te stellen!

**Comment by ElsLommelen** [comment]
Ok, en nu de vragen over de berekeningen zelf:  ;-)
- in de hoofdfunctie wordt voor de volumeberekening enkel nIngang = 2 gebruikt, maar bovenaan in het issue lees ik dit:

> * -- Hakhout ev. op spilniveau én tarief met twee ingangen als hoogtemodel beschikbaar, indien niet, dan tarief met één ingang

Hoe controleer ik of dit hoogtemodel beschikbaar is?  Is dit als calc_height_R niet NA is, of zit er dan ook geen calc_height_m in fieldmap?

- i.v.m. `crown_volume_reduction` en `branch_length_reduction`: we lezen hiervan de ID in, maar zou het niet beter zijn om de waarde (value3) rechtstreeks in te lezen bij `load_data_dendrometry()`?  Of als alternatief: het tabelletje toevoegen in het package, zodat het gemakkelijk beschikbaar is.

**Comment by leymanan** [comment]
- i.v.m. crown_volume_reduction` en `branch_length_reduction` : lees maar direct de waarde in (ik veronderstel dat dat niet veel zwaarder is dan de ID ;-)  ; Tabelletje toevoegen in package mag  ook, wat jou het beste lijkt.

**Comment by leymanan** [comment]
ivm volumeberekening:

**Beetje duiding** 
- op dit moment wordt het volume op niveau van de trees layer berekend (in FM-IA): obv gemiddelde dbh, CalcHeight_m en aantal spillen
- correcter is om het volume op spilniveau (layer shoots) te berekenen (zeker wat betreft het volume per diameterklasse)
- In FM-IA kan dat echter niet (enkel op niveau van trees layer mogelijk) én ook CalcHeight kan enkel opgeslagen worden in layer Trees
- In R kan dat wel allemaal, maar moet ik wel een hoogtemodel (aangemaakt in FM-IA) hebben  => te gebruiken voor berekening van een CalcHeight in trees én shoots layer

**Stand van zaken:**
- ik ben bezig alle hoogtemodellen aan 't opkuisen en samenzetten; dat is reeds OK voor een 8-tal bosreservaten (CP's) (Kluisbos, Kolmont, Liedekerke, ...) (vraagt nog wat werk, zeker bij de bosreservaten die al langer geleden verwerkt zijn)
- indien hoogtemodellen beschikbaar zijn, is het aan te raden deze te gebruiken, zelfs al staat er een waarde in het veld CalcHeight_m (dat veld is alleen maar leeg bij de meest recent verwerkte bosreservaten) 
- voor de andere (verwerkte!!) bosreservaten waar ik de hoogtemodellen nog niet opgekuist heb, zit er in het FM-project reeds een berekende CalcHeight, maar enkel op niveau van layer trees, niet op niveau van de onderliggende shoots ==> daar zou ik tijdelijk tarief met 1 ingang gebruiken voor de shoots en tarief met 2 ingangen voor de individuele bomen
- en dan is er nog een deel bosreservaten (of periodes van een bepaald BR) die niet verwerkt zijn, en waar dus CalcHeight_m overal NA is, en er ook geen hoogtemodellen beschikbaar zijn ==> daar kan nu nog geen volume berekend worden

**Wanneer hoogtemodel beschikbaar?**
Dat staat los van het al dan niet ingevuld staan van calc_height_m.
Ik heb een lijst van hoogtemodellen op gdrive geplaatst (https://drive.google.com/drive/folders/1-GBhYJJ-GBYpRmhjKLEHzgMYrXB_2TAA?usp=sharing)
In R heb ik gebruik gemaakt van code
`list_heightmodels <- list.files(path = path_to_height_models, pattern="xlsx", all.files=FALSE,
    full.names=FALSE)`
en dan al deze files aflopen en de p1, p2 en type functie (exp of log of ...) per boomsoort, per bosreservaat en per periode samenvoegen.
Is beetje ambachtelijk, maar werkte wel
Ik ben er zeker van dat jij veel elegantere oplossingen weet ;-)

**Comment by ElsLommelen** [comment]
In verband met die elegantere oplossing: is er een reden dat er voor elk BR een apart bestand is?  Alles in 1 tabel zou het al een beetje minder ambachtelijk maken.  En dan afhankelijk van hoe vaak die cijfers veranderen, een keuze maken voor waar dit opgeslagen kan worden.  Voorlopig heb ik dit hoogtemodel beschouwd als een externe tabel die een gebruiker toevoegt, maar als dit niet of zelden verandert en expliciet deel is van de berekeningen, zoals de tarieven, dan kan dit uiteraard ook een interne tabel worden.

Ik zie dat niet elk BR hetzelfde model bevat, terwijl ik in de code wel maar 1 model zag.  Is het zinvol om evt. het model uit de tabel in te lezen en toe te passen?  Waarschijnlijk gaat het dan wel wat herschreven moeten worden om het codematig niet te complex te maken.  Of gaat het bv. maar om 2 modellen?  Dan is het gemakkelijker om een variabele toe te voegen die aangeeft welk model toegepast moet worden.

Dus voor de volumes stel ik de volgende code op?
- als calc_height berekend kon worden via een hoogtemodel, bereken ik het volume volgens tarief met 2 ingangen
- als calc_height zo niet berekend kon worden en niet NA is, neem ik dit uit FM en bereken ik het volume volgens tarief met 1 ingang
- als calc_height NA is, is volume ook NA (het zou volgens de formule van tarief met 1 ingang wel berekend kunnen worden, lijkt mij)

Ah, en die calc_height en volume moet dus berekend worden op shoot-niveau, niet op tree-niveau, en dan geaggregeerd?  Hoe moet die calc_height dan geaggregeerd worden?  (Volume is som nemen, dat is logisch.)

**Comment by leymanan** [comment]
**Ivm hoogtemodellen**

- voor elk BR een apart bestand: zo wordt dat aangemaakt in FM-IA: apart voor elke BR en elke periode, wordt gradueel verder aangevuld
- Alles in één bestand: in mijn R-code wordt er één bestand van gemaakt en dan gebruikt, makkelijker dan telkens één centrale file aan te vullen, want dat zou dan toch weer een kopie zijn van .... (en als er dan aanpassingen nodig zijn maakt dat alles complexer.
- Er zijn inderdaad meerdere modellen mogelijk. Ik dacht dat ik in mijn code een onderscheid gemaakt had mbv een ifelse obv de variabele `Model`
Maar ik zie inderdaad enkel `calc_height_R = 1.3 + P1 + P2*log(dbh_mm/10)`, staan
en in ander script `calc_height_R = 1.3 + exp(P1 + P2/(dbh_mm/10))
- Normaal gesproken blijft het beperkt tot één van deze twee modellen.
- Interne tabel: ik ga nog wel een tijdje bezig zijn om deze hoogtemodellen gradueel bij te werken. Deze tabellen zijn totaal anders dan de tarieven op dat vlak, zijn veel minder vast. Dus misschien toch houden op een externe tabel? (toch voor komend jaar)

**Ivm volumes**

- als calc_height berekend kon worden via een hoogtemodel, bereken ik het volume volgens tarief met 2 ingangen - **OK**
- als calc_height zo niet berekend kon worden en niet NA is, neem ik dit uit FM en bereken ik het volume volgens tarief met 1 ingang - **NEE, tarief met 2 ingangen, maar Calc_Height uit FM**
- als calc_height NA is, is volume ook NA (het zou volgens de formule van tarief met 1 ingang wel berekend kunnen worden, lijkt mij) - **NEE, dan tarief met één ingang gebruiken**

- volume idd berekenen op shoot-niveau en dan aggregeren (som) op tree-niveau (uiteraard enkel voor het hakhout, `ind_sht_cop ==12`)
- height: moet niet geaggregeerd worden: daar mag je calc_height uit trees layer overnemen (berekend obv gemiddelde dbh en het hoogtemodel) of - als model nog niet beschikbaar - calc_height uit FM

Hopelijk een beetje duidelijk zo?
Bedankt!

**Comment by ElsLommelen** [comment]
> * als calc_height zo niet berekend kon worden en niet NA is, neem ik dit uit FM en bereken ik het volume volgens tarief met 1 ingang - **NEE, tarief met 2 ingangen, maar Calc_Height uit FM**

Ah ja, oeps, hier moet ik enkel tarief met 1 ingang gebruiken als het over hakhout met meerdere shoots gaat, niet?

> * Er zijn inderdaad meerdere modellen mogelijk. Ik dacht dat ik in mijn code een onderscheid gemaakt had mbv een ifelse obv de variabele `Model`
>   Maar ik zie inderdaad enkel `calc_height_R = 1.3 + P1 + P2*log(dbh_mm/10)`, staan
>   en in ander script `calc_height_R = 1.3 + exp(P1 + P2/(dbh_mm/10))`

Is er iets anders dan de kolom 'Model' waarvan ik kan afleiden welk model toegepast moet worden?  Of check ik best op de aanwezigheid van `ln` of `exp` in deze formule?

**Comment by leymanan** [comment]
- idd enkel tarief met één ingang bij hakhout

- enkel in variabele `Model` te zien, dus ev. daar inderdaad checken op de aanwezigheid van `ln` of `exp` in de formule.

**Comment by ElsLommelen** [comment]
Ik ben toch nog op een vraagje uitgekomen: moet het kroonvolume berekend worden op basis van de shoots, of van de trees?

**Comment by leymanan** [comment]
obv shoots net als het stamvolume

Op wo 5 mei 2021 15:23 schreef ElsLommelen ***@***.***>:

**Comment by ElsLommelen** [comment]
Voor de berekeningen van deadwood vraag ik me af of het nodig is om hiervoor een extra functie `calc_variables_deadwood_level()` te maken:
- die 2 extra variabelen die uit tabel Deadwood_Diameters komen, kunnen mss beter meteen in `load_data_deadwood()` opgehaald worden (dit bespaart een connectie met de databank, en veel combineerwerk)
- `max_diam_mm`, `min_diam_mm` en `total_length_m` zijn amper rekenwerk te noemen, dus dat kan ook eventjes meegenomen worden in `load_data_deadwood()`
- `calc_length_m` is nog een beetje onduidelijk voor mij.  Als het idee is om die berekening via tarifering te doen, is dat wel iets meer rekenwerk, en dan gaat het mogelijk ook niet lukken om de aggregaties tot boomniveau te doen in `load_data_deadwood()` en op basis van de output hiervan `calc_length_m` te berekenen in de nieuwe functie `calc_variables_deadwood_level()`...  Dus op basis daarvan zal dan de keuze gemaakt moeten worden of het al dan niet in `load_data_deadwood()` kan gebeuren.

Wat denk jij?
Voordelen om alles in `load_data_deadwood()` te steken, lijken mij:
- gebruiksgemak (1 functie die gebruiksklare gegevens aanlevert, minder functies nodig om het hele traject te doorlopen)

Voordelen om voor een aparte functie `calc_variables_deadwood_level()` te kiezen, lijken mij:
- transparantie over de stappen die gebeuren
- de functie voor de berekeningen is apart beschikbaar

Er is ook nog de optie dat we een functie `calc_variables_deadwood_level()` maken die in de functie `load_data_deadwood()` gebruikt wordt, dan combineer je een beetje de voordelen van beide opties.  ;-)

**Comment by leymanan** [comment]
`calc_variables_deadwood_level()` is er volgens mij ingeslopen naar analogie met `calc_variables_tree_level`
Zijn idd maar weinig variabelen, dus hoeft voor mij geen afzonderlijke functie te zijn.

Maar als we toch kiezen voor een afzonderlijke functie, dan zou ik die wel implementeren in `load_data_deadwood()`.
?Is dat ook geen optie voor de functie `calc_variables_tree_level()`: implementeren in `load_data_dendro()` ?

Wat betreft ` calc_length_m`: dat is een variabele die in FM berekend wordt, en dus 'as is' geïmporteerd wordt in R. Dat slaat op de lengte van het dood hout fragment binnen de plot.

**Comment by ElsLommelen** [comment]
Ah, ok, dan lijkt `calc_variables_deadwood_level()` me helemaal niet nodig, en dan zal ik die extra variabelen toevoegen aan `load_data_deadwood()`.
Voor `calc_variables_tree_level()` is dat minder evident: die gebruikt behalve de gegevens uit `load_data_dendrometry()` ook gegevens uit` load_data_shoots()` na bewerking door de functie `compose_stem_data()`.  Op zich is het uiteraard wel mogelijk om dit alles in 1 'gebruikers'functie te groeperen, maar gezien de lengte van de huidige functies zullen er wel hulpfuncties moeten blijven.  Ik zal dit eens bekijken en een voorstel formuleren.  En dan kan je nog kiezen in hoeverre de hulpfuncties voor gebruikers beschikbaar moeten zijn.  Ik stel voor om dat ook achteraf eens te bekijken, eerst zorgen dat alles werkt en je het kan gebruiken.

**Comment by leymanan** [comment]
klein foutje nog bij functie `load_data_deadwood`:
...
 summarise(
      max_diam_mm = max(.data$diam_mm),
      min_diam_mm = min(.data$diam_mm),
      **total_length_m = sum(.data$length_m)**

total_length_m moet gelijk zijn aan **max** ipv sum(.data$length_m)

**Comment by leymanan** [comment]
heeft enkel invloed als er meer dan 2 tussenmetingen zijn, maar komt wel voor.
Sorry!
