### ISSUE TITLE
regeneration: number_of_trees obv heightclass

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#61]
De keuze voor het gebruik van reg_number of number_class laten afhangen van heightclass:
- als subcircle A1 (lage hoogteklasses): dan kiezen voor number_class, behalve mocht dit veld leeg zijn, dan reg_number gebruiken
- als A2, dan net omgekeerd

**Comment by leymanan** [comment]
ik zag ook dat bij functie "load_regeneration" nog enkele hoogteklasses misten (6000, 7000, 8000 waren nog niet toegevoegd):

subcircle =
        ifelse(
          .data$height_class %in% c(3000, 4000, **6000, 7000, 8000**),
          "A2",
          ifelse(
            .data$height_class %in% c(1000, 2000, 5000),
            "A1",
            NA_character_
          )

**Comment by ElsLommelen** [comment]
Na het oplossen van issues #21 en #46 en de discussie [hier](https://github.com/inbo/forrescalc/pull/82#discussion_r678172388) lijkt me dit issue niet meer van toepassing?  (Die extra `height_class` lijken eerder al toegevoegd, geen idee meer wanneer.)

- `reg_number` & `number_class`: zowel in A1 als A2 zijn er aantallen gescoord als klassen, dus we kunnen voor A2 niet kiezen om de gegevens op te slaan in 1 variabele met 1 getal (zie discussie waar hierboven naar verwezen is).
- we hebben daarom uiteindelijk toch gekozen om `reg_number` (hernoemd als `nr_of_regeneration`) en `number_class` (met klassegrenzen `min_number_of_regeneration` en `max_number_of_regeneration` en midden `mid_number_of_regeneration`) te gebruiken zoals in de databank, en dit op te splitsen in `nr_established` en `nr_seedlings` (of gerelateerde klassen) van zodra meerdere hoogteklassen samengevoegd worden in een `calculate_regeneration`-functie.  Voor die opsplitsing gebruik ik de subcirkels, dus dit komt in feite overeen met wat je vraagt.  En waar gegevens per hoogteklasse uitgevoerd worden, kan je die opsplitsing als gebruiker zelf maken.

Check je eens of hier nog iets nodig is?
