### ISSUE TITLE
Extra 0-waardes obv survey_trees én data_processed

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#63]
Het is onpractisch om nulwaarden te gaan toekennen aan dendro_by_plot_by_species, omdat je dan voor elke soort een nulwaarde moet toekennen, idem dito voor diam_klasses.

MAAR het zou ev. wel kunnen bij de meest algemene output-files: dendro_by_plot, deadw_by_plot, veg_by_plot, reg_by_plo: daar obv survey_trees/deadw/veg/reg e,n data_processed (te vinden in "plotinfo") zorgen dat elke plot die processed is mee opgenomen is, met ev. nulwaardes als er geen trees/deadw/veg/reg is.

**Comment by leymanan** [comment]
Bv. plot 475: geen bomen in periode 1

**Comment by leymanan** [comment]
bij regeneration en vegetation wordt dat al opgevangen, omdat er daar een subplotID wordt aangemaakt zodra er een opname is

**Comment by ElsLommelen** [comment]
Ik kwam toevallig net de functie `add_zeros()` tegen, in hoeverre voldoet die voor dit issue?  Ik denk dat we ooit al eens de bedenking gemaakt hadden dat we het niet echt zinvol vonden om voor alle nulwaarden records in forresdat op te slaan, en ik vermoed dat de functie `add_zeros()` gemaakt is om die toch gemakkelijk te kunnen toevoegen.

Ik heb nog niet in detail gekeken hoe realistisch het is, maar misschien zou het een piste kunnen zijn om in `read_forresdat()` een argument `add_zeros` (met mogelijke waarden TRUE en FALSE) toe te voegen?  Lastige gaat waarschijnlijk zijn dat dit generiek geschreven moet worden en dat er dus ergens info zal moeten zijn over welke variabelen als groeperende variabelen beschouwd moeten worden, en wat de nulwaarde precies moet zijn voor de variabelen die niet numeriek zijn.

Ik zal dit binnenkort nog bekijken en een concreet voorstel maken, bovenstaand tekstje is vooral als nota voor mezelf.  Tenzij je aangeeft dat `add_zeros()` volstaat, uiteraard.  ;-)  In dit geval zou in de documentatie van `read_forresdat()` best staan dat er geen nulwaarden toegevoegd zijn, en verwijzen naar `add_zeros()` om die toe te voegen voor de gegevens die ze effectief gebruiken...

**Comment by leymanan** [comment]
> Tenzij je aangeeft dat `add_zeros()` volstaat, uiteraard. ;-) In dit geval zou in de documentatie van `read_forresdat()` best staan dat er geen nulwaarden toegevoegd zijn, en verwijzen naar `add_zeros()` om die toe te voegen voor de gegevens die ze effectief gebruiken...

Voor mij is dat zo voldoende.
En voor zekerheid bij documentatie van `read_forresdat` vermelden dat er geen nulwaardes toegevoegd zijn. Goed idee!
Ik denk dat dat zo het veiligste is. Afhankelijk van meetvraag moeten nullen toegevoegd worden of niet, ik zou dat niet in `read_forresdat `bij stoppen.

**Comment by ElsLommelen** [comment]
Vermelding is toegevoegd, maar ik denk dat we dit best nog eens grondig bekijken samen met issue #64, want bij mijn weten is er nergens rekening gehouden met survey_xxx voor het toevoegen van 0 vs. NA.  Dus we zouden er minstens voor moeten zorgen dat `add_zeros()` hier rekening mee houdt bij het toevoegen van records, en mss is het wel een optie om in enkele kortere tabellen de nulwaarde-records toe te voegen in `read_forresdat()` (en dan in het andere geval een warning geven dat de records met nulwaarden niet toegevoegd zijn)?  Dan staan ze niet in de databank, maar anderzijds krijgt de gebruikers ze wel bij het opladen van de gegevens.

**Comment by ElsLommelen** [comment]
Intussen worden de records default niet meer geladen als survey_xxx != 10, dus in principe is dat ok.  Ik ga wel voor de zekerheid even bij `add_zeros()` de functionaliteit toevoegen om een kolom met TRUE/FALSE te kunnen toevoegen die aangeeft of waarden 0/NA moeten toegevoegd worden.  Voorlopig dus niet nodig voor dit en gerelateerde issues, maar je weet nooit waarvoor het ooit nuttig is.

**Comment by ElsLommelen** [comment]
Voila, ik heb bij het inladen van de data ook even een warning toegevoegd dat nulwaarden ontbreken, want niet iedereen kijkt in de help en dit is toch belangrijke info voor de gebruiker van de data, lijkt mij.  (Ik heb er een warning van gemaakt omdat messages standaard afgezet kunnen worden, en ook heel gemakkelijk over het hoofd gezien kunnen worden bij bv. het runnen van een Rmd).

@leymanan ik neem aan dat dit voldoende is voor dit issue?  Kan je even checken of de teksten duidelijk geformuleerd zijn?  En evt. die nieuwe functionaliteit van `add_zeros()` testen (is uitleg hierover duidelijk, en ik weet niet of de naam van het argument `add_zero_no_na` goed gekozen is)?

**Comment by leymanan** [comment]
Is voor mij voldoende!

**Comment by leymanan** [comment]
ik heb net de functie eens getest om een plot toe te voegen aan dendro_by_plot (met `survey_trees `als `add_zero_no_na`), en blijkbaar worden toch plots toegevoegd waar survey_trees = FALSE is ... (ik dacht immers dat dat een logische variabele zou zijn om onderscheid te maken tss 0 en NA.

```
dendro_by_plot_ <- add_zeros(dataset = dendro_by_plot %>% select(-contains(c("reg", "veg")), -survey_deadw, - data_processed)
                             , comb_vars = c("plot_id", "period")
                             , grouping_vars = c("plottype", "forest_reserve")
                             , add_zero_no_na = c("survey_trees")
                             )
  
nrow(dendro_by_plot)  - nrow(dendro_by_plot_)
dendro_by_plot_ %>% anti_join(dendro_by_plot, 
                              by = c("plot_id", "period", "plottype", "forest_reserve"))

```
MAAR daar zitten ook plots bij die niet opgenomen zijn in periode 1 ...
Logisch wanneer ik de functie in detail bekijk, want de combinatie `plot`, `periode `en `survey_trees ` zit niet in de tabel voor  de ontbrekende periode, dus kan `survey_trees `niet correct zijn.

Het komt erop neer, dat als ik de uitleg mbt de functie lees, ik dit op deze manier zou doen, en denken dat het correct is.
Maar dan worden dus ook de plots toegevoegd waar geen opname in gebeurd is (geen opname in periode 1, maar wel in periode 2).

In theorie zou de functie de nullen die toegevoegd worden, nog eens moeten aftoetsen aan survey_trees/deadw/reg/veg (afhankelijk van de situatie).
MAAR ik denk dat ons dat veel te ver zou leiden.

Het lijkt me makkelijker om na gebruik van de functie de records weg te filteren waar survey_trees/deadw/reg/veg FALSE is.
EVENTUEEL dit als melding weergeven: "check survey_trees/deadw/veg/reg for zeros addes: if FALSE zeros should be removed" 

Wat betreft `dendro_by_plot`: ik voeg nullen wel gewoon toe obv plotinfo. Daar hoeft de functie `add_zeros `niet speciaal voor aangepast worden.

**Comment by ElsLommelen** [comment]
Ik neem aan dat dit intussen opgelost is, of minstens een heel stuk verbeterd?  Kan jij dit bij gelegenheid nog eens grondig testen?  En test vooral de functie `add_zeros()` met allerlei datasets op de manier dat je denkt dat ze ooit nuttig voor je zou kunnen zijn (of voor imaginaire gebruikers van de bosreservatendataset).  Die functie kan in veel situaties nuttig zijn, dus ze mag wel wat robuust zijn, lijkt mij.  (Dus enerzijds geen rare resultaten of rare foutmeldingen geven, anderzijds duidelijke foutmeldingen geven als je iets fout doet.)

**Comment by ElsLommelen** [comment]
Ah, nog een extra vraagje: ik zie in de titel van dit issue ook `én data_processed` staan, moet die ook overal toegevoegd worden als ik check op `survey_trees`?  En enkel bij `survey_trees`, of ook bij `survey_deadw` en andere?

**Comment by leymanan** [comment]
even getwijfeld, maar laat dat maar zo.
Er is immers de optie om bij `load_data_xxx()` enkel de processed data in te laden.
Dat is voldoende.
`Processed `wordt immers pas op TRUE gezet wanneer alle "surveys" verwerkt zijn, en soms wil ik wel al data verwerken van bv. vegetation terwijl de trees nog niet verwerkt zijn.

**Comment by ElsLommelen** [comment]
Ok, dan laat ik het zo.  Dus bij deze is dit issue dan afgehandeld?
