### ISSUE TITLE
survey_deadw = 20 (geen deadwood opgemeten)

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#64]
op dit moment is dit enkel het geval bij KV Kerss (plotid 11.000), en wordt dit scriptmatig in de main opgevangen.
Maar het zou properder zijn,  mocht dit meegenomen worden in de calculate_xxx functies.

Als survey_deadwood = 20, dan alles mbv deadwood = NA ipv 0.
Als survey_trees = 20, dan alles mbv levende bomen = NA ipv 0 
!! dit laatste komt op dit moment niet voor: als er een deadwood-opname is, is er ook een trees-opname => misschien overkill?!

Bij reg en veg zou ik deze voorwaarde wél willen toevoegen, opdat zo het - per ongeluk - aanmaken van een "lege" subplotid, waar géén data verzameld is, wordt opgevangen.
Dus daar: als survey_reg = 20, dan alles NA ipv '0'.
en als survey_veg = 20, dan alles NA ipv '0'.

**Comment by ElsLommelen** [comment]
> !! dit laatste komt op dit moment niet voor: als er een deadwood-opname is, is er ook een trees-opname => misschien overkill?!

Verwacht je dat dit in de toekomst zou kunnen voorkomen?
In elk geval lijkt het me veiliger om dit toch te implementeren als de variabele `survey_trees` bestaat.  Want als het bestaat, is er kans dat het ooit gebruikt gaat worden...  Als je verwacht dat dit nooit nodig gaat zijn (en dus stelt dat bomen opmeten echt wel het minimum is dat verwacht wordt als een nieuwe meetperiode opgestart wordt voor een plot/KV), dan kan je beter geen variabele `survey_trees` aanmaken, of geen optie 20 voorzien.  Enfin, dus beter voorzichtig zijn en dit toch maar implementeren, het is tenslotte maar een regeltje code...
(Moest je het ooit nodig hebben: voor iets zeer complex wat je mogelijk nooit nodig gaat hebben, is de beste strategie om ervoor te checken, en een error te gooien als je toch in de situatie terechtkomt.  In het beste geval komen jij of de gebruikers van het package nooit bij die error uit, en als het toch het geval is, zoek je dan naar een oplossing.)

Enfin, ik neem aan dat ik het hier gewoon even implementeer?

**Comment by ElsLommelen** [comment]
Ik heb intussen issue #58 opgelost, dat bij load-functies enkel records met `survey_xxx = 10` selecteert als `processed = TRUE` (default).  Dan zijn wel de records weg en niet NA, maar ik neem aan dat dit misschien zelfs gemakkelijker is voor dit issue?
