### ISSUE TITLE
aanpassen naam functies

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#67]
om duidelijker te maken waar functie voor dient (minder verwarring)
- compare_periods --> compare_periods_per_plot
- create_overview_status --> create_unique_tree_id

**Comment by leymanan** [comment]
@ElsLommelen: kan ik dat ook zelf doen? 
Gewoon de r-file hernoemen en de functie erin?
Of houdt dat nog meer in?

**Comment by ElsLommelen** [comment]
Euh, eventueel ook andere plaatsen waar die namen gebruikt zijn, dus zeker goed zoeken met ctrl-shift-f dat je alles aangepast hebt (en Rd-files niet rechtstreeks aanpassen, maar hiervoor nieuwe build doen).

En een ander aandachtspunt: best het hernoemen van de file als een aparte commit doen, want als je de aanpassing van de filenaam en de inhoud in dezelfde commit steekt, kan je achteraf niet meer gemakkelijk zien welke aanpassingen je in de file gemaakt hebt.

Maar ja, je kan dat inderdaad ook zelf doen.  ;-)
