### ISSUE TITLE
load_data_deadwood: extra variabele

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#70]
Is het mogelijk om als ook CalcLength (naast CalcVolume) mee te nemen bij inladen data?

**Comment by leymanan** [comment]
het zou ook handig zijn mocht `deadw_measure_id` meegenomen worden bij `load_data_deadwood()`, ikv datacontrole ....

**Comment by ElsLommelen** [comment]
Euh, gingen we voor de datacontrole de data niet apart inladen (omdat er vaak andere gegevens voor nodig zijn, en andere combinaties van data dan diegenen die in de load-functies ingeladen worden)?  Ik vind die afspraak niet direct terug, maar ik zie dat het in de functie `check_data_trees()` alvast zo gedaan is (data apart inladen).

**Comment by leymanan** [comment]
jaja, dat kan wel zijn!
Maar als er kleine foutjes optreden (tijdens datavewerking) zoals nu bij die max_diam_deadwood, is het toch handig om te zien om welke records het gaat.

**Comment by ElsLommelen** [comment]
ok, ik voeg het toe

**Comment by ElsLommelen** [comment]
Euh, wat is het verschil tussen `deadw_measure_id` (hetgeen je nu voorstelt) en `lying_deadw_id` (de id die je laatst toegevoegd hebt op basis van Deadwood.ID)?  En als er een verschil is: op welke ID moet `deadw_measure_id` gebaseerd worden?

**Comment by leymanan** [comment]
Pff, sorry, gebaseerd op deadwood.ID.
Was vergeten dat lying_deadw_id al bestond.
Had gekeken naar finale tabel en daar geen id zien staan ... en dan naar analogie met trees en shoot seen naam voorgesteld.
Maar is dus zelfde, naam doet er voor mij niet toe.

**Comment by ElsLommelen** [comment]
ok, dan is dit issue dus opgelost?  (`calc_length` voegde ik vorige week al toe)

**Comment by leymanan** [comment]
ok! Bedankt!
