### ISSUE TITLE
create_overview_status() uitbreiden naar meer dan 3 periodes

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#72]
Voorlopig werkt functie `create_overview()` status voor 3 periodes, maar dit zou bij gelegenheid best eens herschreven worden zodat dit blijft werken als er extra periodes bij komen (bij voorkeur op een manier dat niet bij elke periode extra code toegevoegd moet worden).

**Comment by ElsLommelen** [comment]
Intussen is die functie hernoemd naar `create_unique_tree_id()`.

@leymanan  Vraagje voor de zekerheid: hoe wordt omgegaan met een boom die in de eerste en derde periode opgemeten is, maar in de 2de periode niet?  Of wat als bv. die plot in de 2de periode niet opgemeten is?  Worden bomen uit periode 3 dan aan de 1ste periode gekoppeld, en hoe wordt dit aangeduid in de databank (in `old_id`?), of worden ze helemaal niet gekoppeld?

Voorlopig is telkens de `old_id` van een bepaalde periode gekoppeld aan de `tree_measure_id` van `periode - 1` (en dit per `plot_id` om zeker te zijn dat er nooit 2 boommetingen zullen zijn met dezelfde nummer).  Ik zal dit bij de aanpassing naar meer dan 3 periodes zo behouden.  Maar als er bij old_id ook ooit wordt verwezen naar eerdere periodes, moet dat nog aangepast worden.

**Comment by leymanan** [comment]
> @leymanan Vraagje voor de zekerheid: hoe wordt omgegaan met een boom die in de eerste en derde periode opgemeten is, maar in de 2de periode niet? Of wat als bv. die plot in de 2de periode niet opgemeten is? Worden bomen uit periode 3 dan aan de 1ste periode gekoppeld, en hoe wordt dit aangeduid in de databank (in `old_id`?), of worden ze helemaal niet gekoppeld?
> 
> Voorlopig is telkens de `old_id` van een bepaalde periode gekoppeld aan de `tree_measure_id` van `periode - 1` (en dit per `plot_id`). Ik zal dit bij de aanpassing naar meer dan 3 periodes zo behouden. Maar als er bij old_id ook ooit wordt verwezen naar eerdere periodes, moet dat nog aangepast worden.

Er worden enkel bomen gekoppeld aan periode -1
Mocht gebeuren wat je zegt: boom in periode 1 en 3 opgemeten, niet in periode 2, dan is de link verbroken.
Dat kan in theorie niet voorkomen.
Tenzij natuurlijk wanneer de plot in periode 2 niet opgemeten is, maar dan kan er ook geen vgl gemaakt worden tss peridoe 1 en 3. 
Die plots worden bij een analyse (om periodes 1,2 en 3 te vergelijken) uit de dataset verwijderd.
