### ISSUE TITLE
extra variabelen als factor ipv gebruik LU-lijst

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#75]
- levend/dood
- ind/shoot/coppice
- intact/snag 
- ev. ook height_class ( bevat reeds meer levels)

**Comment by leymanan** [comment]
-  codes beter ook in de databank zelf steken. Moesten er ooit aanpassingen zijn, dan gaan tenminste de juiste gegevens opgehaald worden en moet je hiervoor niet in de R-code gaan wroeten.
- Engelstalig maken!!
- nadenken of we met korte codes (CP) of uitgebreidere omschrijving (circular plot) werken

Ter info:
- codes hebben het voordeel dat ze minder typwerk zijn, maar het nadeel dat er nog altijd extra uitleg nodig is om ze te begrijpen. Als je echt wil, kan je bij factoren nog altijd de ID's gebruiken om minder typwerk te hebben.

**Comment by ElsLommelen** [comment]
@leymanan Plottype is in orde (heeft waarden CP en CA), maar zou je even kunnen aangeven hoe de andere waarden best benoemd zouden worden?  Bv. `alive_dead` zou je de waarden 'alive' en 'dead' kunnen geven, zoals in de FM databank (in dat geval zou het handig zijn als de exacte waarden uit de databank gehaald kunnen worden, zodat jullie ze kunnen aanpassen zonder in de code te wroeten), maar als je de variabele hernoemt naar `alive`, zou je de waarden ook door TRUE en FALSE kunnen vervangen.  En voor andere variabelen met 2 mogelijkheden zou ik hetzelfde kunnen doen: telkens 11 vervangen door TRUE en alle rest wordt FALSE, maar in dit geval zal meestal de variabelenaam iets aangepast moeten worden, vermoed ik.

Kan jij een concrete aanzet geven?  Dat kan dus door in FM waarden in te vullen die ik rechtstreeks kan gebruiken, of in dit issue een alternatieve variabelenaam voorstellen en aangeven wat TRUE moet zijn.

**Comment by leymanan** [comment]
Misschien moeten we dit maar zo laten voor de andere variabelen.
Kan iets zijn om package later mee te verfijnen, maar denk dat het beter is dat we ons nu focussen op het zo snel mogelijk (maar natuurlijk correct) afronden van het package, en geen extra's meer toevoegen.

**Comment by leymanan** [comment]
mochten we dat op termijn toch willen implementeren, lijkt het me inderdaad makkelijkste om de korte naam in Value3 van de lookuplijsten uit FieldMap op te slaan (zoals ook bij plottype gebeurd is).

- alive/dead
- intact/snag
- indiv/shoot/copp

Voor `Heightclass` lijkt het me sowieso niet meer opportuun (teveel klasses).

**Comment by leymanan** [comment]
van mij mag je issue sluiten als je dit niet meer gaat opnemen

**Comment by leymanan** [comment]
maar indien wel, laat het me weten en dan bezorg ik je een databank met voor die drie variabelen een `Value 3` in hun lookuplijst.

**Comment by ElsLommelen** [comment]
Euh, ik weet niet meer exact hoe het nu is, maar met het oog op het publiceren van de afgeleide gegevens in forresdat lijkt het me wel proper dat de veldnamen en inhoud informatief zijn (en altijd ervan uitgaan dat niet iedereen de volledige documentatie leest).  En het lijkt me van mijn kant een kleintje om dit even aan te passen in het package (half dagje werk omwille van de vele functies waarin het voorkomt?).  Sowieso is dit iets wat we ofwel nu aanpassen, vooraleer het package en de gegevens gebruikt worden, ofwel niet meer, want zo'n aanpassing achteraf heeft zeer veel impact op de gebruikers.  En uit ervaring weet ik dat het heel vervelend is om er achteraf spijt te hebben van een slecht gekozen naamgeving (je merkt de impact vaak pas als anderen ermee werken, en voor open data denk je best verder dan je team en medewerkers), dus als je het liever aangepast wil, stel ik voor dat we ervoor gaan!

**Comment by leymanan** [comment]
Els, ik heb er wat verder over nagedacht, en ik zou dit laten zoals het nu is.
De waardes zitten in lookuplijsten en dat is goed genoeg zo. Sowieso zijn de lookuplijsten nodig voor nog zoveel andere variabelen.
Het maakt de tabellen ook zwaarder.

Bijkomend zitten die waardes enkel in de trees-tabel, niet in de tabellen op plot-niveau.
