### ISSUE TITLE
calc_ar_tree_level() inbouwen in workflow

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#78]
Iets wat tenminste ik over het hoofd gezien heb...

Het lijkt me het meest logische om de functie `calc_var_tree_level()` uit te voeren in het begin van `calculate_dendrometry()`, en dan anderzijds waar nodig de documentatie en voorbeelden van de andere `calculate`-functies aanpassen.  Op die manier heeft de gebruiker een uitgebreide keuze:
- de fieldmap-gegevens verwerken tot een nieuwe versie voor forresdat (of voor andere reden dezelfde bewerkingen doen) kan eenvoudigweg door de data te laden en `calculate_dendrometry()` te gebruiken
- de gegevens laden, het volume op een eigen manier berekenen, en dan de gewenste `calculate`-functies gebruiken
- de gegevens laden en het volume berekenen met `calc_var_tree_level()`, en er daarna z'n eigen ding mee doen
- de berekeningen uitvoeren op eigen gegevens
- enkel de gegevens uit fieldmap inladen voor eigen gebruik
- ...

Enfin, er zijn enerzijds veel mogelijkheden (waarvoor gegevens uiteraard wel in het juiste formaat moeten staan), en anderzijds moet je basisscript zo niet veranderen.

Een andere optie zou zijn dat je `calc_var_tree_level()` als een aparte stap in je basisscript opneemt en het resultaat hiervan als argument gebruikt bij `calculate_dendrometry()`.  Op die manier geeft je basisscript wel iets transparanter weer wat er gebeurt.  Ook in dat geval zullen de nodige argumenten en documentatie aangepast moeten worden.

**Comment by leymanan** [comment]
op dit moment heb ik de tweede optie gebruikt: `calc_var_tree_level()` als een aparte stap in het basisscript opnemen, en het resultaat hiervan als argument gebruiken bij `calculate_dendrometry()`.  
De documentatie bij de functies is al in die zin aangepast.
Maar misschien moet de algemene documentatie nog aangepast worden?

**Comment by leymanan** [comment]
Misschien ga ik toch voor optie 1: ik bne bang dat men de `calc_var_tree_level()` stap gaat vergeten.
Ik heb immers ook nog een `calc_var_stem_level()` functie aangemaakt, die moet lopen vóór `calc_var_tree_level`

**Comment by ElsLommelen** [comment]
Ok.
We gaan er in dat geval best wel voor zorgen dat ook duidelijk gedocumenteerd is hoe de aparte stappen kunnen gebeuren, zodat gebruikers ook hun weg vinden in die tussenstappen.
Ik merk trouwens dat bij `calculate_dendro_plot_species()` (en waarschijnlijk ook de gelijkaardige functies) het voorbeeld nog niet aangepast is aan het feit dat je nog een `calc_var_stem_level()` toegevoegd hebt.  (Een van de gemakkelijkste manieren voor documentatie, is gebruik maken van die voorbeelden.)

**Comment by leymanan** [comment]
oeps, blijkbaar over hoofd gezien.
Ik dacht dat ik die voorbeelden aangepast had, maar nu met andere workflow misschien toch weer wat fouten ingeslopen ...
Ik check ze nog eens.
