### ISSUE TITLE
testdatasetje toevoegen?

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#81]
In afwachting van unittests zou het misschien goed zijn om de voorbeelden alvast op een gemakkelijke manier te kunnen runnen, kwestie om al ietwat foutcontrole te hebben op de code zelf.  (Als die niet in 'dontrun' staan, worden die automatisch gerund tijdens de checks, en dan geeft een error in een van de voorbeelden ook een error in de check.)  Maar dit kan uiteraard enkel als er een datasetje intern in het package zit.

Ik zie hiervoor op 't eerste zicht 2 mogelijkheden:
- de outputs van `load_data_xxx()` opslaan, waarmee we enkel de `calculate`-functies kunnen testen.  Grote nadeel is dat die datasets telkens moeten aangepast worden als er aanpassingen zijn in de output van de `load_data`-functies.
- een sqlite-databankje toevoegen met dezelfde structuur als de FM-databank, en de functie `query_database()` uitbreiden zodat ze ook hiermee overweg kan.

Behalve voor testredenen is een groot voordeel van deze 'echt werkende' voorbeelden dat gebruikers op basis hiervan gemakkelijk kunnen zien hoe hun dataset eruit moet zien als ze enkel een van de tussenstappen willen uitvoeren.

En vermits het package nu toch vrij goed in orde is qua tests, kunnen we overwegen om deze telkens automatisch te laten uitvoeren bij een push github.  Als jij dit zit zitten, uiteraard, de voorbeelden kunnen meenemen in de manuele check is ook al een stap vooruit.  (Dus ingeval van testen op github gebeurt die 'check' automatisch op het moment dat we instellen, bv. bij elke push, of bij elke push maar pas nadat er een PR naar de master aangemaakt is, of...  En als er errors zijn bij de checks, krijg je een github-email met melding hiervan, en dan kan je via een link die errors en warnings en notes online bekijken.  We kunnen het ook iets uitgebreider doen en dan alle regeltjes volgen die Thierry gebruikt in z'n package [checklist](https://inbo.github.io/checklist/), waarbij vooral de aanwezigheid van documentatie en licentie etc. iets uitgebreider getest wordt.)

Waarschijnlijk aan mij om binnenkort dit issue uit te voeren, maar denk je hier eens over na en laat je dan eens weten hoe jij het ziet.
(Reden van dit issue is dat het intussen nogal wat werk is om alles in te laden om de voorbeelden te testen, nu er ook die hoogtemodellen bijgekomen zijn, en 2 extra functies met voorbeelden...)

**Comment by leymanan** [comment]
Klinkt goed!
Er zijn wel nog enkele issues die output wat gaan wijzigen, ik weet niet of die eerst afgerond moeten zijn (bv. deze om CP en KV te gebruiken ipv 20 en 30)

**Comment by ElsLommelen** [comment]
Als we voor de SQLite gaan, maakt dit niet uit.  (Voor de andere optie wel, tenminste als je die CP en KV al in de `load`-functies aanpast (wat me logisch lijkt).)

We runnen dan in de check gewoon de voorbeelden zonder output te testen ofzo (dus het zijn geen unittests, daar is er nog een apart issue voor, en dat is ook iets meer werk om te maken, vandaar deze snelle oplossing als extra voorstel).  Dus een andere output heeft geen invloed op het al dan niet falen van een test, we krijgen wel een error als het voorbeeld runnen zelf een error geeft.  (Dus als er ergens in een functie gemorreld is, waardoor het resultaat van de ene functie niet meer gebruikt kan worden als input in de andere functie, ofzo.  Een goed voorbeeld is het toevoegen van `calc_variables_stem_level()` en vergeten de voorbeelden aan te passen.  ;-) )

Dit zal sowieso niet meer zijn om deze week aan te beginnen, en uiteraard bekijk ik samen met u wanneer we het past om dit naar de master te brengen.  Aan die SQLite heb ik ongetwijfeld wat werk (Access en SQLite lijken me geen al te beste vriendjes), de rest is hopelijk wel peanuts, maar in elk geval gaat het nog wel eventjes duren tot dat af is.  En tegen die tijd overleggen we weleens wanneer het past dat ik de branch merge.  En misschien liefst ook of en wat we evt. automatiseren op github.  Evt. kunnen we hier tegen dan een overlegje over inplannen zodat ik je de mogelijkheden uitleg?

**Comment by leymanan** [comment]
OK! Goed voorstel!
(CP en KV idd al in `load`-functies)

**Comment by ElsLommelen** [comment]
Nota: ik ben ooit begonnen aan een functie `access_to_sqlite()`, een goed vertrekpunt als we hiervoor met 'echte' gegevens werken.  (In dit geval liefst wel een kleine selectie maken van enkele metingen voor enkele BR en plots enz.)

**Comment by leymanan** [comment]
is het dan de bedoeling dat ik een databank aanmaak met bv. 2 bosreservaten, en daarbinnnen bv. de eerste 5 CP's en de CA?
en je die bezorg?

**Comment by ElsLommelen** [comment]
Misschien handiger om gewoon in de queries zelf een selectie te maken en die uit te voeren op een kopie van de FM-databank?  Dan kan je dat script herbruiken als er eens aanpassingen zijn in de databankstructuur, lijkt me iets minder werk dan telkens een nieuwe databank aan te maken.  (Dat wordt dan een extra scriptje voor de folder `data-raw`: scripts om de interne data van forrescalc te genereren, die enkel in uitzonderlijke omstandigheden gerund moeten worden.)

2 bosreservaten met daarbinnen 5 CP's en de CA klinkt goed als aanzet.  Ik dacht dan om bv. telkens de eerste 5 records per periode te selecteren, of afhankelijk van de gegevens de eerste 5 records per hoogteklasse,...  Of misschien van 1 CP meer records om hiermee de analyses wat grondiger te kunnen testen, en van de andere die 5 records om te kunnen testen of selecties (bv. in `load`-functies) in orde zijn.  En dan is het uiteraard ook de bedoeling om er wat speciale situaties in te steken.  Enfin, in dit issue is de bedoeling beschreven om de voorbeelden te testen, maar uiteindelijk zou ik de inhoud van de database bepalen/aanpassen i.f.v. de noden voor unittests (issue #24).  (Alternatief is om een volledig fictieve databank aan te maken, vergelijkbaar met de unittests in dhcurve, maar in dit geval lijkt me gegevens overnemen op 't eerste zicht iets minder werk.)

Handig zou zijn, moest je evt. kunnen aangeven welke bosreservaten en welke CP ik beter wel of niet zou gebruiken, als dit iets uitmaakt.  Is er bv. een bosreservaat met CP met weinig gegevens ofzo?  (Dan kan ik evt. alle gegevens nemen zonder dat de databank direct te groot wordt voor in het package.)  Of een CP zonder gegevens? ...  Zijn er andere speciallekes waar je aan denkt om te testen?
En anderzijds: wat er getest moet worden, mag je altijd aanvullen in issue #24 van de unittests.  (Ik vul dat nu systematisch aan als ik problemen tegenkom, bij andere packages zou ik in zo'n situatie direct een unittest toevoegen, maar nu is die stap te groot omdat die testdatabank hiervoor nodig is.  En ik wil liever zorgen dat de andere issues eerst opgelost zijn, zodat jullie verder kunnen.)

**Comment by leymanan** [comment]
> Handig zou zijn, moest je evt. kunnen aangeven welke bosreservaten en welke CP ik beter wel of niet zou gebruiken, als dit iets uitmaakt. Is er bv. een bosreservaat met CP met weinig gegevens ofzo? (Dan kan ik evt. alle gegevens nemen zonder dat de databank direct te groot wordt voor in het package.) Of een CP zonder gegevens? ... Zijn er andere speciallekes waar je aan denkt om te testen?

Sorry dat ik hier nog niet eerder op geantwoord had.

CA's: 21000 als standaard, en 11000 als specialleke, eventueel ook 141100?
CP's: 101 als standaard, met eventueel als speciallekes: 204, 1005, 2006?

Of wordt dat teveel? (3 CP's en 4 CA's?)

Wat betreft soorten: selectie lijkt me OK: boomsoorten (qSpecies: 6, 7, 16, 87 (berk, beuk, esdoorn, eik)) en kruidlaagsoorten (qHerbSpecies240810: 131 en 161 (Bosanemoon en Braam)) .
Eventueel nog Grove den toevoegen: id = 26

**Comment by ElsLommelen** [comment]
Lijkt me wel haalbaar, momenteel (met 21000, 11000 en 101) is de databank 356 kb, dus dat verdubbelen lijkt me nog wel ok als het nuttig is voor de gebruikers (en de unittests).  Kan je wel nog aangeven wat er speciaal is aan de nieuw opgegeven plots, en wat ik er dus bij de unittests op kan testen wat niet kan op de andere plots?

**Comment by leymanan** [comment]
> Kan je wel nog aangeven wat er speciaal is aan de nieuw opgegeven plots, en wat ik er dus bij de unittests op kan testen wat niet kan op de andere plots?

141100: afwijkende oppervlakte (0.5 ipv 0.98 ha)
11000: afwijkende treshold diameter voor liggend dood hout

204: afwijkende treshold diameter voor A3 (staande, levende bomen vanaf 10 cm in A3) + afwijkende rA1, rA2, rA3, rA4 + geen veg-opname
1005: afwijkende treshold diameter voor A4 (staande, levende bomen vanaf 5 cm in A4)  + afwijkende rA3, rA4 
2006: afwijkende treshold diameter voor A4 (staande, levende bomen vanaf 30 cm in A4)  + afwijkende rA1, rA2, rA3, rA4

**Comment by leymanan** [comment]
trouwens wel een heel goede opzet van die test-databank!
Super makkelijk dat die afgeleid kan worden van de volledige db!

**Comment by leymanan** [comment]
> Lijkt me wel haalbaar, momenteel (met 21000, 11000 en 101) is de databank 356 kb, dus dat verdubbelen lijkt me nog wel ok als het nuttig is voor de gebruikers (en de unittests).

Misschien kunnen we ook elke tabel aftoppen op eerste 5 of 10 records?
Maar dan heb je natuurlijk per plot  niet meer de correcte resultaten.
Anderzijds heb je die ook niet omdat je maar een aantal soorten behoudt ...

Misschien enkel overwegen als testdatabase te groot wordt?

**Comment by ElsLommelen** [comment]
> > Lijkt me wel haalbaar, momenteel (met 21000, 11000 en 101) is de databank 356 kb, dus dat verdubbelen lijkt me nog wel ok als het nuttig is voor de gebruikers (en de unittests).
> 
> Misschien kunnen we ook elke tabel aftoppen op eerste 5 of 10 records? Maar dan heb je natuurlijk per plot niet meer de correcte resultaten. Anderzijds heb je die ook niet omdat je maar een aantal soorten behoudt ...
> 
> Misschien enkel overwegen als testdatabase te groot wordt?

Goed idee, al wil je om te testen misschien ook wel enkele 'complete' gegevens.  Misschien de 'standaards' volledig houden en de 'speciallekes' aftoppen op de eerste 5 records en/of minder soorten meenemen (bv. beperken tot 1 of 2 soorten)?  Of loop ik dan het risico dat ik het 'speciale' mis?  Misschien met `sample()` werken om 5 willekeurige gegevens te nemen (en niet de eerste of de laatste of de hoogste of de laagste), en dan even checken dat het speciale getest kan worden (bv. de kleine diameters aanwezig zijn)?  Enfin, ik zal wel wat puzzelen om een zo klein mogelijke databank te bekomen met toch genoeg testgegevens.  (En sowieso kunnen we het in de toekomst ook bij 3 perioden houden.)

De resultaten die niet op soortniveau gegroepeerd zijn, zullen inderdaad anders zijn dan je volledige databank, maar dat maakt niet uit: voor de unittests moeten we gewoon zorgen dat we de correcte resultaten kennen voor onze testdatabank zodat we de vergelijking kunnen maken.

**Comment by ElsLommelen** [comment]
Nog wat extra nota's en bedenkingen in verband met het testdatabankje:
- misschien tabellen van 2de en 3de set ook aanmaken op basis van functie `query_reltable()` zodat de OldID's bestaan in de 1ste en 2de set?  Anderzijds wil je ook enkele records zonder OldID om een realistische situatie te hebben waarin niet elke boom gekoppeld kan worden
- in verband met de test van de `check_data`-functies wil je enkele fouten in de dataset (bv. OldId die nergens naar verwijst,...), hoe dit aanpakken?  Fouten in deze testdataset steken, of maak je een aparte, afgeleide dataset met enkele fouten?  Vraag is ook: is dit ideaal om ook te gebruiken om de andere functies te testen, of net niet?  (Sowieso kan het wel een voordeel zijn voor de examples van de `check_data`-functies om hier wat output te hebben, dus een dataset met fouten zou sowieso best in het package beschikbaar zijn.)  Dus vraag is: 1 dataset die wat fouten bevat en wat goede voorbeelden, of 2 datasets: eentje met fouten en eentje zonder fouten?

**Comment by ElsLommelen** [comment]
nog eentje om zeker in de dataset te hebben: boom met coppice_id die initieel volledig levend is, en vanaf een bepaalde periode een levend en dood deel heeft (zit al in huidige testdataset, maar niet voor alle periodes, dus opletten dat die er uiteindelijk zeker terug bij zit)

**Comment by ElsLommelen** [comment]
Voor Herblayer hadden we eigenlijk nog niet echt soorten geselecteerd om te gebruiken.  Ik heb hier voorlopig zelf een knoop doorgehakt op basis van wat het meest voorkwam in de plots die we geselecteerd hadden:  71 (beuk), 131 (bosanemoon), 165 (brede stekelvaren), 680 (klimop), 1058 (smalle stekelvaren) en 1371 (zomereik).  Laat maar weten als je een beter voorstel hebt.  (Op zich maakt het niet heel veel uit welke soorten dat precies zijn: het gaat over een voorbeelddatasetje of testdatasetje dat de gebruiker een idee geeft van hoe zo'n fieldmapdatabank in elkaar zit, en het geeft ons de gelegenheid om voorbeelden te testen en evt. unittests te schrijven zodat we in de toekomst merken als er iets mis is met de berekeningen in een van de functies.  Belangrijkste is eigenlijk dat er iets in zit, vandaar de keuze voor veel voorkomende soorten in die plots.)

**Comment by ElsLommelen** [comment]
> > Kan je wel nog aangeven wat er speciaal is aan de nieuw opgegeven plots, en wat ik er dus bij de unittests op kan testen wat niet kan op de andere plots?
> 
> 141100: afwijkende oppervlakte (0.5 ipv 0.98 ha) 11000: afwijkende treshold diameter voor liggend dood hout
> 
> 204: afwijkende treshold diameter voor A3 (staande, levende bomen vanaf 10 cm in A3) + afwijkende rA1, rA2, rA3, rA4 + geen veg-opname 1005: afwijkende treshold diameter voor A4 (staande, levende bomen vanaf 5 cm in A4) + afwijkende rA3, rA4 2006: afwijkende treshold diameter voor A4 (staande, levende bomen vanaf 30 cm in A4) + afwijkende rA1, rA2, rA3, rA4

Vraagje in verband hiermee: voor `check_data_trees()` test ik voor A4 of de boom binnen de 18 m van het centrum van de plot ligt, en voor A3 binnen de 9 m, maar dit geeft wel wat afwijkingen voor die afwijkende plots.  Zou het beter zijn als ik test of die bomen binnen rA4 en rA3 liggen i.p.v. binnen 18 en 9 m?  (Voor de rekenfuncties is dit wel juist gedaan, als ik het me goed herinner.)

**Comment by ElsLommelen** [comment]
Oeps, voor commits 1f35a97 en 1e4c8e4 ben ik dit issue vergeten toevoegen, maar de dataset ziet er dus nu ongeveer uit als hierboven beschreven: ongeveer 10 gegevens van de standaardplots, ongeveer 3 gegevens van de extra plots met afwijkingen, en dezelfde bomen zijn meegenomen voor de 3 periodes, al zijn er ook enkele nieuwe toegevoegd die er in de vorige periode niet bij waren.  Ik heb wel t.o.v. eerdere afspraken een extra boomsoort (28) toegevoegd om een interessante hakhoutstoof erbij te kunnen hebben (met het oog op tests).

**Comment by leymanan** [comment]
> Vraagje in verband hiermee: voor `check_data_trees()` test ik voor A4 of de boom binnen de 18 m van het centrum van de plot ligt, en voor A3 binnen de 9 m, maar dit geeft wel wat afwijkingen voor die afwijkende plots. Zou het beter zijn als ik test of die bomen binnen rA4 en rA3 liggen i.p.v. binnen 18 en 9 m? (Voor de rekenfuncties is dit wel juist gedaan, als ik het me goed herinner.)
> 
> Die vraag hoort eigenlijk bij issue #66, maar ik kwam ze tegen door dit issue op te lossen...

ja, inderdaad beter om rA4 en rA3 te gebruiken

**Comment by ElsLommelen** [comment]
Ik heb nog een foutje ontdekt dankzij het schrijven van de unittests, en ik heb ook nog een vraag:
- als `ind_sht_cop` NA is of iets verschillend van 10, 11 en 12 is, en `coppice_id` NA is (en `ind_sht_cop` dus een al een opmerking krijgt), komt bij `coppice_id` de opmerking "missing".  Dit lijkt me overbodig, laat ik dit zo of geef ik de opmerking van `coppice_id` enkel als `ind_sht_cop` 12 is en niet NA?

**Comment by leymanan** [comment]
> Ik heb nog een foutje ontdekt dankzij het schrijven van de unittests, en ik heb ook nog een vraag:
> 
> * als `ind_sht_cop` NA is of iets verschillend van 10, 11 en 12 is, en `coppice_id` NA is (en `ind_sht_cop` dus een al een opmerking krijgt), komt bij `coppice_id` de opmerking "missing".  Dit lijkt me overbodig, laat ik dit zo of geef ik de opmerking van `coppice_id` enkel als `ind_sht_cop` 12 is en niet NA?

is inderdaad overbodig, zou beter zijn enkel deze melding te geven als `ind_sht_cop` 12 is en niet NA.

**Comment by leymanan** [comment]
> Door een unittest voor `check_tree_evolution()` merk ik dat de functie vastloopt als er 2 records zijn met hetzelfde old_id. Wat doe ik hiermee?
> 
> Even situeren: bij deze functie wordt als eerste test gecheckt of er dubbels zijn bij de old_id, en de error treedt pas nadien op als records van opeenvolgende periodes gekoppeld worden om deze te vergelijken. Dus de error kan vermeden worden door bv. deze records na de eerste test te wissen, maar dat heeft wel als gevolg dat andere tests niet op deze records gebeuren en dat er dus na het oplossen van dit probleem in de databank zeker opnieuw getest moet worden. Maar zoals al meermaals aangehaald: je blijft sowieso best testen tot alles opgelost is, want elke aanpassing kan een nieuwe fout genereren, en er zijn ook andere situaties waarin fouten pas getest kunnen worden nadat andere fouten opgelost zijn.
> 
> Dus wat doe ik hier, die records wegsmijten na die eerste test, waardoor ze niet alle tests doorlopen? (Als deze records bv. uit periode 2 komen, zal dit sowieso betekenen dat zowel verschillen tussen periodes 1 en 2 als periodes 2 en 3 niet getest worden voor die bepaalde boom, maar alternatief is dat de functie een error geeft en niet uitgevoerd wordt, ook niet voor andere bomen...)

Klopt toch dat er wél een foutmelding zou gegeven worden "dubbele old_id", maar dat die records "weggegooid" worden vooraleer de volgende tests gebeuren.
Als dat zo is, zouden - na oplossen van dubbele old_id - `check_tree_evolution()` opnieuw gerund moeten worden?
Dat lijkt me inderdaad de beste oplossing en ik zie daar geen probleem.

Misschien kan dat bij de informatie van de functie `check_tree_evolution()` meegegeven worden (zoiets als: "Attention: if double old_id, rerun function after solving the problem")

**Comment by ElsLommelen** [comment]
> Misschien kan dat bij de informatie van de functie `check_tree_evolution()` meegegeven worden (zoiets als: "Attention: if double old_id, rerun function after solving the problem")

Vraag is dan: moeten we dat ook niet bij andere functies meegeven?  Want een probleem oplossen betekent eigenlijk altijd dat je ergens iets aanpast, en die aanpassing moet sowieso nog gecontroleerd worden op juistheid...  (En er zitten sowieso nog wel andere situaties in waar bepaalde fouten niet gecheckt kunnen worden zolang andere niet opgelost zijn: bv. zolang alive_dead niet ingevuld is, zal niet gecheckt kunnen worden of decay_stage correct ingevuld is.)  Dus ergens is het gewoon logisch dat die scripts opnieuw gerund worden tot er geen fouten meer uit komen.  Dus misschien ons beperken tot het kort vermelden van deze werkwijze bij check-functies (blijven herhalen) in het vignette?
