### ISSUE TITLE
load_plotinfo: kleine verbetering, niet dringend

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#83]
eventueel extra code toevoegen waarbij onderscheid gemaakt wordt tss welke data uit forresdat ingelezen wordt:
- dendro: dan mag ev. joinen op "year" én dan survey_veg en survey_reg verwijderen
- reg: NIET joinen op year én verwijderen van year, survey_trees, survey_deadw, survey_veg
- veg en herblayer: NIET joinen op year én verwijderen van year, survey_trees, survey_deadw, survey_reg

**Comment by ElsLommelen** [comment]
- in `read_forresdat()` is year in `plotinfo` verwijderd voor de join in commit 5500623de219ac4d8c7d2d8117306292a624c850
- verwijderen van overbodige variabelen bekijken samen met [deze suggestie](https://github.com/inbo/forrescalc/issues/63#issuecomment-893532051), maar lijkt me nogal lastig om zo'n tabelspecifieke handeling uit te voeren in een generieke functie (tenzij dit overzichtelijk in een tabelleke bijgehouden wordt, maar het lastige is om dit up-to-date te houden als er tabellen bij komen of hernoemd worden).

**Comment by ElsLommelen** [comment]
Enkele vraagjes:
- zijn er in forresdat eigenlijk tabellen waarin geen record opgenomen is voor een `plot_id`-`periode`-combinatie waarbij `survey_xxx_YN = 10` en `DataProcessed_YN = 10`?  (Omgekeerd ga ik ervan uit dat records die hieraan niet voldoen, niet opgenomen zijn, nu issue #58 opgelost is.)
- als er voor elk `plot_id`-`periode`-combinatie minstens 1 record aanwezig is in de tabellen van forresdat, wat is dan nog het nut van die extra variabelen beginnend met `survey_` in forresdat?  Op basis van `add_zeros()` kunnen we dan toch eventuele ontbrekende records (voor soorten,...) toevoegen door simpelweg `plot_id` en `periode` op te geven als `grouping_vars`?  Die `survey_`-variabelen lijken me eerlijk gezegd enkel extra ballast voor gebruikers van de dataset: variabelen die overal een waarde TRUE hebben (want FALSE zit niet in forresdat) en die eigenlijk eerder dienen voor interne controles.
- Moesten de records toch nuttig zijn om mee te nemen in forresdat, zou het dan niet logischer zijn om die survey-variabelen toe te voegen aan de tabellen met gegevens zelf (als dat niet extreem veel extra records genereert, uiteraard)?

Ik heb het gevoel dat we het nu allemaal extra moeilijk aan 't maken zijn op niks: een aantal variabelen/info die eigenlijk specifiek zijn voor 1 type gegevens (dendro of veg of reg), samensteken in 1 tabel, en bij het ophalen van de gegevens moeten die weer bij de respectievelijke gegevens gestoken worden en de andere kolommen gewist...  Als die info bij welbepaalde gegevens hoort, zetten we die er best van in het begin bij, lijkt mij.  (Echte generieke gegevens zoals `year` en `forest_reserve` kunnen uiteraard wel in een generieke tabel blijven.)

**Comment by leymanan** [comment]
inderdaad, je hebt gelijk.
Goed afbakenen wat we willen!

(1) Ik wil met `load_plotinfo `de mogelijkheid hebben om alle info over alle plot-period-combinaties op te vragen: dus ook waar zijn welke opnames gebeurd (= alle survey-velden). 
(2) ik wil de mogelijkheid om enkel de processed_data in te laden => issue #58  - OK
(3) ik wil bij `read_forresdat` volgende plotinfo kunnen koppelen aan de statistieken: plottype, forest_reserve, survey_number. (year zit al in de plot-level-data)

Ik heb in die zin ook wat suggesties gedaan in branch `statistics and other issues`.
