### ISSUE TITLE
naam van subplot toevoegen bij load_data_reg/veg/herbl 

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#84]
enkel relevant voor core area's: soms is het handig om te weten over welke subplot het gaat.
Niet van belang voor de `calculate_xxx` -functies, maar is een beetje zoals de `load_data_dendrometry`: handig om ook wat extra variabelen te kunnen inladen, als er gevraagd wordt naar de ruwe data.

Ik had dat eerst zelf toegevoegd aan de functies, in de query: 
```
Reg.Plotnr AS subplot_name
```
maar kreeg foutmelding
```
FROM ((Plots
          INNER JOIN PlotDetails_%1$deSet pd ON Plots.ID = pd.IDPlots)
          INNER JOIN [... truncated]Error: Can't combine `..1$subplot_name` <character> and `..2$subplot_name` <integer>.
```

Ik vind de oorzaak niet, dus heb ik deze terug verwijderd uit de functies.

Maar zou wel handig zijn, mocht dat op termijn toch toegevoegd worden, al dan niet met behulp van extra argument `extra_variables`

**Comment by ElsLommelen** [comment]
(Antwoord van @leymanan gewenst om meteen het juiste te doen.)

**Comment by leymanan** [comment]
eens gaan kijken in databank, en wellicht is het het veiligste om niet met `Plotnr` te werken, maar met `ID`  
(in regeneration layer en vegetation layer; wat betreft herblayer betreft het `IDVegetation` (= ID in layer Vegetation)).

Voor cirkelplots zijn die ID's steeds 1 (en niet belangrijk), maar bij de kernvlaktes bevatten die wel info over de (locatie van) de subplot.

En ja, enkel deze ene variabele. Er is immers geen echte subplot-laag, is eerder een extra variabele in de tabel regeneration en vegetation, die aangeeft in welke subplot van de kernvlakte de opname gebeurt.

**Comment by ElsLommelen** [comment]
Ik zie dat dit al toegevoegd is in commits de8ad7f, 3bccaa0 en f9dde2d (zonder te verwijzen naar dit issue), dus ik neem aan dat dit in orde is en dicht mag?
