### ISSUE TITLE
Foutmelding bij gebruik load_data_dendrometry in combinatie met argument "forest_reserve"

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#86]
Ik krijg volgende foutmeling als ik "forest_reserve" specifieer. Ik krijg die foutmelding niet als ik enkel plottype opgeef of extra variabels vraag.
Achteraf filteren op forest_reserve lukt wel 

```
trees <- load_data_dendrometry(database = path_to_fieldmap, plottype = "Core area", forest_reserve = "Muizenbos", extra_variables = TRUE)

Error: Can't combine `..1$date_dendro` <datetime<local>> and `..2$date_dendro` <character>. 
```

**Comment by leymanan** [comment]
Dezelfde foutmelding komt voor bij load_data_deadwood/reg/veg ...
Ik weet niet of je dat ook aangepast had?

Bij load_data_reg met variabele plottype = core area, krijg ik ook nog de cirkelplots?

**Comment by ElsLommelen** [comment]
Ik heb de aanpassing generiek gedaan in de functie `query_database()`, dus dit zou voor alle `load`-functies in orde moeten zijn (zie info in PR #87).  Ik heb elk van de `load`-functies getest, en o.a. de code die je hierboven opgeeft, maar ik heb niet bij alle functies verschillende argumenten getest (en eerlijk gezegd de resultaat-dataset ook niet in detail bekeken, ik ging ervan uit dat het probleem was dat je een error kreeg en dat de functie zelf in orde was).

Het feit dat `plottype = "Core area"` nog niet werkt, heeft dat niet te maken met het feit dat bij plottype momenteel nog de id's opgehaald worden?  (Ik zie niet direct het issue waarin die aanpassing aangevraagd wordt, dus dit mss open laten bij wijze van herinnering?)

**Comment by leymanan** [comment]
ok!
Is wel enkel bij regeneration dat filteren op core area niet werkt ...

**Comment by leymanan** [comment]
Hoi Els,

blijkbaar heb ik nog steeds dit probleem, maar niet voor alle bosreservaten. 
Het probleem doet zich precies vooral voor wanneer er geen opnames gebeurd zijn in 1e of 2eSET.
Dan is er ook geen DateDendro ingevuld voor die periodes ... kan dat een probleem zijn? 
Ik heb het zelf niet verder bekeken.

ik trek mijn plan nu met achteraf filteren, ook niet zo erg, maar op termijn moet het wel opgelost geraken.

Bedankt!

**Comment by ElsLommelen** [comment]
Kan je een concreet voorbeeld geven, of minstens aangeven in welke functie en onder welke omstandigheden dit probleem zich nog stelt?  En ook: welke branch heb je geïnstalleerd om dit te testen?  Is dat de branch `statistics-and-other-issues` waarin ik dit item opgelost heb?

**Comment by leymanan** [comment]
Ik heb nu `branch statistics ..`  gepullt, gebuild en nu krijg ik volgende foutmelding (na uitvoeren onderstaande code.

> plot_type
[1] "Circular plot"
> forestreserve
[1] "Zwaenepoel"

> trees <- load_data_dendrometry(database = path_to_fieldmap_db, 
+                                plottype = plot_type, 
+                                forest_reserve = forestreserve, 
+                                extra_variables = TRUE)


 **Error in check_input(plottype, database, "qPlotType", "Value3") : 
Input value 'Circular plot' should be one of the following values:NA**

Wellicht omdat plottype in Value2 staat, en niet in Value3 ...

**Comment by leymanan** [comment]
Blijkbaar zijn er in die branch andere zaken die verouderd zijn, kan dat? Zo is bij `load_data_shoots`, de optie om extra variabelen zoals iufro-klasses in te laden, niet aanwezig.

**Comment by leymanan** [comment]
in branch `issue90` heb ik volgende foutmelding met 
plot_type
[1] "Circular plot"
forestreserve
[1] "Zwaenepoel"

 `Error: Can't combine `..1$date_dendro` <character> and `..2$date_dendro` <datetime<local>>.`

**Comment by ElsLommelen** [comment]
Tip: als je in github onder code voor branches kiest, krijg je [deze pagina](https://github.com/inbo/forrescalc/branches), waaruit je bv. kan afleiden dat je `reg_AL` inderdaad 4 commits achter staat t.o.v. de master.  En zie dan de handleiding van samenwerken in github voor info over hoe je die kan updaten t.o.v. de master.

In github zijn er ook opties om branches te vergelijken, en in RStudio onder de tab git kan je ook de history opvragen, en dat geeft ook een goed overzicht hoe branches zich t.o.v. elkaar verhouden.  Enfin, meerdere manieren om te bekijken hoe het precies zit, elk met z'n voor- en nadelen.  Verken het gerust even als je daar zin in hebt, je hebt hier een ideale situatie met meerdere branches.  ;-)

(De problemen lijken inderdaad te liggen aan het feit dat we met meerdere branches aan 't werken zijn.  Idealiter wordt een branch op relatief korte termijn afgewerkt en gemerged, of toch een die belangrijke fouten oplost, en idealiter worden andere (langlopende) branches ook bijgewerkt nadat de master is bijgewerkt.  Langlopende branches kan dus, maar enkel voor niet dringende zaken (bv. een handleiding of extra functionaliteit), en dan is het uiteraard kwestie om te zorgen voor een regelmatige update met de master om conflicten voor te blijven.)

**Comment by leymanan** [comment]
Ter info: ik heb mijn branch (`reg_AL`) bijgewerkt met `master `en dus ook met branch `update_query_database` 
Maar ik krijg nog steeds foutmelding bji Zwaenepoel (BR met enkel opnames in 3de decade)
(maar ik kan wel verder, dan filter ik gewoon achteraf)

```
forestreserve <- "Zwaenepoel"
plot_type <- "Circular plot"

trees <- load_data_dendrometry(database = path_to_fieldmap_db, 
                                plottype = plot_type, 
                                forest_reserve = forestreserve, 
                                extra_variables = TRUE)

 Error: Can't combine `..1$date_dendro` <character> and `..2$date_dendro` <datetime<local>>.
```

**Comment by ElsLommelen** [comment]
Ik heb dit script even getest, en in mijn geval (mogelijk een verouderde databank) krijg ik geen error (als ik van `"Circular plot"` `"CP"` maak), wel een dataframe met 0 rijen.  Met `forestreserve <- "Everzwijnbad"` krijg ik wel een dataframe met enkele duizenden rijen.  Dus dit lijkt opgelost.
Kan je even checken of dit probleem zich bij u nog stelt als je een recente versie van branch bug-fixes installeert?

**Comment by leymanan** [comment]
klopt toch dat ik enkel in forrescalc-project de branch bug-fixes moet uitchecken en dan builden?
En dan mijn R-dataverwerking-project opnieuw openen en library(forrescalc) runnen?

**Comment by ElsLommelen** [comment]
Ok, bedankt!  Met die recente versie van de databank krijg ik inderdaad dezelfde fout.  Waarschijnlijk had mijn oude versie van de databank enkel gegevens van periode 1 en 2 voor Zwaenepoel, vandaar dat ik een lege dataset als resultaat kreeg?  Dit is duidelijk iets wat met het toevoegen van die 3de versie te maken heeft (en vooral het feit dat er daarbij in m'n code nog een bug zit), ik los het meteen even op.



> klopt toch dat ik enkel in forrescalc-project de branch bug-fixes moet uitchecken en dan builden?
> En dan mijn R-dataverwerking-project opnieuw openen en library(forrescalc) runnen?

Ja, dat is inderdaad voldoende om de nieuwe versie te installeren (belangrijk is inderdaad dat uw R-dataverwerking-project intussen dicht is).
Alternatief is om `remotes::install_github("inbo/forrescalc@bug-fixes")` te runnen (met disclaimer voor eventuele typo's, want ik heb het niet getest), dat kan gewoon in je R-dataverwerking-project als je forrescalc nog niet geladen hebt (ofwel eerst even ctrl-shift-F10 doen om R te herstarten in je project).  Dat is iets meer typwerk, maar iets minder gedoe als je al wat datasets geladen hebt en je je project liever niet sluit (bij herstarten van R in RStudio blijven die tegenwoordig behouden, heb ik al gemerkt).  Dit ter info, moest het ooit eens gemakkelijker zijn om je project niet te moeten sluiten.

Met uw versie was dus niks mis, verschil zat hem in het feit dat ik een oudere databank gebruikte.

**Comment by ElsLommelen** [comment]
Voila, deze bug zou opgelost moeten zijn.  Blijkbaar had ik er nooit aan gedacht dat het weleens zou kunnen dat er in de eerste periode(s) niks opgemeten was en in de volgende periode(s) wel.  En zoals je misschien ooit gemerkt hebt: bij een lege dataframe kan het toegekende datatype van een kolom nogal eens afwijken, wat problemen geeft als je die aan een andere dataset plakt met bind_rows()...

Moest je nog andere bugs vinden in deze of andere functies, laat zeker weten (hier of in een nieuw issue, je kiest maar).  Ik probeer de code robuust te schrijven, maar ik ga niet alle bosreservaten afzonderlijk testen of alle combinaties van argumenten, dus het is niet onmogelijk dat er hier of daar nog wel iets opduikt.  Ik hoop erop dat jij die functies voldoende gebruikt dat dit soort zaken er op termijn wel uit geraakt.  (Tot nu toe lukt dat al redelijk, heb ik de indruk. ;-) )
