### ISSUE TITLE
voorbeelden create_statistics() geven foutmelding

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#88]
De voorbeelden in de help-functie van `create_statistics()` geven een foutmelding omdat de column `year` niet meer zou bestaan.  In de nieuwe opgeladen dataset staan wel `year.x` en `year.y` met niet altijd dezelfde waarde, het resultaat van een slechte join die veroorzaakt wordt doordat `year` in forresdat toegevoegd is aan `plotinfo` in [deze commit](https://github.com/inbo/forresdat/commit/ebc5c2afe9e901591152157399eda620f458af5a).

@leymanan Heb jij nog enig idee waarom `year` (en `period`) toegevoegd is aan tabel `plotinfo` (intussen een jaar geleden)?  Ik neem aan dat je `year` zowel in `plotinfo` als in de tabellen met gegevens in forresdat wil behouden?  Is het in dit geval nuttig om ook `period` overal te behouden?  Of kunnen we `period` evt. verwijderen in de tabellen met gegevens in forresdat en met `read_forresdat()` opladen door `plotinfo` hieraan te koppelen?  (Sowieso moet de join dan aangepast worden zodat ook op `year` gekoppeld wordt.)  Alternatief is om `period` overal te behouden en `year` niet, maar ik weet niet of `year` hetzelfde is voor alle gegevens uit eenzelfde `period`?  Indien niet, dan is het wat lastiger om de tabellen te koppelen op basis van enkel `plot_id` en `period` en gaat m'n voorkeur uit naar `year`...

**Comment by leymanan** [comment]
Ik heb dat toegevoegd, omdat we soms een lijst plots moeten aanleveren met bijhorende info (oa `year`) en dan is het handig dat we van de tabel `plotinfo` kunnen vertrekken.
Maar als je een join doet van `plotinfo` met plot level resultaten, geeft dat inderdaad problemen. Dan moet je `year` soms eerst terug verwijderen. Dat had ik ook al gemerkt.

Net eens gekeken en ja, soms ander year voor eenzelfde periode (en zelfde BR) ...
Bijkomend probleem is dat `year `verschillend kan zijn bij dendro en verjonging/vegetatie, voor eenzelfde periode en plot_id. Dus koppelen obv `year `is ook een gevaarlijke (bv als je dendro en regeneration wil koppelen voor een bepaalde analyse). 
Je wil koppelen obv `period` in dat geval.
Sowieso zou ik willen blijven koppelen obv `period`, lijkt me veiligste en meest correcte. 
`period ` geeft ook een link met de meetmethode, die tussen de decades/periodes lichtjes kan verschillen.

`Year` heb je anderzijds nodig wanneer je bv. vertrekkende van `dendro_by_plot `een analyse wil doen over alle reservaten heen. Dan ga je niet eerst `plotinfo` koppelen. Maar het kan natuurlijk wel.

Dus jouw voorstel om `period` te verwijderen uit forresdat-data en te koppelen mbv `read_forresdat` zou ik niet doen. Bovendien geeft die functie vaak problemen. En ik vrees dat dat bij veel mensen zo gaat blijven, omdat dat verweven zit met git en toelatingen en zo  ...
Ook `year `verwijderen uit alle forresdat-data en koppelen via `read_forresdat ` is geen optie.
Want bij verjonging en vegetatie is er soms een ander `year `(`year `in `plotinfo `is jaar van dendro-opname), dus daar moet dat sowieso behouden blijven.

**DUS: ik zou voorstander zijn om `period` en `year` in alle tabellen te behouden, maar eventueel bij `read_forresdat` eerst `year` te verwijderen uit `plotinfo` en dan pas te joinen? Is dat een optie?**

**Comment by ElsLommelen** [comment]
Ja, dat is uiteraard een optie.  Dan gaan we uiteraard wel moeten joinen op `plot_id` en `period` (en `year` dus verwijderen).

Joinen op `plot_id` en `period` en `year` zou ook kunnen, maar dan gaat je info uit `plotinfo` niet toegevoegd worden voor de gevallen waar `year` in `plotinfo` verschillend is van `year` in de tabel met gegevens.  Aan u om hier de keuze in te maken.

Oei, werkt dat met git nog altijd niet goed?  Hebben ze de installatie met ssl ook gedaan, zoals bij u?  Ok dat je dit even moet installeren volgens het stappenplan en zorgen dat alle instellingen goed staan, maar ik was me niet bewust van het feit dat dat daarna ook nog terug problemen kan geven.  Zelf heb ik toen wat moeten zoeken om die functies in orde te krijgen, maar nadien heb ik er eigenlijk nooit meer problemen mee gehad.  Ik ging nog voor een handleiding zorgen voor die installatie, dus ik hoor graag wat de problemen zijn die opduiken, zodat ik hier voor m'n handleiding rekening mee kan houden.  Ik was trouwens met die workshop ook van plan om dat met het hele team samen te installeren, maar door Corona is er nooit een tweede workshop gekomen...  Ik weet niet hoe jullie dit nu opgelost hebben?  Moest daar nood aan zijn, dan kunnen we binnenkort alsnog een vervolg-workshop doen.  Of anders kan ik de problemen wel individueel oplossen (via email als ze duidelijk aangeven wat het probleem is, via videochat, of evt. even overnemen van hun computer).  Maar laat zeker weten als hier nog problemen rond zijn, niks vervelender dan dat iets niet werkt zoals het hoort omwille van installatieproblemen.

**Comment by leymanan** [comment]
Sowieso liefst steeds koppelen obv `period`. Is veiligste.

Git: bij mij werkt dat nog steeds niet, is sinds ik upgrade naar windows10 gehad heb.
Ik behelp me met read_vc, om de tsv-files vanuit de forresdat-folder binnen te halen.
En ik ga naar forresdat-project om manueel data te pushen of te pullen.

**Comment by ElsLommelen** [comment]
Ok, dan zal ik dat zo aanpassen, en `year` verwijderen bij het koppelen.

Juist ja, ik ben even terug gaan kijken, en ik zie dat ik je laatste email i.v.m. dat probleem met git nog niet beantwoord heb.  Mijn excuses, die moet in een drukke periode tussen de mazen van het net geglipt zijn.  Ik ben vandaag bezig met die functie `create_statistics()` en een oplossing voor de intervallen, daarna pik ik dit meteen terug op (mogelijk maandag).

Sowieso moet je **push** manueel doen, want je moet eerst lokaal in forresdat checken of hetgeen je wil updaten, in orde is (en of je inderdaad enkel de aangepaste records updatet, een goede manier om te checken of alles in orde is).  Ik heb bv. gezien dat je bij je nieuwe commits van 11/6/21 de hele tabelstructuur aangepast hebt, ik weet niet of dat de bedoeling was?  Had je dezelfde sorteervolgorde gebruikt als de commits die gebeuren via `save_results_git()`?  Want als je dat niet aanhoudt en telkens de hele tabellen gaat overschrijven, dan gaat forresdat snel vol zitten, vrees ik (en dan heeft het geen zin dat we zo'n geoptimaliseerd systeem als git2rdata gebruiken).  Dus als het niet werkt, mss toch best even in `save_results_git()` kijken om de tabelstructuur te kunnen aanhouden.  Soit, als ik het package volledig in orde gemaakt heb en je github-probleem opgelost is, zal ik forresdat ook nog even terug op punt zetten.
**Pull** zou normaal inderdaad automatisch moeten gebeuren bij gebruik van `read_forresdat()`.

**Comment by leymanan** [comment]
ja, dat weet ik, van die push en pull.
Ik let er normaal ook op om datastructuur constant te houden en op zelfde velden te sorteren.
(ik heb  dezelfde sorting_max gebruikt als in forrescalc)
Net eens gaan kijken, en volgens mij is het eerder omdat er extra velden aan toegevoegd zijn dat datastructuur veranderd is ...

**Comment by ElsLommelen** [comment]
Ok, goed dat je die sortering aangehouden hebt (aanpassen van de volledige tsv is inderdaad door de aangepaste velden).  Ik vond het eigenlijk vooral vreemd dat in de yml-file de volgorde van de velden aangepast is (wat niet het geval was toen je bv. `year` toevoegde bij `plotinfo`).  Maar misschien heeft dat iets te maken met de recente aanpassingen in git2rdata?
