### ISSUE TITLE
compose_stem_data: integreren van iufro-klasses

### ISSUE THREAD

**Issue by leymanan** [inbo/forrescalc#90]
iufro-klasses worden op niveau van spillen ingevuld.
Dit wil zeggen dat bij hakhout steeds `iufro_xxx = 50 - NVT stoof.`

Na gebruik van `compose_stem_data`, krijgen we dan telkens 2 variabelen per iufro-meting: `iufro_xxx `en `iufro_xxx_shoots`.

Het zou handig en properder zijn mochten deze geïntegreerd zijn in één veld en de `50 - NVT stoof` van `iufro_xxx `steeds vervangen zijn door de waarde van `iufro_xxx_shoots`.

Lastige is dat op dit moment iufro-klasses niet steeds mee ingeladen worden (enkel indien `extra_variables = TRUE`), en dus niet steeds aanwezig zijn in `data_dendro `of `data_shoots`.
Makkelijkste is misschien om die iufro-klasses standaard in te laden bij gebruik van `load_data_dendro `en `load_data_shoots `...?

**Comment by ElsLommelen** [comment]
Goh, ik kan ook met een `if` werken...
De reden dat je ze wil samenvoegen, mag in mijn ogen geen reden zijn om ze standaard in te laden als de meeste gebruikers ze niet nodig hebben, integendeel: op die manier ga je ze nog verplichten om voor hen onnuttige code mee te runnen, en dan moeten ze achteraf nog van de overbodige kolommen af geraken...  En het toevoegen van de basiscode zou ineens ook de vereisten voor de input van `compose_stem_data()` verhogen: de kolommen met iufro-klasses moeten ineens aanwezig zijn in de input data, anders werkt de functie niet (m.a.w. je verplicht ze om die extra kolommen te behouden).  Dus ik denk dat het om meerdere redenen handiger en properder is om het met een `if` op te lossen.
