### ISSUE TITLE
Oude gegevens van Trees_1986

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#95]
Tijdens het herwerken van functie `create_unique_tree_id()` ontdek ik dat bij sommige records van `plot_id` 11000 al in de eerste periode een `old_id` toegevoegd is, vermoedelijk een verwijzing naar de tabel `Trees_1986` in de databank.  In issue #40 was er sprake was om deze ook toe te voegen aan de databank met `periode = 0`, maar die heb ik blijkbaar gesloten na het toevoegen van periode 3.  @leymanan ik veronderstel dat het nog steeds relevant is om deze data toe te voegen?  Klopt het dat dit enkel dendro data zijn (zonder dood hout, gaf je al aan), dus geen veg en reg data?

Nota's voor mezelf:
- zonder dood hout wil zeggen dat ik moet checken dat de nodige NA's toegevoegd worden
- Als het nodig is, zal ik in `create_unique_tree_id()` eventuele problemen rond het ontbreken van deze gegevens opvangen door de `old_id`'s voor `period = 1` vooraf te verwijderen in een afgescheiden codeblok, te checken en evt. te verwijderen nadat dit issue opgelost is.

**Comment by ElsLommelen** [comment]
Ik heb deze data toegevoegd bij `load_data_dentrometry()` en `load_data_shoots()` (wat een lege tabel was, maar afgaande op data_dendro zijn er geen stoven bij deze data).  Ik veronderstel dat dit volledig is?

Ik merk dat bij de berekeningen deze dataset wegvalt bij het uitvoeren van `calc_variables_tree_level()` omdat er nog geen hoogtemodel is voor `periode = 0`.  Kan jij dit bij gelegenheid nog oplossen, @leymanan ?

**Comment by leymanan** [comment]
Ik heb net de hoogtemodellen aangemaakt voor deze periode (zie https://drive.google.com/file/d/1-08YL27W5Ek2ig5Fx7P6n3TGk3IpKfrt/view?usp=sharing)
Zou inderdaad handig zijn mocht deze branch gemerged worden, zodat ook periode 1986 ingeladen wordt. Bedankt!!

**Comment by ElsLommelen** [comment]
Euh, ik vermoed dat dit intussen in orde is?
- Die link naar de googledrive werkt niet meer, maar ik heb wel recentere hoogtemodellen op mijn laptop opgeslagen.  Sowieso gaat het over data die extern zijn aan het package, dus daarvoor moest ik niks aanpassen aan het package zelf.
- En wat het mergen van de branches betreft: alles zit tegenwoordig samen in bug-fixes, en daar worden inderdaad die gegevens uit 1986 mee ingeladen.  Ik heb het even getest, en ze krijgen ook resultaten bij de volumeberekening, dus ik neem aan dat hier niks meer aan moet gebeuren en dit dicht kan?
