### ISSUE TITLE
mogelijkheid om paden op te slaan?

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#96]
Zou het zinvol zijn om op zoek te gaan naar een mogelijkheid om de paden naar fieldmap, forresdat en/of de hoogtemodellen ergens op te slaan in een omgevingsvariabele?  Dit zou dan eenmalig moeten gebeuren bij installatie, en dan zouden die paden via `getenv()` opgehaald kunnen worden, wat handig kan zijn voor het main-script en andere scripts waarin we (of jullie als team) samenwerken.

Door een interne voorbeelddatabank te maken, zou het voor de voorbeelden van functies op basis van FM niet meer nodig zijn, daar kunnen we standaard naar het interne databankje verwijzen (zodat ze effectief als test gerund kunnen worden), voor de functies op basis van forresdat kan het uiteraard wel.

Enfin, 't is maar een ideetje, om eens over na te denken of jullie dit zouden gebruiken.  (Voor dhcurve was er in vroegere versies iets gelijkaardigs met het filetje 'leesfile', maar dat is weggedaan samen met het verwijderen van het main-script.)

**Comment by leymanan** [comment]
Ik zou het niet ingewikkelder maken dan het al is.
Als die paden dan veranderen (sowieso zullen die bij iedereen anders zijn, want we kunnen niet volledig op gdrive werken met R) en de mensen kunnen niet overweg met die getenv() dan zijn er weer extra problemen.

Leen en ik gebruiken voor de VBI een extra script met bestandsnamen dat we bij het begin van elk script runnen.
Ik denk dat zoiets geschikter zal zijn voor gebruik binnen ons team.

**Comment by leymanan** [comment]
misschien eerder dat ik niet op drive werk met R.
Dan moet je gdrive sync afzetten terwijl je bezig bent.
Idem dito voor access-databanken: die komen ook best niet op gdrive...
En ook fieldmap kan niet op gdrive ....

Komt er gewoon op neer dat we niet allemaal dezelfde linken hebben naar de data.

**Comment by ElsLommelen** [comment]
Euh, eerlijk gezegd zet ik die sync niet af, en ik ondervind geen problemen.  Zelfs niet met projecten die op googledrive staan en gelijktijdig onder versiebeheer met git.  Tenminste: scripts runnen geeft geen problemen, maar ik weet niet hoe gdrive omgaat met aanpassingen door meerdere personen in R-bestanden.  Doorgaans werk ik niet samen met R-projecten op gdrive, en als ik dat wel doe, is dat mits zeer duidelijke afspraken wie wanneer het project opent.

Net voor het feit dat het volledige script hetzelfde is met uitzondering van de linken, leek een omgevingsvariabele me een goede oplossing: je zet de linken zelf in een omgevingsvariabele, en verder kan iedereen hetzelfde script hebben.  Zo'n omgevingsvariabele kan op verschillende niveaus gedefinieerd worden:
- op het niveau van een project, en dan is dat een apart bestandje met naam .Renvir waarvan de inhoud (iets als `FMpath="C://..."`) vanzelf inlaadt bij het openen van een project
- op het niveau van een computer, wat als voordeel heeft dat je die omgevingsvariabelen bij alle projecten kan oproepen, maar als nadeel dat het iets lastiger is om die (eenmalig) in te stellen (dit zou ik moeten opzoeken)

I.v.m. de eerste optie werk ik samen met een team dat daar gebruik van maakt, en daar blijkt dat net een zeer handige methode om samen te werken aan een project en de minder ervaren R-gebruikers een aantal lastige zaken te besparen.  (Ze moeten wel bij het eerste gebruik een 'handleiding' doorlopen om o.a. dit op orde te zetten.)  Maar waar ik niet aan gedacht had toen ik het u voorstelde, is dat jullie dit waarschijnlijk in meerdere projecten zullen gebruiken, waardoor we voor de 2de optie moeten gaan.  Ook daar volstaat in principe een handleiding, maar dan op het niveau van forrescalc voor de gebruikers van het package?

Enfin, dus mss niet iets om nu met het team toe te passen, maar moest je interesse hebben om het eens met Leen uit te testen, dan toon ik het je bij gelegenheid weleens.

**Comment by leymanan** [comment]
och ja, gdrive: ik werk daar gewoon niet mee, niet enkel wegens R, maar initieel omdat FieldMap er niet op kan draaien, en acces-databanken ook niet. Enkel mijn administratie en literatuur staat op gdrive.
Ik heb graag mijn data per project zoveel mogelijk bij elkaar, 't is nu al zo'n kluwen, met de zaken die dan wel op gdrive staan (literatuur en gedeelde data van mijn team), met ANB werk ik via sharepoint en onedrive, en dan nog amazon ....
En backup heb ik via github voor de scripts.

Maar zal 't (proberen) onthouden.

Kan inderdaad misschien nuttig zijn voor mij en Leen.
Zijn toch meerdere paden die kunnen gedefinieerd worden?
Anderzijds: we laten ook nog andere scripts runnen, met oa functies en constantes en ...., du sgaat in één beweging.
Als we eens tijd hebben ;-)

**Comment by ElsLommelen** [comment]
Ja, je kan in zo'n documentje zoveel 'omgevingsvariabelen' definiëren als je wil (dit kunnen paden zijn, maar ook andere variabelen, bijvoorbeeld constanten die projectafhankelijk of persoonsafhankelijk zijn).  Ik zal het je weleens tonen als we nog eens samenzitten (of mekaar tegenkomen in Brussel).
