### ISSUE TITLE
seedlings vs established?

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/forrescalc#98]
bij `calculate_regeneration_plot()` en `calculate_regeneration_core_area_species()` wordt verjonging van records waar `subcircle` NA is, toegevoegd aan zowel `seedlings` als `established`.  Ik neem aan dat dit niet veel voorkomt en niet de bedoeling is dat dit voorkomt, maar mss toch beter om dit op te lossen en te kiezen waar we evt NA's bij tellen?

**Comment by ElsLommelen** [comment]
@leymanan Bekijk jij deze vraag nog even?  Ik denk dat deze nog niet opgelost is.

**Comment by leymanan** [comment]
Blijkbaar komt `subcircle  = NA,` enkel voor wanneer er geen verjonging genoteerd/waargenomen werd.
Dus dan moet er zowel bij `seedlings `als bij `established` een "0" geplaatst worden.
Toch indien `Survey_Regeneration_YN = TRUE`

Is het dat wat je bedoelde?

**Comment by ElsLommelen** [comment]
Min of meer, want door je antwoord heb ik nog een bijkomend vraagje:
Check ik bij `subcircle = NA` best of `nr_of_regeneration` inderdaad 0 is?  En wat doe ik als dat niet het geval zou zijn?  Een error gooien?  Of een warning gooien, en waar tel ik in dit geval de `nr_of_regeneration` bij?  (Zie die error of warning vooral als een extra foutcontrole voor u: als je de berekeningen sowieso opnieuw moet doen in dat geval, dan kan je best voor de error kiezen want dan moet je niet op de rekentijd wachten.  Als je liever gewoon voortwerkt en er een generiek regeltje op kan plakken, maar toch wel graag verwittigd wordt, dat dit optreedt, dan is een warning de betere keuze.)
(Geen warning of error is uiteraard ook ok voor mij, maar het is een kleintje om het even toe te voegen, moest het handig zijn.)

**Comment by leymanan** [comment]
volgens mij zorgt de code ervoor dat als `nr_of_regeneration == 0` , `subcircle = NA` in `data_regeneration`

Dus mocht `nr_of_regeneration `toch > 0 zijn, is er inderdaad een `subcircle `die niet bestaat (NA).
Anderzijds: volgens mij kan er geen `nr_of_regeneration` genoteerd worden, als er geen subcircle is.

`nr_of_regeneration` moet sowieso nergens bijgeteld worden, als er geen subcircle is
Liever een warning dan een error.

**Comment by ElsLommelen** [comment]
Normaal zou het niet mogen voorkomen en je zou dus nooit een warning mogen krijgen, maar de warning is dus toegevoegd voor moest je toch ooit in die situatie terechtkomen.
